
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  User: 'User',
  Request: 'Request',
  Homework: 'Homework',
  UserHomework: 'UserHomework',
  StudyGroupRelation: 'StudyGroupRelation',
  StudyGroup: 'StudyGroup'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  username: 'username',
  yandex_email: 'yandex_email',
  verified: 'verified',
  name: 'name',
  last_name: 'last_name',
  patronymic: 'patronymic',
  overdue_tasks: 'overdue_tasks',
  createdAt: 'createdAt',
  role: 'role',
  score: 'score',
  studyGroupId: 'studyGroupId'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const RequestScalarFieldEnum = {
  id: 'id',
  resolved: 'resolved',
  canceled: 'canceled',
  messageId: 'messageId',
  user_id: 'user_id'
} as const

export type RequestScalarFieldEnum = (typeof RequestScalarFieldEnum)[keyof typeof RequestScalarFieldEnum]


export const HomeworkScalarFieldEnum = {
  id: 'id',
  name: 'name',
  deadline: 'deadline',
  studyGroupId: 'studyGroupId',
  expired: 'expired',
  deleted: 'deleted',
  created_at: 'created_at'
} as const

export type HomeworkScalarFieldEnum = (typeof HomeworkScalarFieldEnum)[keyof typeof HomeworkScalarFieldEnum]


export const UserHomeworkScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  homework_id: 'homework_id',
  deleted: 'deleted',
  checked: 'checked',
  score: 'score',
  completedAt: 'completedAt'
} as const

export type UserHomeworkScalarFieldEnum = (typeof UserHomeworkScalarFieldEnum)[keyof typeof UserHomeworkScalarFieldEnum]


export const StudyGroupRelationScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  groupId: 'groupId'
} as const

export type StudyGroupRelationScalarFieldEnum = (typeof StudyGroupRelationScalarFieldEnum)[keyof typeof StudyGroupRelationScalarFieldEnum]


export const StudyGroupScalarFieldEnum = {
  id: 'id',
  grade: 'grade',
  letter: 'letter',
  title: 'title'
} as const

export type StudyGroupScalarFieldEnum = (typeof StudyGroupScalarFieldEnum)[keyof typeof StudyGroupScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

