
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Homework` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Homework
 * 
 */
export type HomeworkModel = runtime.Types.Result.DefaultSelection<Prisma.$HomeworkPayload>

export type AggregateHomework = {
  _count: HomeworkCountAggregateOutputType | null
  _avg: HomeworkAvgAggregateOutputType | null
  _sum: HomeworkSumAggregateOutputType | null
  _min: HomeworkMinAggregateOutputType | null
  _max: HomeworkMaxAggregateOutputType | null
}

export type HomeworkAvgAggregateOutputType = {
  id: number | null
  studyGroupId: number | null
}

export type HomeworkSumAggregateOutputType = {
  id: number | null
  studyGroupId: number | null
}

export type HomeworkMinAggregateOutputType = {
  id: number | null
  name: string | null
  deadline: Date | null
  studyGroupId: number | null
  expired: boolean | null
  deleted: boolean | null
  created_at: Date | null
}

export type HomeworkMaxAggregateOutputType = {
  id: number | null
  name: string | null
  deadline: Date | null
  studyGroupId: number | null
  expired: boolean | null
  deleted: boolean | null
  created_at: Date | null
}

export type HomeworkCountAggregateOutputType = {
  id: number
  name: number
  deadline: number
  studyGroupId: number
  expired: number
  deleted: number
  created_at: number
  _all: number
}


export type HomeworkAvgAggregateInputType = {
  id?: true
  studyGroupId?: true
}

export type HomeworkSumAggregateInputType = {
  id?: true
  studyGroupId?: true
}

export type HomeworkMinAggregateInputType = {
  id?: true
  name?: true
  deadline?: true
  studyGroupId?: true
  expired?: true
  deleted?: true
  created_at?: true
}

export type HomeworkMaxAggregateInputType = {
  id?: true
  name?: true
  deadline?: true
  studyGroupId?: true
  expired?: true
  deleted?: true
  created_at?: true
}

export type HomeworkCountAggregateInputType = {
  id?: true
  name?: true
  deadline?: true
  studyGroupId?: true
  expired?: true
  deleted?: true
  created_at?: true
  _all?: true
}

export type HomeworkAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Homework to aggregate.
   */
  where?: Prisma.HomeworkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Homework to fetch.
   */
  orderBy?: Prisma.HomeworkOrderByWithRelationInput | Prisma.HomeworkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.HomeworkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Homework from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Homework.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Homework
  **/
  _count?: true | HomeworkCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: HomeworkAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: HomeworkSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: HomeworkMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: HomeworkMaxAggregateInputType
}

export type GetHomeworkAggregateType<T extends HomeworkAggregateArgs> = {
      [P in keyof T & keyof AggregateHomework]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateHomework[P]>
    : Prisma.GetScalarType<T[P], AggregateHomework[P]>
}




export type HomeworkGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.HomeworkWhereInput
  orderBy?: Prisma.HomeworkOrderByWithAggregationInput | Prisma.HomeworkOrderByWithAggregationInput[]
  by: Prisma.HomeworkScalarFieldEnum[] | Prisma.HomeworkScalarFieldEnum
  having?: Prisma.HomeworkScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: HomeworkCountAggregateInputType | true
  _avg?: HomeworkAvgAggregateInputType
  _sum?: HomeworkSumAggregateInputType
  _min?: HomeworkMinAggregateInputType
  _max?: HomeworkMaxAggregateInputType
}

export type HomeworkGroupByOutputType = {
  id: number
  name: string
  deadline: Date | null
  studyGroupId: number
  expired: boolean
  deleted: boolean
  created_at: Date
  _count: HomeworkCountAggregateOutputType | null
  _avg: HomeworkAvgAggregateOutputType | null
  _sum: HomeworkSumAggregateOutputType | null
  _min: HomeworkMinAggregateOutputType | null
  _max: HomeworkMaxAggregateOutputType | null
}

type GetHomeworkGroupByPayload<T extends HomeworkGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<HomeworkGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof HomeworkGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], HomeworkGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], HomeworkGroupByOutputType[P]>
      }
    >
  >



export type HomeworkWhereInput = {
  AND?: Prisma.HomeworkWhereInput | Prisma.HomeworkWhereInput[]
  OR?: Prisma.HomeworkWhereInput[]
  NOT?: Prisma.HomeworkWhereInput | Prisma.HomeworkWhereInput[]
  id?: Prisma.IntFilter<"Homework"> | number
  name?: Prisma.StringFilter<"Homework"> | string
  deadline?: Prisma.DateTimeNullableFilter<"Homework"> | Date | string | null
  studyGroupId?: Prisma.IntFilter<"Homework"> | number
  expired?: Prisma.BoolFilter<"Homework"> | boolean
  deleted?: Prisma.BoolFilter<"Homework"> | boolean
  created_at?: Prisma.DateTimeFilter<"Homework"> | Date | string
  studyGroup?: Prisma.XOR<Prisma.StudyGroupScalarRelationFilter, Prisma.StudyGroupWhereInput>
  userHomeworks?: Prisma.UserHomeworkListRelationFilter
}

export type HomeworkOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  deadline?: Prisma.SortOrderInput | Prisma.SortOrder
  studyGroupId?: Prisma.SortOrder
  expired?: Prisma.SortOrder
  deleted?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  studyGroup?: Prisma.StudyGroupOrderByWithRelationInput
  userHomeworks?: Prisma.UserHomeworkOrderByRelationAggregateInput
}

export type HomeworkWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  name?: string
  AND?: Prisma.HomeworkWhereInput | Prisma.HomeworkWhereInput[]
  OR?: Prisma.HomeworkWhereInput[]
  NOT?: Prisma.HomeworkWhereInput | Prisma.HomeworkWhereInput[]
  deadline?: Prisma.DateTimeNullableFilter<"Homework"> | Date | string | null
  studyGroupId?: Prisma.IntFilter<"Homework"> | number
  expired?: Prisma.BoolFilter<"Homework"> | boolean
  deleted?: Prisma.BoolFilter<"Homework"> | boolean
  created_at?: Prisma.DateTimeFilter<"Homework"> | Date | string
  studyGroup?: Prisma.XOR<Prisma.StudyGroupScalarRelationFilter, Prisma.StudyGroupWhereInput>
  userHomeworks?: Prisma.UserHomeworkListRelationFilter
}, "id" | "name">

export type HomeworkOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  deadline?: Prisma.SortOrderInput | Prisma.SortOrder
  studyGroupId?: Prisma.SortOrder
  expired?: Prisma.SortOrder
  deleted?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  _count?: Prisma.HomeworkCountOrderByAggregateInput
  _avg?: Prisma.HomeworkAvgOrderByAggregateInput
  _max?: Prisma.HomeworkMaxOrderByAggregateInput
  _min?: Prisma.HomeworkMinOrderByAggregateInput
  _sum?: Prisma.HomeworkSumOrderByAggregateInput
}

export type HomeworkScalarWhereWithAggregatesInput = {
  AND?: Prisma.HomeworkScalarWhereWithAggregatesInput | Prisma.HomeworkScalarWhereWithAggregatesInput[]
  OR?: Prisma.HomeworkScalarWhereWithAggregatesInput[]
  NOT?: Prisma.HomeworkScalarWhereWithAggregatesInput | Prisma.HomeworkScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Homework"> | number
  name?: Prisma.StringWithAggregatesFilter<"Homework"> | string
  deadline?: Prisma.DateTimeNullableWithAggregatesFilter<"Homework"> | Date | string | null
  studyGroupId?: Prisma.IntWithAggregatesFilter<"Homework"> | number
  expired?: Prisma.BoolWithAggregatesFilter<"Homework"> | boolean
  deleted?: Prisma.BoolWithAggregatesFilter<"Homework"> | boolean
  created_at?: Prisma.DateTimeWithAggregatesFilter<"Homework"> | Date | string
}

export type HomeworkCreateInput = {
  id?: number
  name: string
  deadline?: Date | string | null
  expired?: boolean
  deleted?: boolean
  created_at?: Date | string
  studyGroup: Prisma.StudyGroupCreateNestedOneWithoutHomeworkInput
  userHomeworks?: Prisma.UserHomeworkCreateNestedManyWithoutHomeworkInput
}

export type HomeworkUncheckedCreateInput = {
  id?: number
  name: string
  deadline?: Date | string | null
  studyGroupId: number
  expired?: boolean
  deleted?: boolean
  created_at?: Date | string
  userHomeworks?: Prisma.UserHomeworkUncheckedCreateNestedManyWithoutHomeworkInput
}

export type HomeworkUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  deadline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  expired?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  studyGroup?: Prisma.StudyGroupUpdateOneRequiredWithoutHomeworkNestedInput
  userHomeworks?: Prisma.UserHomeworkUpdateManyWithoutHomeworkNestedInput
}

export type HomeworkUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  deadline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  studyGroupId?: Prisma.IntFieldUpdateOperationsInput | number
  expired?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userHomeworks?: Prisma.UserHomeworkUncheckedUpdateManyWithoutHomeworkNestedInput
}

export type HomeworkCreateManyInput = {
  id?: number
  name: string
  deadline?: Date | string | null
  studyGroupId: number
  expired?: boolean
  deleted?: boolean
  created_at?: Date | string
}

export type HomeworkUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  deadline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  expired?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type HomeworkUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  deadline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  studyGroupId?: Prisma.IntFieldUpdateOperationsInput | number
  expired?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type HomeworkCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  deadline?: Prisma.SortOrder
  studyGroupId?: Prisma.SortOrder
  expired?: Prisma.SortOrder
  deleted?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type HomeworkAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  studyGroupId?: Prisma.SortOrder
}

export type HomeworkMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  deadline?: Prisma.SortOrder
  studyGroupId?: Prisma.SortOrder
  expired?: Prisma.SortOrder
  deleted?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type HomeworkMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  deadline?: Prisma.SortOrder
  studyGroupId?: Prisma.SortOrder
  expired?: Prisma.SortOrder
  deleted?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type HomeworkSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  studyGroupId?: Prisma.SortOrder
}

export type HomeworkScalarRelationFilter = {
  is?: Prisma.HomeworkWhereInput
  isNot?: Prisma.HomeworkWhereInput
}

export type HomeworkListRelationFilter = {
  every?: Prisma.HomeworkWhereInput
  some?: Prisma.HomeworkWhereInput
  none?: Prisma.HomeworkWhereInput
}

export type HomeworkOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type HomeworkCreateNestedOneWithoutUserHomeworksInput = {
  create?: Prisma.XOR<Prisma.HomeworkCreateWithoutUserHomeworksInput, Prisma.HomeworkUncheckedCreateWithoutUserHomeworksInput>
  connectOrCreate?: Prisma.HomeworkCreateOrConnectWithoutUserHomeworksInput
  connect?: Prisma.HomeworkWhereUniqueInput
}

export type HomeworkUpdateOneRequiredWithoutUserHomeworksNestedInput = {
  create?: Prisma.XOR<Prisma.HomeworkCreateWithoutUserHomeworksInput, Prisma.HomeworkUncheckedCreateWithoutUserHomeworksInput>
  connectOrCreate?: Prisma.HomeworkCreateOrConnectWithoutUserHomeworksInput
  upsert?: Prisma.HomeworkUpsertWithoutUserHomeworksInput
  connect?: Prisma.HomeworkWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.HomeworkUpdateToOneWithWhereWithoutUserHomeworksInput, Prisma.HomeworkUpdateWithoutUserHomeworksInput>, Prisma.HomeworkUncheckedUpdateWithoutUserHomeworksInput>
}

export type HomeworkCreateNestedManyWithoutStudyGroupInput = {
  create?: Prisma.XOR<Prisma.HomeworkCreateWithoutStudyGroupInput, Prisma.HomeworkUncheckedCreateWithoutStudyGroupInput> | Prisma.HomeworkCreateWithoutStudyGroupInput[] | Prisma.HomeworkUncheckedCreateWithoutStudyGroupInput[]
  connectOrCreate?: Prisma.HomeworkCreateOrConnectWithoutStudyGroupInput | Prisma.HomeworkCreateOrConnectWithoutStudyGroupInput[]
  createMany?: Prisma.HomeworkCreateManyStudyGroupInputEnvelope
  connect?: Prisma.HomeworkWhereUniqueInput | Prisma.HomeworkWhereUniqueInput[]
}

export type HomeworkUncheckedCreateNestedManyWithoutStudyGroupInput = {
  create?: Prisma.XOR<Prisma.HomeworkCreateWithoutStudyGroupInput, Prisma.HomeworkUncheckedCreateWithoutStudyGroupInput> | Prisma.HomeworkCreateWithoutStudyGroupInput[] | Prisma.HomeworkUncheckedCreateWithoutStudyGroupInput[]
  connectOrCreate?: Prisma.HomeworkCreateOrConnectWithoutStudyGroupInput | Prisma.HomeworkCreateOrConnectWithoutStudyGroupInput[]
  createMany?: Prisma.HomeworkCreateManyStudyGroupInputEnvelope
  connect?: Prisma.HomeworkWhereUniqueInput | Prisma.HomeworkWhereUniqueInput[]
}

export type HomeworkUpdateManyWithoutStudyGroupNestedInput = {
  create?: Prisma.XOR<Prisma.HomeworkCreateWithoutStudyGroupInput, Prisma.HomeworkUncheckedCreateWithoutStudyGroupInput> | Prisma.HomeworkCreateWithoutStudyGroupInput[] | Prisma.HomeworkUncheckedCreateWithoutStudyGroupInput[]
  connectOrCreate?: Prisma.HomeworkCreateOrConnectWithoutStudyGroupInput | Prisma.HomeworkCreateOrConnectWithoutStudyGroupInput[]
  upsert?: Prisma.HomeworkUpsertWithWhereUniqueWithoutStudyGroupInput | Prisma.HomeworkUpsertWithWhereUniqueWithoutStudyGroupInput[]
  createMany?: Prisma.HomeworkCreateManyStudyGroupInputEnvelope
  set?: Prisma.HomeworkWhereUniqueInput | Prisma.HomeworkWhereUniqueInput[]
  disconnect?: Prisma.HomeworkWhereUniqueInput | Prisma.HomeworkWhereUniqueInput[]
  delete?: Prisma.HomeworkWhereUniqueInput | Prisma.HomeworkWhereUniqueInput[]
  connect?: Prisma.HomeworkWhereUniqueInput | Prisma.HomeworkWhereUniqueInput[]
  update?: Prisma.HomeworkUpdateWithWhereUniqueWithoutStudyGroupInput | Prisma.HomeworkUpdateWithWhereUniqueWithoutStudyGroupInput[]
  updateMany?: Prisma.HomeworkUpdateManyWithWhereWithoutStudyGroupInput | Prisma.HomeworkUpdateManyWithWhereWithoutStudyGroupInput[]
  deleteMany?: Prisma.HomeworkScalarWhereInput | Prisma.HomeworkScalarWhereInput[]
}

export type HomeworkUncheckedUpdateManyWithoutStudyGroupNestedInput = {
  create?: Prisma.XOR<Prisma.HomeworkCreateWithoutStudyGroupInput, Prisma.HomeworkUncheckedCreateWithoutStudyGroupInput> | Prisma.HomeworkCreateWithoutStudyGroupInput[] | Prisma.HomeworkUncheckedCreateWithoutStudyGroupInput[]
  connectOrCreate?: Prisma.HomeworkCreateOrConnectWithoutStudyGroupInput | Prisma.HomeworkCreateOrConnectWithoutStudyGroupInput[]
  upsert?: Prisma.HomeworkUpsertWithWhereUniqueWithoutStudyGroupInput | Prisma.HomeworkUpsertWithWhereUniqueWithoutStudyGroupInput[]
  createMany?: Prisma.HomeworkCreateManyStudyGroupInputEnvelope
  set?: Prisma.HomeworkWhereUniqueInput | Prisma.HomeworkWhereUniqueInput[]
  disconnect?: Prisma.HomeworkWhereUniqueInput | Prisma.HomeworkWhereUniqueInput[]
  delete?: Prisma.HomeworkWhereUniqueInput | Prisma.HomeworkWhereUniqueInput[]
  connect?: Prisma.HomeworkWhereUniqueInput | Prisma.HomeworkWhereUniqueInput[]
  update?: Prisma.HomeworkUpdateWithWhereUniqueWithoutStudyGroupInput | Prisma.HomeworkUpdateWithWhereUniqueWithoutStudyGroupInput[]
  updateMany?: Prisma.HomeworkUpdateManyWithWhereWithoutStudyGroupInput | Prisma.HomeworkUpdateManyWithWhereWithoutStudyGroupInput[]
  deleteMany?: Prisma.HomeworkScalarWhereInput | Prisma.HomeworkScalarWhereInput[]
}

export type HomeworkCreateWithoutUserHomeworksInput = {
  id?: number
  name: string
  deadline?: Date | string | null
  expired?: boolean
  deleted?: boolean
  created_at?: Date | string
  studyGroup: Prisma.StudyGroupCreateNestedOneWithoutHomeworkInput
}

export type HomeworkUncheckedCreateWithoutUserHomeworksInput = {
  id?: number
  name: string
  deadline?: Date | string | null
  studyGroupId: number
  expired?: boolean
  deleted?: boolean
  created_at?: Date | string
}

export type HomeworkCreateOrConnectWithoutUserHomeworksInput = {
  where: Prisma.HomeworkWhereUniqueInput
  create: Prisma.XOR<Prisma.HomeworkCreateWithoutUserHomeworksInput, Prisma.HomeworkUncheckedCreateWithoutUserHomeworksInput>
}

export type HomeworkUpsertWithoutUserHomeworksInput = {
  update: Prisma.XOR<Prisma.HomeworkUpdateWithoutUserHomeworksInput, Prisma.HomeworkUncheckedUpdateWithoutUserHomeworksInput>
  create: Prisma.XOR<Prisma.HomeworkCreateWithoutUserHomeworksInput, Prisma.HomeworkUncheckedCreateWithoutUserHomeworksInput>
  where?: Prisma.HomeworkWhereInput
}

export type HomeworkUpdateToOneWithWhereWithoutUserHomeworksInput = {
  where?: Prisma.HomeworkWhereInput
  data: Prisma.XOR<Prisma.HomeworkUpdateWithoutUserHomeworksInput, Prisma.HomeworkUncheckedUpdateWithoutUserHomeworksInput>
}

export type HomeworkUpdateWithoutUserHomeworksInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  deadline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  expired?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  studyGroup?: Prisma.StudyGroupUpdateOneRequiredWithoutHomeworkNestedInput
}

export type HomeworkUncheckedUpdateWithoutUserHomeworksInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  deadline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  studyGroupId?: Prisma.IntFieldUpdateOperationsInput | number
  expired?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type HomeworkCreateWithoutStudyGroupInput = {
  id?: number
  name: string
  deadline?: Date | string | null
  expired?: boolean
  deleted?: boolean
  created_at?: Date | string
  userHomeworks?: Prisma.UserHomeworkCreateNestedManyWithoutHomeworkInput
}

export type HomeworkUncheckedCreateWithoutStudyGroupInput = {
  id?: number
  name: string
  deadline?: Date | string | null
  expired?: boolean
  deleted?: boolean
  created_at?: Date | string
  userHomeworks?: Prisma.UserHomeworkUncheckedCreateNestedManyWithoutHomeworkInput
}

export type HomeworkCreateOrConnectWithoutStudyGroupInput = {
  where: Prisma.HomeworkWhereUniqueInput
  create: Prisma.XOR<Prisma.HomeworkCreateWithoutStudyGroupInput, Prisma.HomeworkUncheckedCreateWithoutStudyGroupInput>
}

export type HomeworkCreateManyStudyGroupInputEnvelope = {
  data: Prisma.HomeworkCreateManyStudyGroupInput | Prisma.HomeworkCreateManyStudyGroupInput[]
  skipDuplicates?: boolean
}

export type HomeworkUpsertWithWhereUniqueWithoutStudyGroupInput = {
  where: Prisma.HomeworkWhereUniqueInput
  update: Prisma.XOR<Prisma.HomeworkUpdateWithoutStudyGroupInput, Prisma.HomeworkUncheckedUpdateWithoutStudyGroupInput>
  create: Prisma.XOR<Prisma.HomeworkCreateWithoutStudyGroupInput, Prisma.HomeworkUncheckedCreateWithoutStudyGroupInput>
}

export type HomeworkUpdateWithWhereUniqueWithoutStudyGroupInput = {
  where: Prisma.HomeworkWhereUniqueInput
  data: Prisma.XOR<Prisma.HomeworkUpdateWithoutStudyGroupInput, Prisma.HomeworkUncheckedUpdateWithoutStudyGroupInput>
}

export type HomeworkUpdateManyWithWhereWithoutStudyGroupInput = {
  where: Prisma.HomeworkScalarWhereInput
  data: Prisma.XOR<Prisma.HomeworkUpdateManyMutationInput, Prisma.HomeworkUncheckedUpdateManyWithoutStudyGroupInput>
}

export type HomeworkScalarWhereInput = {
  AND?: Prisma.HomeworkScalarWhereInput | Prisma.HomeworkScalarWhereInput[]
  OR?: Prisma.HomeworkScalarWhereInput[]
  NOT?: Prisma.HomeworkScalarWhereInput | Prisma.HomeworkScalarWhereInput[]
  id?: Prisma.IntFilter<"Homework"> | number
  name?: Prisma.StringFilter<"Homework"> | string
  deadline?: Prisma.DateTimeNullableFilter<"Homework"> | Date | string | null
  studyGroupId?: Prisma.IntFilter<"Homework"> | number
  expired?: Prisma.BoolFilter<"Homework"> | boolean
  deleted?: Prisma.BoolFilter<"Homework"> | boolean
  created_at?: Prisma.DateTimeFilter<"Homework"> | Date | string
}

export type HomeworkCreateManyStudyGroupInput = {
  id?: number
  name: string
  deadline?: Date | string | null
  expired?: boolean
  deleted?: boolean
  created_at?: Date | string
}

export type HomeworkUpdateWithoutStudyGroupInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  deadline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  expired?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userHomeworks?: Prisma.UserHomeworkUpdateManyWithoutHomeworkNestedInput
}

export type HomeworkUncheckedUpdateWithoutStudyGroupInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  deadline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  expired?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userHomeworks?: Prisma.UserHomeworkUncheckedUpdateManyWithoutHomeworkNestedInput
}

export type HomeworkUncheckedUpdateManyWithoutStudyGroupInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  deadline?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  expired?: Prisma.BoolFieldUpdateOperationsInput | boolean
  deleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type HomeworkCountOutputType
 */

export type HomeworkCountOutputType = {
  userHomeworks: number
}

export type HomeworkCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  userHomeworks?: boolean | HomeworkCountOutputTypeCountUserHomeworksArgs
}

/**
 * HomeworkCountOutputType without action
 */
export type HomeworkCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HomeworkCountOutputType
   */
  select?: Prisma.HomeworkCountOutputTypeSelect<ExtArgs> | null
}

/**
 * HomeworkCountOutputType without action
 */
export type HomeworkCountOutputTypeCountUserHomeworksArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserHomeworkWhereInput
}


export type HomeworkSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  deadline?: boolean
  studyGroupId?: boolean
  expired?: boolean
  deleted?: boolean
  created_at?: boolean
  studyGroup?: boolean | Prisma.StudyGroupDefaultArgs<ExtArgs>
  userHomeworks?: boolean | Prisma.Homework$userHomeworksArgs<ExtArgs>
  _count?: boolean | Prisma.HomeworkCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["homework"]>

export type HomeworkSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  deadline?: boolean
  studyGroupId?: boolean
  expired?: boolean
  deleted?: boolean
  created_at?: boolean
  studyGroup?: boolean | Prisma.StudyGroupDefaultArgs<ExtArgs>
}, ExtArgs["result"]["homework"]>

export type HomeworkSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  deadline?: boolean
  studyGroupId?: boolean
  expired?: boolean
  deleted?: boolean
  created_at?: boolean
  studyGroup?: boolean | Prisma.StudyGroupDefaultArgs<ExtArgs>
}, ExtArgs["result"]["homework"]>

export type HomeworkSelectScalar = {
  id?: boolean
  name?: boolean
  deadline?: boolean
  studyGroupId?: boolean
  expired?: boolean
  deleted?: boolean
  created_at?: boolean
}

export type HomeworkOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "deadline" | "studyGroupId" | "expired" | "deleted" | "created_at", ExtArgs["result"]["homework"]>
export type HomeworkInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  studyGroup?: boolean | Prisma.StudyGroupDefaultArgs<ExtArgs>
  userHomeworks?: boolean | Prisma.Homework$userHomeworksArgs<ExtArgs>
  _count?: boolean | Prisma.HomeworkCountOutputTypeDefaultArgs<ExtArgs>
}
export type HomeworkIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  studyGroup?: boolean | Prisma.StudyGroupDefaultArgs<ExtArgs>
}
export type HomeworkIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  studyGroup?: boolean | Prisma.StudyGroupDefaultArgs<ExtArgs>
}

export type $HomeworkPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Homework"
  objects: {
    studyGroup: Prisma.$StudyGroupPayload<ExtArgs>
    userHomeworks: Prisma.$UserHomeworkPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    name: string
    deadline: Date | null
    studyGroupId: number
    expired: boolean
    deleted: boolean
    created_at: Date
  }, ExtArgs["result"]["homework"]>
  composites: {}
}

export type HomeworkGetPayload<S extends boolean | null | undefined | HomeworkDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$HomeworkPayload, S>

export type HomeworkCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<HomeworkFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: HomeworkCountAggregateInputType | true
  }

export interface HomeworkDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Homework'], meta: { name: 'Homework' } }
  /**
   * Find zero or one Homework that matches the filter.
   * @param {HomeworkFindUniqueArgs} args - Arguments to find a Homework
   * @example
   * // Get one Homework
   * const homework = await prisma.homework.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends HomeworkFindUniqueArgs>(args: Prisma.SelectSubset<T, HomeworkFindUniqueArgs<ExtArgs>>): Prisma.Prisma__HomeworkClient<runtime.Types.Result.GetResult<Prisma.$HomeworkPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Homework that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {HomeworkFindUniqueOrThrowArgs} args - Arguments to find a Homework
   * @example
   * // Get one Homework
   * const homework = await prisma.homework.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends HomeworkFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, HomeworkFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__HomeworkClient<runtime.Types.Result.GetResult<Prisma.$HomeworkPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Homework that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HomeworkFindFirstArgs} args - Arguments to find a Homework
   * @example
   * // Get one Homework
   * const homework = await prisma.homework.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends HomeworkFindFirstArgs>(args?: Prisma.SelectSubset<T, HomeworkFindFirstArgs<ExtArgs>>): Prisma.Prisma__HomeworkClient<runtime.Types.Result.GetResult<Prisma.$HomeworkPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Homework that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HomeworkFindFirstOrThrowArgs} args - Arguments to find a Homework
   * @example
   * // Get one Homework
   * const homework = await prisma.homework.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends HomeworkFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, HomeworkFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__HomeworkClient<runtime.Types.Result.GetResult<Prisma.$HomeworkPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Homework that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HomeworkFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Homework
   * const homework = await prisma.homework.findMany()
   * 
   * // Get first 10 Homework
   * const homework = await prisma.homework.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const homeworkWithIdOnly = await prisma.homework.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends HomeworkFindManyArgs>(args?: Prisma.SelectSubset<T, HomeworkFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HomeworkPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Homework.
   * @param {HomeworkCreateArgs} args - Arguments to create a Homework.
   * @example
   * // Create one Homework
   * const Homework = await prisma.homework.create({
   *   data: {
   *     // ... data to create a Homework
   *   }
   * })
   * 
   */
  create<T extends HomeworkCreateArgs>(args: Prisma.SelectSubset<T, HomeworkCreateArgs<ExtArgs>>): Prisma.Prisma__HomeworkClient<runtime.Types.Result.GetResult<Prisma.$HomeworkPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Homework.
   * @param {HomeworkCreateManyArgs} args - Arguments to create many Homework.
   * @example
   * // Create many Homework
   * const homework = await prisma.homework.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends HomeworkCreateManyArgs>(args?: Prisma.SelectSubset<T, HomeworkCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Homework and returns the data saved in the database.
   * @param {HomeworkCreateManyAndReturnArgs} args - Arguments to create many Homework.
   * @example
   * // Create many Homework
   * const homework = await prisma.homework.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Homework and only return the `id`
   * const homeworkWithIdOnly = await prisma.homework.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends HomeworkCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, HomeworkCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HomeworkPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Homework.
   * @param {HomeworkDeleteArgs} args - Arguments to delete one Homework.
   * @example
   * // Delete one Homework
   * const Homework = await prisma.homework.delete({
   *   where: {
   *     // ... filter to delete one Homework
   *   }
   * })
   * 
   */
  delete<T extends HomeworkDeleteArgs>(args: Prisma.SelectSubset<T, HomeworkDeleteArgs<ExtArgs>>): Prisma.Prisma__HomeworkClient<runtime.Types.Result.GetResult<Prisma.$HomeworkPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Homework.
   * @param {HomeworkUpdateArgs} args - Arguments to update one Homework.
   * @example
   * // Update one Homework
   * const homework = await prisma.homework.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends HomeworkUpdateArgs>(args: Prisma.SelectSubset<T, HomeworkUpdateArgs<ExtArgs>>): Prisma.Prisma__HomeworkClient<runtime.Types.Result.GetResult<Prisma.$HomeworkPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Homework.
   * @param {HomeworkDeleteManyArgs} args - Arguments to filter Homework to delete.
   * @example
   * // Delete a few Homework
   * const { count } = await prisma.homework.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends HomeworkDeleteManyArgs>(args?: Prisma.SelectSubset<T, HomeworkDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Homework.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HomeworkUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Homework
   * const homework = await prisma.homework.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends HomeworkUpdateManyArgs>(args: Prisma.SelectSubset<T, HomeworkUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Homework and returns the data updated in the database.
   * @param {HomeworkUpdateManyAndReturnArgs} args - Arguments to update many Homework.
   * @example
   * // Update many Homework
   * const homework = await prisma.homework.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Homework and only return the `id`
   * const homeworkWithIdOnly = await prisma.homework.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends HomeworkUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, HomeworkUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HomeworkPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Homework.
   * @param {HomeworkUpsertArgs} args - Arguments to update or create a Homework.
   * @example
   * // Update or create a Homework
   * const homework = await prisma.homework.upsert({
   *   create: {
   *     // ... data to create a Homework
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Homework we want to update
   *   }
   * })
   */
  upsert<T extends HomeworkUpsertArgs>(args: Prisma.SelectSubset<T, HomeworkUpsertArgs<ExtArgs>>): Prisma.Prisma__HomeworkClient<runtime.Types.Result.GetResult<Prisma.$HomeworkPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Homework.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HomeworkCountArgs} args - Arguments to filter Homework to count.
   * @example
   * // Count the number of Homework
   * const count = await prisma.homework.count({
   *   where: {
   *     // ... the filter for the Homework we want to count
   *   }
   * })
  **/
  count<T extends HomeworkCountArgs>(
    args?: Prisma.Subset<T, HomeworkCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], HomeworkCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Homework.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HomeworkAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends HomeworkAggregateArgs>(args: Prisma.Subset<T, HomeworkAggregateArgs>): Prisma.PrismaPromise<GetHomeworkAggregateType<T>>

  /**
   * Group by Homework.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HomeworkGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends HomeworkGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: HomeworkGroupByArgs['orderBy'] }
      : { orderBy?: HomeworkGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, HomeworkGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetHomeworkGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Homework model
 */
readonly fields: HomeworkFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Homework.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__HomeworkClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  studyGroup<T extends Prisma.StudyGroupDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.StudyGroupDefaultArgs<ExtArgs>>): Prisma.Prisma__StudyGroupClient<runtime.Types.Result.GetResult<Prisma.$StudyGroupPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  userHomeworks<T extends Prisma.Homework$userHomeworksArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Homework$userHomeworksArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserHomeworkPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Homework model
 */
export interface HomeworkFieldRefs {
  readonly id: Prisma.FieldRef<"Homework", 'Int'>
  readonly name: Prisma.FieldRef<"Homework", 'String'>
  readonly deadline: Prisma.FieldRef<"Homework", 'DateTime'>
  readonly studyGroupId: Prisma.FieldRef<"Homework", 'Int'>
  readonly expired: Prisma.FieldRef<"Homework", 'Boolean'>
  readonly deleted: Prisma.FieldRef<"Homework", 'Boolean'>
  readonly created_at: Prisma.FieldRef<"Homework", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Homework findUnique
 */
export type HomeworkFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Homework
   */
  select?: Prisma.HomeworkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Homework
   */
  omit?: Prisma.HomeworkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HomeworkInclude<ExtArgs> | null
  /**
   * Filter, which Homework to fetch.
   */
  where: Prisma.HomeworkWhereUniqueInput
}

/**
 * Homework findUniqueOrThrow
 */
export type HomeworkFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Homework
   */
  select?: Prisma.HomeworkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Homework
   */
  omit?: Prisma.HomeworkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HomeworkInclude<ExtArgs> | null
  /**
   * Filter, which Homework to fetch.
   */
  where: Prisma.HomeworkWhereUniqueInput
}

/**
 * Homework findFirst
 */
export type HomeworkFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Homework
   */
  select?: Prisma.HomeworkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Homework
   */
  omit?: Prisma.HomeworkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HomeworkInclude<ExtArgs> | null
  /**
   * Filter, which Homework to fetch.
   */
  where?: Prisma.HomeworkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Homework to fetch.
   */
  orderBy?: Prisma.HomeworkOrderByWithRelationInput | Prisma.HomeworkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Homework.
   */
  cursor?: Prisma.HomeworkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Homework from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Homework.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Homework.
   */
  distinct?: Prisma.HomeworkScalarFieldEnum | Prisma.HomeworkScalarFieldEnum[]
}

/**
 * Homework findFirstOrThrow
 */
export type HomeworkFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Homework
   */
  select?: Prisma.HomeworkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Homework
   */
  omit?: Prisma.HomeworkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HomeworkInclude<ExtArgs> | null
  /**
   * Filter, which Homework to fetch.
   */
  where?: Prisma.HomeworkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Homework to fetch.
   */
  orderBy?: Prisma.HomeworkOrderByWithRelationInput | Prisma.HomeworkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Homework.
   */
  cursor?: Prisma.HomeworkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Homework from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Homework.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Homework.
   */
  distinct?: Prisma.HomeworkScalarFieldEnum | Prisma.HomeworkScalarFieldEnum[]
}

/**
 * Homework findMany
 */
export type HomeworkFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Homework
   */
  select?: Prisma.HomeworkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Homework
   */
  omit?: Prisma.HomeworkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HomeworkInclude<ExtArgs> | null
  /**
   * Filter, which Homework to fetch.
   */
  where?: Prisma.HomeworkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Homework to fetch.
   */
  orderBy?: Prisma.HomeworkOrderByWithRelationInput | Prisma.HomeworkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Homework.
   */
  cursor?: Prisma.HomeworkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Homework from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Homework.
   */
  skip?: number
  distinct?: Prisma.HomeworkScalarFieldEnum | Prisma.HomeworkScalarFieldEnum[]
}

/**
 * Homework create
 */
export type HomeworkCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Homework
   */
  select?: Prisma.HomeworkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Homework
   */
  omit?: Prisma.HomeworkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HomeworkInclude<ExtArgs> | null
  /**
   * The data needed to create a Homework.
   */
  data: Prisma.XOR<Prisma.HomeworkCreateInput, Prisma.HomeworkUncheckedCreateInput>
}

/**
 * Homework createMany
 */
export type HomeworkCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Homework.
   */
  data: Prisma.HomeworkCreateManyInput | Prisma.HomeworkCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Homework createManyAndReturn
 */
export type HomeworkCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Homework
   */
  select?: Prisma.HomeworkSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Homework
   */
  omit?: Prisma.HomeworkOmit<ExtArgs> | null
  /**
   * The data used to create many Homework.
   */
  data: Prisma.HomeworkCreateManyInput | Prisma.HomeworkCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HomeworkIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Homework update
 */
export type HomeworkUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Homework
   */
  select?: Prisma.HomeworkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Homework
   */
  omit?: Prisma.HomeworkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HomeworkInclude<ExtArgs> | null
  /**
   * The data needed to update a Homework.
   */
  data: Prisma.XOR<Prisma.HomeworkUpdateInput, Prisma.HomeworkUncheckedUpdateInput>
  /**
   * Choose, which Homework to update.
   */
  where: Prisma.HomeworkWhereUniqueInput
}

/**
 * Homework updateMany
 */
export type HomeworkUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Homework.
   */
  data: Prisma.XOR<Prisma.HomeworkUpdateManyMutationInput, Prisma.HomeworkUncheckedUpdateManyInput>
  /**
   * Filter which Homework to update
   */
  where?: Prisma.HomeworkWhereInput
  /**
   * Limit how many Homework to update.
   */
  limit?: number
}

/**
 * Homework updateManyAndReturn
 */
export type HomeworkUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Homework
   */
  select?: Prisma.HomeworkSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Homework
   */
  omit?: Prisma.HomeworkOmit<ExtArgs> | null
  /**
   * The data used to update Homework.
   */
  data: Prisma.XOR<Prisma.HomeworkUpdateManyMutationInput, Prisma.HomeworkUncheckedUpdateManyInput>
  /**
   * Filter which Homework to update
   */
  where?: Prisma.HomeworkWhereInput
  /**
   * Limit how many Homework to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HomeworkIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Homework upsert
 */
export type HomeworkUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Homework
   */
  select?: Prisma.HomeworkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Homework
   */
  omit?: Prisma.HomeworkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HomeworkInclude<ExtArgs> | null
  /**
   * The filter to search for the Homework to update in case it exists.
   */
  where: Prisma.HomeworkWhereUniqueInput
  /**
   * In case the Homework found by the `where` argument doesn't exist, create a new Homework with this data.
   */
  create: Prisma.XOR<Prisma.HomeworkCreateInput, Prisma.HomeworkUncheckedCreateInput>
  /**
   * In case the Homework was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.HomeworkUpdateInput, Prisma.HomeworkUncheckedUpdateInput>
}

/**
 * Homework delete
 */
export type HomeworkDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Homework
   */
  select?: Prisma.HomeworkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Homework
   */
  omit?: Prisma.HomeworkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HomeworkInclude<ExtArgs> | null
  /**
   * Filter which Homework to delete.
   */
  where: Prisma.HomeworkWhereUniqueInput
}

/**
 * Homework deleteMany
 */
export type HomeworkDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Homework to delete
   */
  where?: Prisma.HomeworkWhereInput
  /**
   * Limit how many Homework to delete.
   */
  limit?: number
}

/**
 * Homework.userHomeworks
 */
export type Homework$userHomeworksArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserHomework
   */
  select?: Prisma.UserHomeworkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserHomework
   */
  omit?: Prisma.UserHomeworkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserHomeworkInclude<ExtArgs> | null
  where?: Prisma.UserHomeworkWhereInput
  orderBy?: Prisma.UserHomeworkOrderByWithRelationInput | Prisma.UserHomeworkOrderByWithRelationInput[]
  cursor?: Prisma.UserHomeworkWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.UserHomeworkScalarFieldEnum | Prisma.UserHomeworkScalarFieldEnum[]
}

/**
 * Homework without action
 */
export type HomeworkDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Homework
   */
  select?: Prisma.HomeworkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Homework
   */
  omit?: Prisma.HomeworkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HomeworkInclude<ExtArgs> | null
}
