
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `StudyGroupRelation` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model StudyGroupRelation
 * 
 */
export type StudyGroupRelationModel = runtime.Types.Result.DefaultSelection<Prisma.$StudyGroupRelationPayload>

export type AggregateStudyGroupRelation = {
  _count: StudyGroupRelationCountAggregateOutputType | null
  _avg: StudyGroupRelationAvgAggregateOutputType | null
  _sum: StudyGroupRelationSumAggregateOutputType | null
  _min: StudyGroupRelationMinAggregateOutputType | null
  _max: StudyGroupRelationMaxAggregateOutputType | null
}

export type StudyGroupRelationAvgAggregateOutputType = {
  id: number | null
  userId: number | null
  groupId: number | null
}

export type StudyGroupRelationSumAggregateOutputType = {
  id: number | null
  userId: bigint | null
  groupId: number | null
}

export type StudyGroupRelationMinAggregateOutputType = {
  id: number | null
  userId: bigint | null
  groupId: number | null
}

export type StudyGroupRelationMaxAggregateOutputType = {
  id: number | null
  userId: bigint | null
  groupId: number | null
}

export type StudyGroupRelationCountAggregateOutputType = {
  id: number
  userId: number
  groupId: number
  _all: number
}


export type StudyGroupRelationAvgAggregateInputType = {
  id?: true
  userId?: true
  groupId?: true
}

export type StudyGroupRelationSumAggregateInputType = {
  id?: true
  userId?: true
  groupId?: true
}

export type StudyGroupRelationMinAggregateInputType = {
  id?: true
  userId?: true
  groupId?: true
}

export type StudyGroupRelationMaxAggregateInputType = {
  id?: true
  userId?: true
  groupId?: true
}

export type StudyGroupRelationCountAggregateInputType = {
  id?: true
  userId?: true
  groupId?: true
  _all?: true
}

export type StudyGroupRelationAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which StudyGroupRelation to aggregate.
   */
  where?: Prisma.StudyGroupRelationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StudyGroupRelations to fetch.
   */
  orderBy?: Prisma.StudyGroupRelationOrderByWithRelationInput | Prisma.StudyGroupRelationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.StudyGroupRelationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StudyGroupRelations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StudyGroupRelations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned StudyGroupRelations
  **/
  _count?: true | StudyGroupRelationCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: StudyGroupRelationAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: StudyGroupRelationSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: StudyGroupRelationMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: StudyGroupRelationMaxAggregateInputType
}

export type GetStudyGroupRelationAggregateType<T extends StudyGroupRelationAggregateArgs> = {
      [P in keyof T & keyof AggregateStudyGroupRelation]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateStudyGroupRelation[P]>
    : Prisma.GetScalarType<T[P], AggregateStudyGroupRelation[P]>
}




export type StudyGroupRelationGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.StudyGroupRelationWhereInput
  orderBy?: Prisma.StudyGroupRelationOrderByWithAggregationInput | Prisma.StudyGroupRelationOrderByWithAggregationInput[]
  by: Prisma.StudyGroupRelationScalarFieldEnum[] | Prisma.StudyGroupRelationScalarFieldEnum
  having?: Prisma.StudyGroupRelationScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: StudyGroupRelationCountAggregateInputType | true
  _avg?: StudyGroupRelationAvgAggregateInputType
  _sum?: StudyGroupRelationSumAggregateInputType
  _min?: StudyGroupRelationMinAggregateInputType
  _max?: StudyGroupRelationMaxAggregateInputType
}

export type StudyGroupRelationGroupByOutputType = {
  id: number
  userId: bigint
  groupId: number
  _count: StudyGroupRelationCountAggregateOutputType | null
  _avg: StudyGroupRelationAvgAggregateOutputType | null
  _sum: StudyGroupRelationSumAggregateOutputType | null
  _min: StudyGroupRelationMinAggregateOutputType | null
  _max: StudyGroupRelationMaxAggregateOutputType | null
}

type GetStudyGroupRelationGroupByPayload<T extends StudyGroupRelationGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<StudyGroupRelationGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof StudyGroupRelationGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], StudyGroupRelationGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], StudyGroupRelationGroupByOutputType[P]>
      }
    >
  >



export type StudyGroupRelationWhereInput = {
  AND?: Prisma.StudyGroupRelationWhereInput | Prisma.StudyGroupRelationWhereInput[]
  OR?: Prisma.StudyGroupRelationWhereInput[]
  NOT?: Prisma.StudyGroupRelationWhereInput | Prisma.StudyGroupRelationWhereInput[]
  id?: Prisma.IntFilter<"StudyGroupRelation"> | number
  userId?: Prisma.BigIntFilter<"StudyGroupRelation"> | bigint | number
  groupId?: Prisma.IntFilter<"StudyGroupRelation"> | number
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  group?: Prisma.XOR<Prisma.StudyGroupScalarRelationFilter, Prisma.StudyGroupWhereInput>
}

export type StudyGroupRelationOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  groupId?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  group?: Prisma.StudyGroupOrderByWithRelationInput
}

export type StudyGroupRelationWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.StudyGroupRelationWhereInput | Prisma.StudyGroupRelationWhereInput[]
  OR?: Prisma.StudyGroupRelationWhereInput[]
  NOT?: Prisma.StudyGroupRelationWhereInput | Prisma.StudyGroupRelationWhereInput[]
  userId?: Prisma.BigIntFilter<"StudyGroupRelation"> | bigint | number
  groupId?: Prisma.IntFilter<"StudyGroupRelation"> | number
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  group?: Prisma.XOR<Prisma.StudyGroupScalarRelationFilter, Prisma.StudyGroupWhereInput>
}, "id">

export type StudyGroupRelationOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  groupId?: Prisma.SortOrder
  _count?: Prisma.StudyGroupRelationCountOrderByAggregateInput
  _avg?: Prisma.StudyGroupRelationAvgOrderByAggregateInput
  _max?: Prisma.StudyGroupRelationMaxOrderByAggregateInput
  _min?: Prisma.StudyGroupRelationMinOrderByAggregateInput
  _sum?: Prisma.StudyGroupRelationSumOrderByAggregateInput
}

export type StudyGroupRelationScalarWhereWithAggregatesInput = {
  AND?: Prisma.StudyGroupRelationScalarWhereWithAggregatesInput | Prisma.StudyGroupRelationScalarWhereWithAggregatesInput[]
  OR?: Prisma.StudyGroupRelationScalarWhereWithAggregatesInput[]
  NOT?: Prisma.StudyGroupRelationScalarWhereWithAggregatesInput | Prisma.StudyGroupRelationScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"StudyGroupRelation"> | number
  userId?: Prisma.BigIntWithAggregatesFilter<"StudyGroupRelation"> | bigint | number
  groupId?: Prisma.IntWithAggregatesFilter<"StudyGroupRelation"> | number
}

export type StudyGroupRelationCreateInput = {
  id?: number
  user: Prisma.UserCreateNestedOneWithoutStudyGroupRelationsInput
  group: Prisma.StudyGroupCreateNestedOneWithoutStudyGroupRelationsInput
}

export type StudyGroupRelationUncheckedCreateInput = {
  id?: number
  userId: bigint | number
  groupId: number
}

export type StudyGroupRelationUpdateInput = {
  user?: Prisma.UserUpdateOneRequiredWithoutStudyGroupRelationsNestedInput
  group?: Prisma.StudyGroupUpdateOneRequiredWithoutStudyGroupRelationsNestedInput
}

export type StudyGroupRelationUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  groupId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type StudyGroupRelationCreateManyInput = {
  id?: number
  userId: bigint | number
  groupId: number
}

export type StudyGroupRelationUpdateManyMutationInput = {

}

export type StudyGroupRelationUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  groupId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type StudyGroupRelationListRelationFilter = {
  every?: Prisma.StudyGroupRelationWhereInput
  some?: Prisma.StudyGroupRelationWhereInput
  none?: Prisma.StudyGroupRelationWhereInput
}

export type StudyGroupRelationOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type StudyGroupRelationCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  groupId?: Prisma.SortOrder
}

export type StudyGroupRelationAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  groupId?: Prisma.SortOrder
}

export type StudyGroupRelationMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  groupId?: Prisma.SortOrder
}

export type StudyGroupRelationMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  groupId?: Prisma.SortOrder
}

export type StudyGroupRelationSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  groupId?: Prisma.SortOrder
}

export type StudyGroupRelationCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.StudyGroupRelationCreateWithoutUserInput, Prisma.StudyGroupRelationUncheckedCreateWithoutUserInput> | Prisma.StudyGroupRelationCreateWithoutUserInput[] | Prisma.StudyGroupRelationUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.StudyGroupRelationCreateOrConnectWithoutUserInput | Prisma.StudyGroupRelationCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.StudyGroupRelationCreateManyUserInputEnvelope
  connect?: Prisma.StudyGroupRelationWhereUniqueInput | Prisma.StudyGroupRelationWhereUniqueInput[]
}

export type StudyGroupRelationUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.StudyGroupRelationCreateWithoutUserInput, Prisma.StudyGroupRelationUncheckedCreateWithoutUserInput> | Prisma.StudyGroupRelationCreateWithoutUserInput[] | Prisma.StudyGroupRelationUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.StudyGroupRelationCreateOrConnectWithoutUserInput | Prisma.StudyGroupRelationCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.StudyGroupRelationCreateManyUserInputEnvelope
  connect?: Prisma.StudyGroupRelationWhereUniqueInput | Prisma.StudyGroupRelationWhereUniqueInput[]
}

export type StudyGroupRelationUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.StudyGroupRelationCreateWithoutUserInput, Prisma.StudyGroupRelationUncheckedCreateWithoutUserInput> | Prisma.StudyGroupRelationCreateWithoutUserInput[] | Prisma.StudyGroupRelationUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.StudyGroupRelationCreateOrConnectWithoutUserInput | Prisma.StudyGroupRelationCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.StudyGroupRelationUpsertWithWhereUniqueWithoutUserInput | Prisma.StudyGroupRelationUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.StudyGroupRelationCreateManyUserInputEnvelope
  set?: Prisma.StudyGroupRelationWhereUniqueInput | Prisma.StudyGroupRelationWhereUniqueInput[]
  disconnect?: Prisma.StudyGroupRelationWhereUniqueInput | Prisma.StudyGroupRelationWhereUniqueInput[]
  delete?: Prisma.StudyGroupRelationWhereUniqueInput | Prisma.StudyGroupRelationWhereUniqueInput[]
  connect?: Prisma.StudyGroupRelationWhereUniqueInput | Prisma.StudyGroupRelationWhereUniqueInput[]
  update?: Prisma.StudyGroupRelationUpdateWithWhereUniqueWithoutUserInput | Prisma.StudyGroupRelationUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.StudyGroupRelationUpdateManyWithWhereWithoutUserInput | Prisma.StudyGroupRelationUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.StudyGroupRelationScalarWhereInput | Prisma.StudyGroupRelationScalarWhereInput[]
}

export type StudyGroupRelationUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.StudyGroupRelationCreateWithoutUserInput, Prisma.StudyGroupRelationUncheckedCreateWithoutUserInput> | Prisma.StudyGroupRelationCreateWithoutUserInput[] | Prisma.StudyGroupRelationUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.StudyGroupRelationCreateOrConnectWithoutUserInput | Prisma.StudyGroupRelationCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.StudyGroupRelationUpsertWithWhereUniqueWithoutUserInput | Prisma.StudyGroupRelationUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.StudyGroupRelationCreateManyUserInputEnvelope
  set?: Prisma.StudyGroupRelationWhereUniqueInput | Prisma.StudyGroupRelationWhereUniqueInput[]
  disconnect?: Prisma.StudyGroupRelationWhereUniqueInput | Prisma.StudyGroupRelationWhereUniqueInput[]
  delete?: Prisma.StudyGroupRelationWhereUniqueInput | Prisma.StudyGroupRelationWhereUniqueInput[]
  connect?: Prisma.StudyGroupRelationWhereUniqueInput | Prisma.StudyGroupRelationWhereUniqueInput[]
  update?: Prisma.StudyGroupRelationUpdateWithWhereUniqueWithoutUserInput | Prisma.StudyGroupRelationUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.StudyGroupRelationUpdateManyWithWhereWithoutUserInput | Prisma.StudyGroupRelationUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.StudyGroupRelationScalarWhereInput | Prisma.StudyGroupRelationScalarWhereInput[]
}

export type StudyGroupRelationCreateNestedManyWithoutGroupInput = {
  create?: Prisma.XOR<Prisma.StudyGroupRelationCreateWithoutGroupInput, Prisma.StudyGroupRelationUncheckedCreateWithoutGroupInput> | Prisma.StudyGroupRelationCreateWithoutGroupInput[] | Prisma.StudyGroupRelationUncheckedCreateWithoutGroupInput[]
  connectOrCreate?: Prisma.StudyGroupRelationCreateOrConnectWithoutGroupInput | Prisma.StudyGroupRelationCreateOrConnectWithoutGroupInput[]
  createMany?: Prisma.StudyGroupRelationCreateManyGroupInputEnvelope
  connect?: Prisma.StudyGroupRelationWhereUniqueInput | Prisma.StudyGroupRelationWhereUniqueInput[]
}

export type StudyGroupRelationUncheckedCreateNestedManyWithoutGroupInput = {
  create?: Prisma.XOR<Prisma.StudyGroupRelationCreateWithoutGroupInput, Prisma.StudyGroupRelationUncheckedCreateWithoutGroupInput> | Prisma.StudyGroupRelationCreateWithoutGroupInput[] | Prisma.StudyGroupRelationUncheckedCreateWithoutGroupInput[]
  connectOrCreate?: Prisma.StudyGroupRelationCreateOrConnectWithoutGroupInput | Prisma.StudyGroupRelationCreateOrConnectWithoutGroupInput[]
  createMany?: Prisma.StudyGroupRelationCreateManyGroupInputEnvelope
  connect?: Prisma.StudyGroupRelationWhereUniqueInput | Prisma.StudyGroupRelationWhereUniqueInput[]
}

export type StudyGroupRelationUpdateManyWithoutGroupNestedInput = {
  create?: Prisma.XOR<Prisma.StudyGroupRelationCreateWithoutGroupInput, Prisma.StudyGroupRelationUncheckedCreateWithoutGroupInput> | Prisma.StudyGroupRelationCreateWithoutGroupInput[] | Prisma.StudyGroupRelationUncheckedCreateWithoutGroupInput[]
  connectOrCreate?: Prisma.StudyGroupRelationCreateOrConnectWithoutGroupInput | Prisma.StudyGroupRelationCreateOrConnectWithoutGroupInput[]
  upsert?: Prisma.StudyGroupRelationUpsertWithWhereUniqueWithoutGroupInput | Prisma.StudyGroupRelationUpsertWithWhereUniqueWithoutGroupInput[]
  createMany?: Prisma.StudyGroupRelationCreateManyGroupInputEnvelope
  set?: Prisma.StudyGroupRelationWhereUniqueInput | Prisma.StudyGroupRelationWhereUniqueInput[]
  disconnect?: Prisma.StudyGroupRelationWhereUniqueInput | Prisma.StudyGroupRelationWhereUniqueInput[]
  delete?: Prisma.StudyGroupRelationWhereUniqueInput | Prisma.StudyGroupRelationWhereUniqueInput[]
  connect?: Prisma.StudyGroupRelationWhereUniqueInput | Prisma.StudyGroupRelationWhereUniqueInput[]
  update?: Prisma.StudyGroupRelationUpdateWithWhereUniqueWithoutGroupInput | Prisma.StudyGroupRelationUpdateWithWhereUniqueWithoutGroupInput[]
  updateMany?: Prisma.StudyGroupRelationUpdateManyWithWhereWithoutGroupInput | Prisma.StudyGroupRelationUpdateManyWithWhereWithoutGroupInput[]
  deleteMany?: Prisma.StudyGroupRelationScalarWhereInput | Prisma.StudyGroupRelationScalarWhereInput[]
}

export type StudyGroupRelationUncheckedUpdateManyWithoutGroupNestedInput = {
  create?: Prisma.XOR<Prisma.StudyGroupRelationCreateWithoutGroupInput, Prisma.StudyGroupRelationUncheckedCreateWithoutGroupInput> | Prisma.StudyGroupRelationCreateWithoutGroupInput[] | Prisma.StudyGroupRelationUncheckedCreateWithoutGroupInput[]
  connectOrCreate?: Prisma.StudyGroupRelationCreateOrConnectWithoutGroupInput | Prisma.StudyGroupRelationCreateOrConnectWithoutGroupInput[]
  upsert?: Prisma.StudyGroupRelationUpsertWithWhereUniqueWithoutGroupInput | Prisma.StudyGroupRelationUpsertWithWhereUniqueWithoutGroupInput[]
  createMany?: Prisma.StudyGroupRelationCreateManyGroupInputEnvelope
  set?: Prisma.StudyGroupRelationWhereUniqueInput | Prisma.StudyGroupRelationWhereUniqueInput[]
  disconnect?: Prisma.StudyGroupRelationWhereUniqueInput | Prisma.StudyGroupRelationWhereUniqueInput[]
  delete?: Prisma.StudyGroupRelationWhereUniqueInput | Prisma.StudyGroupRelationWhereUniqueInput[]
  connect?: Prisma.StudyGroupRelationWhereUniqueInput | Prisma.StudyGroupRelationWhereUniqueInput[]
  update?: Prisma.StudyGroupRelationUpdateWithWhereUniqueWithoutGroupInput | Prisma.StudyGroupRelationUpdateWithWhereUniqueWithoutGroupInput[]
  updateMany?: Prisma.StudyGroupRelationUpdateManyWithWhereWithoutGroupInput | Prisma.StudyGroupRelationUpdateManyWithWhereWithoutGroupInput[]
  deleteMany?: Prisma.StudyGroupRelationScalarWhereInput | Prisma.StudyGroupRelationScalarWhereInput[]
}

export type StudyGroupRelationCreateWithoutUserInput = {
  id?: number
  group: Prisma.StudyGroupCreateNestedOneWithoutStudyGroupRelationsInput
}

export type StudyGroupRelationUncheckedCreateWithoutUserInput = {
  id?: number
  groupId: number
}

export type StudyGroupRelationCreateOrConnectWithoutUserInput = {
  where: Prisma.StudyGroupRelationWhereUniqueInput
  create: Prisma.XOR<Prisma.StudyGroupRelationCreateWithoutUserInput, Prisma.StudyGroupRelationUncheckedCreateWithoutUserInput>
}

export type StudyGroupRelationCreateManyUserInputEnvelope = {
  data: Prisma.StudyGroupRelationCreateManyUserInput | Prisma.StudyGroupRelationCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type StudyGroupRelationUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.StudyGroupRelationWhereUniqueInput
  update: Prisma.XOR<Prisma.StudyGroupRelationUpdateWithoutUserInput, Prisma.StudyGroupRelationUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.StudyGroupRelationCreateWithoutUserInput, Prisma.StudyGroupRelationUncheckedCreateWithoutUserInput>
}

export type StudyGroupRelationUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.StudyGroupRelationWhereUniqueInput
  data: Prisma.XOR<Prisma.StudyGroupRelationUpdateWithoutUserInput, Prisma.StudyGroupRelationUncheckedUpdateWithoutUserInput>
}

export type StudyGroupRelationUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.StudyGroupRelationScalarWhereInput
  data: Prisma.XOR<Prisma.StudyGroupRelationUpdateManyMutationInput, Prisma.StudyGroupRelationUncheckedUpdateManyWithoutUserInput>
}

export type StudyGroupRelationScalarWhereInput = {
  AND?: Prisma.StudyGroupRelationScalarWhereInput | Prisma.StudyGroupRelationScalarWhereInput[]
  OR?: Prisma.StudyGroupRelationScalarWhereInput[]
  NOT?: Prisma.StudyGroupRelationScalarWhereInput | Prisma.StudyGroupRelationScalarWhereInput[]
  id?: Prisma.IntFilter<"StudyGroupRelation"> | number
  userId?: Prisma.BigIntFilter<"StudyGroupRelation"> | bigint | number
  groupId?: Prisma.IntFilter<"StudyGroupRelation"> | number
}

export type StudyGroupRelationCreateWithoutGroupInput = {
  id?: number
  user: Prisma.UserCreateNestedOneWithoutStudyGroupRelationsInput
}

export type StudyGroupRelationUncheckedCreateWithoutGroupInput = {
  id?: number
  userId: bigint | number
}

export type StudyGroupRelationCreateOrConnectWithoutGroupInput = {
  where: Prisma.StudyGroupRelationWhereUniqueInput
  create: Prisma.XOR<Prisma.StudyGroupRelationCreateWithoutGroupInput, Prisma.StudyGroupRelationUncheckedCreateWithoutGroupInput>
}

export type StudyGroupRelationCreateManyGroupInputEnvelope = {
  data: Prisma.StudyGroupRelationCreateManyGroupInput | Prisma.StudyGroupRelationCreateManyGroupInput[]
  skipDuplicates?: boolean
}

export type StudyGroupRelationUpsertWithWhereUniqueWithoutGroupInput = {
  where: Prisma.StudyGroupRelationWhereUniqueInput
  update: Prisma.XOR<Prisma.StudyGroupRelationUpdateWithoutGroupInput, Prisma.StudyGroupRelationUncheckedUpdateWithoutGroupInput>
  create: Prisma.XOR<Prisma.StudyGroupRelationCreateWithoutGroupInput, Prisma.StudyGroupRelationUncheckedCreateWithoutGroupInput>
}

export type StudyGroupRelationUpdateWithWhereUniqueWithoutGroupInput = {
  where: Prisma.StudyGroupRelationWhereUniqueInput
  data: Prisma.XOR<Prisma.StudyGroupRelationUpdateWithoutGroupInput, Prisma.StudyGroupRelationUncheckedUpdateWithoutGroupInput>
}

export type StudyGroupRelationUpdateManyWithWhereWithoutGroupInput = {
  where: Prisma.StudyGroupRelationScalarWhereInput
  data: Prisma.XOR<Prisma.StudyGroupRelationUpdateManyMutationInput, Prisma.StudyGroupRelationUncheckedUpdateManyWithoutGroupInput>
}

export type StudyGroupRelationCreateManyUserInput = {
  id?: number
  groupId: number
}

export type StudyGroupRelationUpdateWithoutUserInput = {
  group?: Prisma.StudyGroupUpdateOneRequiredWithoutStudyGroupRelationsNestedInput
}

export type StudyGroupRelationUncheckedUpdateWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  groupId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type StudyGroupRelationUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  groupId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type StudyGroupRelationCreateManyGroupInput = {
  id?: number
  userId: bigint | number
}

export type StudyGroupRelationUpdateWithoutGroupInput = {
  user?: Prisma.UserUpdateOneRequiredWithoutStudyGroupRelationsNestedInput
}

export type StudyGroupRelationUncheckedUpdateWithoutGroupInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}

export type StudyGroupRelationUncheckedUpdateManyWithoutGroupInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}



export type StudyGroupRelationSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  groupId?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  group?: boolean | Prisma.StudyGroupDefaultArgs<ExtArgs>
}, ExtArgs["result"]["studyGroupRelation"]>

export type StudyGroupRelationSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  groupId?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  group?: boolean | Prisma.StudyGroupDefaultArgs<ExtArgs>
}, ExtArgs["result"]["studyGroupRelation"]>

export type StudyGroupRelationSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  groupId?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  group?: boolean | Prisma.StudyGroupDefaultArgs<ExtArgs>
}, ExtArgs["result"]["studyGroupRelation"]>

export type StudyGroupRelationSelectScalar = {
  id?: boolean
  userId?: boolean
  groupId?: boolean
}

export type StudyGroupRelationOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "groupId", ExtArgs["result"]["studyGroupRelation"]>
export type StudyGroupRelationInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  group?: boolean | Prisma.StudyGroupDefaultArgs<ExtArgs>
}
export type StudyGroupRelationIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  group?: boolean | Prisma.StudyGroupDefaultArgs<ExtArgs>
}
export type StudyGroupRelationIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  group?: boolean | Prisma.StudyGroupDefaultArgs<ExtArgs>
}

export type $StudyGroupRelationPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "StudyGroupRelation"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    group: Prisma.$StudyGroupPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    userId: bigint
    groupId: number
  }, ExtArgs["result"]["studyGroupRelation"]>
  composites: {}
}

export type StudyGroupRelationGetPayload<S extends boolean | null | undefined | StudyGroupRelationDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$StudyGroupRelationPayload, S>

export type StudyGroupRelationCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<StudyGroupRelationFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: StudyGroupRelationCountAggregateInputType | true
  }

export interface StudyGroupRelationDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['StudyGroupRelation'], meta: { name: 'StudyGroupRelation' } }
  /**
   * Find zero or one StudyGroupRelation that matches the filter.
   * @param {StudyGroupRelationFindUniqueArgs} args - Arguments to find a StudyGroupRelation
   * @example
   * // Get one StudyGroupRelation
   * const studyGroupRelation = await prisma.studyGroupRelation.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends StudyGroupRelationFindUniqueArgs>(args: Prisma.SelectSubset<T, StudyGroupRelationFindUniqueArgs<ExtArgs>>): Prisma.Prisma__StudyGroupRelationClient<runtime.Types.Result.GetResult<Prisma.$StudyGroupRelationPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one StudyGroupRelation that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {StudyGroupRelationFindUniqueOrThrowArgs} args - Arguments to find a StudyGroupRelation
   * @example
   * // Get one StudyGroupRelation
   * const studyGroupRelation = await prisma.studyGroupRelation.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends StudyGroupRelationFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, StudyGroupRelationFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__StudyGroupRelationClient<runtime.Types.Result.GetResult<Prisma.$StudyGroupRelationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first StudyGroupRelation that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StudyGroupRelationFindFirstArgs} args - Arguments to find a StudyGroupRelation
   * @example
   * // Get one StudyGroupRelation
   * const studyGroupRelation = await prisma.studyGroupRelation.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends StudyGroupRelationFindFirstArgs>(args?: Prisma.SelectSubset<T, StudyGroupRelationFindFirstArgs<ExtArgs>>): Prisma.Prisma__StudyGroupRelationClient<runtime.Types.Result.GetResult<Prisma.$StudyGroupRelationPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first StudyGroupRelation that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StudyGroupRelationFindFirstOrThrowArgs} args - Arguments to find a StudyGroupRelation
   * @example
   * // Get one StudyGroupRelation
   * const studyGroupRelation = await prisma.studyGroupRelation.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends StudyGroupRelationFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, StudyGroupRelationFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__StudyGroupRelationClient<runtime.Types.Result.GetResult<Prisma.$StudyGroupRelationPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more StudyGroupRelations that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StudyGroupRelationFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all StudyGroupRelations
   * const studyGroupRelations = await prisma.studyGroupRelation.findMany()
   * 
   * // Get first 10 StudyGroupRelations
   * const studyGroupRelations = await prisma.studyGroupRelation.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const studyGroupRelationWithIdOnly = await prisma.studyGroupRelation.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends StudyGroupRelationFindManyArgs>(args?: Prisma.SelectSubset<T, StudyGroupRelationFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StudyGroupRelationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a StudyGroupRelation.
   * @param {StudyGroupRelationCreateArgs} args - Arguments to create a StudyGroupRelation.
   * @example
   * // Create one StudyGroupRelation
   * const StudyGroupRelation = await prisma.studyGroupRelation.create({
   *   data: {
   *     // ... data to create a StudyGroupRelation
   *   }
   * })
   * 
   */
  create<T extends StudyGroupRelationCreateArgs>(args: Prisma.SelectSubset<T, StudyGroupRelationCreateArgs<ExtArgs>>): Prisma.Prisma__StudyGroupRelationClient<runtime.Types.Result.GetResult<Prisma.$StudyGroupRelationPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many StudyGroupRelations.
   * @param {StudyGroupRelationCreateManyArgs} args - Arguments to create many StudyGroupRelations.
   * @example
   * // Create many StudyGroupRelations
   * const studyGroupRelation = await prisma.studyGroupRelation.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends StudyGroupRelationCreateManyArgs>(args?: Prisma.SelectSubset<T, StudyGroupRelationCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many StudyGroupRelations and returns the data saved in the database.
   * @param {StudyGroupRelationCreateManyAndReturnArgs} args - Arguments to create many StudyGroupRelations.
   * @example
   * // Create many StudyGroupRelations
   * const studyGroupRelation = await prisma.studyGroupRelation.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many StudyGroupRelations and only return the `id`
   * const studyGroupRelationWithIdOnly = await prisma.studyGroupRelation.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends StudyGroupRelationCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, StudyGroupRelationCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StudyGroupRelationPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a StudyGroupRelation.
   * @param {StudyGroupRelationDeleteArgs} args - Arguments to delete one StudyGroupRelation.
   * @example
   * // Delete one StudyGroupRelation
   * const StudyGroupRelation = await prisma.studyGroupRelation.delete({
   *   where: {
   *     // ... filter to delete one StudyGroupRelation
   *   }
   * })
   * 
   */
  delete<T extends StudyGroupRelationDeleteArgs>(args: Prisma.SelectSubset<T, StudyGroupRelationDeleteArgs<ExtArgs>>): Prisma.Prisma__StudyGroupRelationClient<runtime.Types.Result.GetResult<Prisma.$StudyGroupRelationPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one StudyGroupRelation.
   * @param {StudyGroupRelationUpdateArgs} args - Arguments to update one StudyGroupRelation.
   * @example
   * // Update one StudyGroupRelation
   * const studyGroupRelation = await prisma.studyGroupRelation.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends StudyGroupRelationUpdateArgs>(args: Prisma.SelectSubset<T, StudyGroupRelationUpdateArgs<ExtArgs>>): Prisma.Prisma__StudyGroupRelationClient<runtime.Types.Result.GetResult<Prisma.$StudyGroupRelationPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more StudyGroupRelations.
   * @param {StudyGroupRelationDeleteManyArgs} args - Arguments to filter StudyGroupRelations to delete.
   * @example
   * // Delete a few StudyGroupRelations
   * const { count } = await prisma.studyGroupRelation.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends StudyGroupRelationDeleteManyArgs>(args?: Prisma.SelectSubset<T, StudyGroupRelationDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more StudyGroupRelations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StudyGroupRelationUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many StudyGroupRelations
   * const studyGroupRelation = await prisma.studyGroupRelation.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends StudyGroupRelationUpdateManyArgs>(args: Prisma.SelectSubset<T, StudyGroupRelationUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more StudyGroupRelations and returns the data updated in the database.
   * @param {StudyGroupRelationUpdateManyAndReturnArgs} args - Arguments to update many StudyGroupRelations.
   * @example
   * // Update many StudyGroupRelations
   * const studyGroupRelation = await prisma.studyGroupRelation.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more StudyGroupRelations and only return the `id`
   * const studyGroupRelationWithIdOnly = await prisma.studyGroupRelation.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends StudyGroupRelationUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, StudyGroupRelationUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StudyGroupRelationPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one StudyGroupRelation.
   * @param {StudyGroupRelationUpsertArgs} args - Arguments to update or create a StudyGroupRelation.
   * @example
   * // Update or create a StudyGroupRelation
   * const studyGroupRelation = await prisma.studyGroupRelation.upsert({
   *   create: {
   *     // ... data to create a StudyGroupRelation
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the StudyGroupRelation we want to update
   *   }
   * })
   */
  upsert<T extends StudyGroupRelationUpsertArgs>(args: Prisma.SelectSubset<T, StudyGroupRelationUpsertArgs<ExtArgs>>): Prisma.Prisma__StudyGroupRelationClient<runtime.Types.Result.GetResult<Prisma.$StudyGroupRelationPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of StudyGroupRelations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StudyGroupRelationCountArgs} args - Arguments to filter StudyGroupRelations to count.
   * @example
   * // Count the number of StudyGroupRelations
   * const count = await prisma.studyGroupRelation.count({
   *   where: {
   *     // ... the filter for the StudyGroupRelations we want to count
   *   }
   * })
  **/
  count<T extends StudyGroupRelationCountArgs>(
    args?: Prisma.Subset<T, StudyGroupRelationCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], StudyGroupRelationCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a StudyGroupRelation.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StudyGroupRelationAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends StudyGroupRelationAggregateArgs>(args: Prisma.Subset<T, StudyGroupRelationAggregateArgs>): Prisma.PrismaPromise<GetStudyGroupRelationAggregateType<T>>

  /**
   * Group by StudyGroupRelation.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StudyGroupRelationGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends StudyGroupRelationGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: StudyGroupRelationGroupByArgs['orderBy'] }
      : { orderBy?: StudyGroupRelationGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, StudyGroupRelationGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetStudyGroupRelationGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the StudyGroupRelation model
 */
readonly fields: StudyGroupRelationFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for StudyGroupRelation.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__StudyGroupRelationClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  group<T extends Prisma.StudyGroupDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.StudyGroupDefaultArgs<ExtArgs>>): Prisma.Prisma__StudyGroupClient<runtime.Types.Result.GetResult<Prisma.$StudyGroupPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the StudyGroupRelation model
 */
export interface StudyGroupRelationFieldRefs {
  readonly id: Prisma.FieldRef<"StudyGroupRelation", 'Int'>
  readonly userId: Prisma.FieldRef<"StudyGroupRelation", 'BigInt'>
  readonly groupId: Prisma.FieldRef<"StudyGroupRelation", 'Int'>
}
    

// Custom InputTypes
/**
 * StudyGroupRelation findUnique
 */
export type StudyGroupRelationFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudyGroupRelation
   */
  select?: Prisma.StudyGroupRelationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudyGroupRelation
   */
  omit?: Prisma.StudyGroupRelationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudyGroupRelationInclude<ExtArgs> | null
  /**
   * Filter, which StudyGroupRelation to fetch.
   */
  where: Prisma.StudyGroupRelationWhereUniqueInput
}

/**
 * StudyGroupRelation findUniqueOrThrow
 */
export type StudyGroupRelationFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudyGroupRelation
   */
  select?: Prisma.StudyGroupRelationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudyGroupRelation
   */
  omit?: Prisma.StudyGroupRelationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudyGroupRelationInclude<ExtArgs> | null
  /**
   * Filter, which StudyGroupRelation to fetch.
   */
  where: Prisma.StudyGroupRelationWhereUniqueInput
}

/**
 * StudyGroupRelation findFirst
 */
export type StudyGroupRelationFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudyGroupRelation
   */
  select?: Prisma.StudyGroupRelationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudyGroupRelation
   */
  omit?: Prisma.StudyGroupRelationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudyGroupRelationInclude<ExtArgs> | null
  /**
   * Filter, which StudyGroupRelation to fetch.
   */
  where?: Prisma.StudyGroupRelationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StudyGroupRelations to fetch.
   */
  orderBy?: Prisma.StudyGroupRelationOrderByWithRelationInput | Prisma.StudyGroupRelationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for StudyGroupRelations.
   */
  cursor?: Prisma.StudyGroupRelationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StudyGroupRelations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StudyGroupRelations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of StudyGroupRelations.
   */
  distinct?: Prisma.StudyGroupRelationScalarFieldEnum | Prisma.StudyGroupRelationScalarFieldEnum[]
}

/**
 * StudyGroupRelation findFirstOrThrow
 */
export type StudyGroupRelationFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudyGroupRelation
   */
  select?: Prisma.StudyGroupRelationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudyGroupRelation
   */
  omit?: Prisma.StudyGroupRelationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudyGroupRelationInclude<ExtArgs> | null
  /**
   * Filter, which StudyGroupRelation to fetch.
   */
  where?: Prisma.StudyGroupRelationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StudyGroupRelations to fetch.
   */
  orderBy?: Prisma.StudyGroupRelationOrderByWithRelationInput | Prisma.StudyGroupRelationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for StudyGroupRelations.
   */
  cursor?: Prisma.StudyGroupRelationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StudyGroupRelations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StudyGroupRelations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of StudyGroupRelations.
   */
  distinct?: Prisma.StudyGroupRelationScalarFieldEnum | Prisma.StudyGroupRelationScalarFieldEnum[]
}

/**
 * StudyGroupRelation findMany
 */
export type StudyGroupRelationFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudyGroupRelation
   */
  select?: Prisma.StudyGroupRelationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudyGroupRelation
   */
  omit?: Prisma.StudyGroupRelationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudyGroupRelationInclude<ExtArgs> | null
  /**
   * Filter, which StudyGroupRelations to fetch.
   */
  where?: Prisma.StudyGroupRelationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StudyGroupRelations to fetch.
   */
  orderBy?: Prisma.StudyGroupRelationOrderByWithRelationInput | Prisma.StudyGroupRelationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing StudyGroupRelations.
   */
  cursor?: Prisma.StudyGroupRelationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StudyGroupRelations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StudyGroupRelations.
   */
  skip?: number
  distinct?: Prisma.StudyGroupRelationScalarFieldEnum | Prisma.StudyGroupRelationScalarFieldEnum[]
}

/**
 * StudyGroupRelation create
 */
export type StudyGroupRelationCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudyGroupRelation
   */
  select?: Prisma.StudyGroupRelationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudyGroupRelation
   */
  omit?: Prisma.StudyGroupRelationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudyGroupRelationInclude<ExtArgs> | null
  /**
   * The data needed to create a StudyGroupRelation.
   */
  data: Prisma.XOR<Prisma.StudyGroupRelationCreateInput, Prisma.StudyGroupRelationUncheckedCreateInput>
}

/**
 * StudyGroupRelation createMany
 */
export type StudyGroupRelationCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many StudyGroupRelations.
   */
  data: Prisma.StudyGroupRelationCreateManyInput | Prisma.StudyGroupRelationCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * StudyGroupRelation createManyAndReturn
 */
export type StudyGroupRelationCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudyGroupRelation
   */
  select?: Prisma.StudyGroupRelationSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the StudyGroupRelation
   */
  omit?: Prisma.StudyGroupRelationOmit<ExtArgs> | null
  /**
   * The data used to create many StudyGroupRelations.
   */
  data: Prisma.StudyGroupRelationCreateManyInput | Prisma.StudyGroupRelationCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudyGroupRelationIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * StudyGroupRelation update
 */
export type StudyGroupRelationUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudyGroupRelation
   */
  select?: Prisma.StudyGroupRelationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudyGroupRelation
   */
  omit?: Prisma.StudyGroupRelationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudyGroupRelationInclude<ExtArgs> | null
  /**
   * The data needed to update a StudyGroupRelation.
   */
  data: Prisma.XOR<Prisma.StudyGroupRelationUpdateInput, Prisma.StudyGroupRelationUncheckedUpdateInput>
  /**
   * Choose, which StudyGroupRelation to update.
   */
  where: Prisma.StudyGroupRelationWhereUniqueInput
}

/**
 * StudyGroupRelation updateMany
 */
export type StudyGroupRelationUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update StudyGroupRelations.
   */
  data: Prisma.XOR<Prisma.StudyGroupRelationUpdateManyMutationInput, Prisma.StudyGroupRelationUncheckedUpdateManyInput>
  /**
   * Filter which StudyGroupRelations to update
   */
  where?: Prisma.StudyGroupRelationWhereInput
  /**
   * Limit how many StudyGroupRelations to update.
   */
  limit?: number
}

/**
 * StudyGroupRelation updateManyAndReturn
 */
export type StudyGroupRelationUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudyGroupRelation
   */
  select?: Prisma.StudyGroupRelationSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the StudyGroupRelation
   */
  omit?: Prisma.StudyGroupRelationOmit<ExtArgs> | null
  /**
   * The data used to update StudyGroupRelations.
   */
  data: Prisma.XOR<Prisma.StudyGroupRelationUpdateManyMutationInput, Prisma.StudyGroupRelationUncheckedUpdateManyInput>
  /**
   * Filter which StudyGroupRelations to update
   */
  where?: Prisma.StudyGroupRelationWhereInput
  /**
   * Limit how many StudyGroupRelations to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudyGroupRelationIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * StudyGroupRelation upsert
 */
export type StudyGroupRelationUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudyGroupRelation
   */
  select?: Prisma.StudyGroupRelationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudyGroupRelation
   */
  omit?: Prisma.StudyGroupRelationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudyGroupRelationInclude<ExtArgs> | null
  /**
   * The filter to search for the StudyGroupRelation to update in case it exists.
   */
  where: Prisma.StudyGroupRelationWhereUniqueInput
  /**
   * In case the StudyGroupRelation found by the `where` argument doesn't exist, create a new StudyGroupRelation with this data.
   */
  create: Prisma.XOR<Prisma.StudyGroupRelationCreateInput, Prisma.StudyGroupRelationUncheckedCreateInput>
  /**
   * In case the StudyGroupRelation was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.StudyGroupRelationUpdateInput, Prisma.StudyGroupRelationUncheckedUpdateInput>
}

/**
 * StudyGroupRelation delete
 */
export type StudyGroupRelationDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudyGroupRelation
   */
  select?: Prisma.StudyGroupRelationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudyGroupRelation
   */
  omit?: Prisma.StudyGroupRelationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudyGroupRelationInclude<ExtArgs> | null
  /**
   * Filter which StudyGroupRelation to delete.
   */
  where: Prisma.StudyGroupRelationWhereUniqueInput
}

/**
 * StudyGroupRelation deleteMany
 */
export type StudyGroupRelationDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which StudyGroupRelations to delete
   */
  where?: Prisma.StudyGroupRelationWhereInput
  /**
   * Limit how many StudyGroupRelations to delete.
   */
  limit?: number
}

/**
 * StudyGroupRelation without action
 */
export type StudyGroupRelationDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudyGroupRelation
   */
  select?: Prisma.StudyGroupRelationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudyGroupRelation
   */
  omit?: Prisma.StudyGroupRelationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudyGroupRelationInclude<ExtArgs> | null
}
