
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `StudyGroup` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model StudyGroup
 * 
 */
export type StudyGroupModel = runtime.Types.Result.DefaultSelection<Prisma.$StudyGroupPayload>

export type AggregateStudyGroup = {
  _count: StudyGroupCountAggregateOutputType | null
  _avg: StudyGroupAvgAggregateOutputType | null
  _sum: StudyGroupSumAggregateOutputType | null
  _min: StudyGroupMinAggregateOutputType | null
  _max: StudyGroupMaxAggregateOutputType | null
}

export type StudyGroupAvgAggregateOutputType = {
  id: number | null
  grade: number | null
}

export type StudyGroupSumAggregateOutputType = {
  id: number | null
  grade: number | null
}

export type StudyGroupMinAggregateOutputType = {
  id: number | null
  grade: number | null
  letter: string | null
  title: string | null
}

export type StudyGroupMaxAggregateOutputType = {
  id: number | null
  grade: number | null
  letter: string | null
  title: string | null
}

export type StudyGroupCountAggregateOutputType = {
  id: number
  grade: number
  letter: number
  title: number
  _all: number
}


export type StudyGroupAvgAggregateInputType = {
  id?: true
  grade?: true
}

export type StudyGroupSumAggregateInputType = {
  id?: true
  grade?: true
}

export type StudyGroupMinAggregateInputType = {
  id?: true
  grade?: true
  letter?: true
  title?: true
}

export type StudyGroupMaxAggregateInputType = {
  id?: true
  grade?: true
  letter?: true
  title?: true
}

export type StudyGroupCountAggregateInputType = {
  id?: true
  grade?: true
  letter?: true
  title?: true
  _all?: true
}

export type StudyGroupAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which StudyGroup to aggregate.
   */
  where?: Prisma.StudyGroupWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StudyGroups to fetch.
   */
  orderBy?: Prisma.StudyGroupOrderByWithRelationInput | Prisma.StudyGroupOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.StudyGroupWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StudyGroups from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StudyGroups.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned StudyGroups
  **/
  _count?: true | StudyGroupCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: StudyGroupAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: StudyGroupSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: StudyGroupMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: StudyGroupMaxAggregateInputType
}

export type GetStudyGroupAggregateType<T extends StudyGroupAggregateArgs> = {
      [P in keyof T & keyof AggregateStudyGroup]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateStudyGroup[P]>
    : Prisma.GetScalarType<T[P], AggregateStudyGroup[P]>
}




export type StudyGroupGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.StudyGroupWhereInput
  orderBy?: Prisma.StudyGroupOrderByWithAggregationInput | Prisma.StudyGroupOrderByWithAggregationInput[]
  by: Prisma.StudyGroupScalarFieldEnum[] | Prisma.StudyGroupScalarFieldEnum
  having?: Prisma.StudyGroupScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: StudyGroupCountAggregateInputType | true
  _avg?: StudyGroupAvgAggregateInputType
  _sum?: StudyGroupSumAggregateInputType
  _min?: StudyGroupMinAggregateInputType
  _max?: StudyGroupMaxAggregateInputType
}

export type StudyGroupGroupByOutputType = {
  id: number
  grade: number | null
  letter: string | null
  title: string
  _count: StudyGroupCountAggregateOutputType | null
  _avg: StudyGroupAvgAggregateOutputType | null
  _sum: StudyGroupSumAggregateOutputType | null
  _min: StudyGroupMinAggregateOutputType | null
  _max: StudyGroupMaxAggregateOutputType | null
}

type GetStudyGroupGroupByPayload<T extends StudyGroupGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<StudyGroupGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof StudyGroupGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], StudyGroupGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], StudyGroupGroupByOutputType[P]>
      }
    >
  >



export type StudyGroupWhereInput = {
  AND?: Prisma.StudyGroupWhereInput | Prisma.StudyGroupWhereInput[]
  OR?: Prisma.StudyGroupWhereInput[]
  NOT?: Prisma.StudyGroupWhereInput | Prisma.StudyGroupWhereInput[]
  id?: Prisma.IntFilter<"StudyGroup"> | number
  grade?: Prisma.IntNullableFilter<"StudyGroup"> | number | null
  letter?: Prisma.StringNullableFilter<"StudyGroup"> | string | null
  title?: Prisma.StringFilter<"StudyGroup"> | string
  homework?: Prisma.HomeworkListRelationFilter
  User?: Prisma.UserListRelationFilter
  studyGroupRelations?: Prisma.StudyGroupRelationListRelationFilter
}

export type StudyGroupOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  grade?: Prisma.SortOrderInput | Prisma.SortOrder
  letter?: Prisma.SortOrderInput | Prisma.SortOrder
  title?: Prisma.SortOrder
  homework?: Prisma.HomeworkOrderByRelationAggregateInput
  User?: Prisma.UserOrderByRelationAggregateInput
  studyGroupRelations?: Prisma.StudyGroupRelationOrderByRelationAggregateInput
}

export type StudyGroupWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.StudyGroupWhereInput | Prisma.StudyGroupWhereInput[]
  OR?: Prisma.StudyGroupWhereInput[]
  NOT?: Prisma.StudyGroupWhereInput | Prisma.StudyGroupWhereInput[]
  grade?: Prisma.IntNullableFilter<"StudyGroup"> | number | null
  letter?: Prisma.StringNullableFilter<"StudyGroup"> | string | null
  title?: Prisma.StringFilter<"StudyGroup"> | string
  homework?: Prisma.HomeworkListRelationFilter
  User?: Prisma.UserListRelationFilter
  studyGroupRelations?: Prisma.StudyGroupRelationListRelationFilter
}, "id">

export type StudyGroupOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  grade?: Prisma.SortOrderInput | Prisma.SortOrder
  letter?: Prisma.SortOrderInput | Prisma.SortOrder
  title?: Prisma.SortOrder
  _count?: Prisma.StudyGroupCountOrderByAggregateInput
  _avg?: Prisma.StudyGroupAvgOrderByAggregateInput
  _max?: Prisma.StudyGroupMaxOrderByAggregateInput
  _min?: Prisma.StudyGroupMinOrderByAggregateInput
  _sum?: Prisma.StudyGroupSumOrderByAggregateInput
}

export type StudyGroupScalarWhereWithAggregatesInput = {
  AND?: Prisma.StudyGroupScalarWhereWithAggregatesInput | Prisma.StudyGroupScalarWhereWithAggregatesInput[]
  OR?: Prisma.StudyGroupScalarWhereWithAggregatesInput[]
  NOT?: Prisma.StudyGroupScalarWhereWithAggregatesInput | Prisma.StudyGroupScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"StudyGroup"> | number
  grade?: Prisma.IntNullableWithAggregatesFilter<"StudyGroup"> | number | null
  letter?: Prisma.StringNullableWithAggregatesFilter<"StudyGroup"> | string | null
  title?: Prisma.StringWithAggregatesFilter<"StudyGroup"> | string
}

export type StudyGroupCreateInput = {
  id?: number
  grade?: number | null
  letter?: string | null
  title: string
  homework?: Prisma.HomeworkCreateNestedManyWithoutStudyGroupInput
  User?: Prisma.UserCreateNestedManyWithoutStudyGroupInput
  studyGroupRelations?: Prisma.StudyGroupRelationCreateNestedManyWithoutGroupInput
}

export type StudyGroupUncheckedCreateInput = {
  id?: number
  grade?: number | null
  letter?: string | null
  title: string
  homework?: Prisma.HomeworkUncheckedCreateNestedManyWithoutStudyGroupInput
  User?: Prisma.UserUncheckedCreateNestedManyWithoutStudyGroupInput
  studyGroupRelations?: Prisma.StudyGroupRelationUncheckedCreateNestedManyWithoutGroupInput
}

export type StudyGroupUpdateInput = {
  grade?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  letter?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  title?: Prisma.StringFieldUpdateOperationsInput | string
  homework?: Prisma.HomeworkUpdateManyWithoutStudyGroupNestedInput
  User?: Prisma.UserUpdateManyWithoutStudyGroupNestedInput
  studyGroupRelations?: Prisma.StudyGroupRelationUpdateManyWithoutGroupNestedInput
}

export type StudyGroupUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  grade?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  letter?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  title?: Prisma.StringFieldUpdateOperationsInput | string
  homework?: Prisma.HomeworkUncheckedUpdateManyWithoutStudyGroupNestedInput
  User?: Prisma.UserUncheckedUpdateManyWithoutStudyGroupNestedInput
  studyGroupRelations?: Prisma.StudyGroupRelationUncheckedUpdateManyWithoutGroupNestedInput
}

export type StudyGroupCreateManyInput = {
  id?: number
  grade?: number | null
  letter?: string | null
  title: string
}

export type StudyGroupUpdateManyMutationInput = {
  grade?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  letter?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  title?: Prisma.StringFieldUpdateOperationsInput | string
}

export type StudyGroupUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  grade?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  letter?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  title?: Prisma.StringFieldUpdateOperationsInput | string
}

export type StudyGroupScalarRelationFilter = {
  is?: Prisma.StudyGroupWhereInput
  isNot?: Prisma.StudyGroupWhereInput
}

export type StudyGroupCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  grade?: Prisma.SortOrder
  letter?: Prisma.SortOrder
  title?: Prisma.SortOrder
}

export type StudyGroupAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  grade?: Prisma.SortOrder
}

export type StudyGroupMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  grade?: Prisma.SortOrder
  letter?: Prisma.SortOrder
  title?: Prisma.SortOrder
}

export type StudyGroupMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  grade?: Prisma.SortOrder
  letter?: Prisma.SortOrder
  title?: Prisma.SortOrder
}

export type StudyGroupSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  grade?: Prisma.SortOrder
}

export type StudyGroupCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.StudyGroupCreateWithoutUserInput, Prisma.StudyGroupUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.StudyGroupCreateOrConnectWithoutUserInput
  connect?: Prisma.StudyGroupWhereUniqueInput
}

export type StudyGroupUpdateOneRequiredWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.StudyGroupCreateWithoutUserInput, Prisma.StudyGroupUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.StudyGroupCreateOrConnectWithoutUserInput
  upsert?: Prisma.StudyGroupUpsertWithoutUserInput
  connect?: Prisma.StudyGroupWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.StudyGroupUpdateToOneWithWhereWithoutUserInput, Prisma.StudyGroupUpdateWithoutUserInput>, Prisma.StudyGroupUncheckedUpdateWithoutUserInput>
}

export type StudyGroupCreateNestedOneWithoutHomeworkInput = {
  create?: Prisma.XOR<Prisma.StudyGroupCreateWithoutHomeworkInput, Prisma.StudyGroupUncheckedCreateWithoutHomeworkInput>
  connectOrCreate?: Prisma.StudyGroupCreateOrConnectWithoutHomeworkInput
  connect?: Prisma.StudyGroupWhereUniqueInput
}

export type StudyGroupUpdateOneRequiredWithoutHomeworkNestedInput = {
  create?: Prisma.XOR<Prisma.StudyGroupCreateWithoutHomeworkInput, Prisma.StudyGroupUncheckedCreateWithoutHomeworkInput>
  connectOrCreate?: Prisma.StudyGroupCreateOrConnectWithoutHomeworkInput
  upsert?: Prisma.StudyGroupUpsertWithoutHomeworkInput
  connect?: Prisma.StudyGroupWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.StudyGroupUpdateToOneWithWhereWithoutHomeworkInput, Prisma.StudyGroupUpdateWithoutHomeworkInput>, Prisma.StudyGroupUncheckedUpdateWithoutHomeworkInput>
}

export type StudyGroupCreateNestedOneWithoutStudyGroupRelationsInput = {
  create?: Prisma.XOR<Prisma.StudyGroupCreateWithoutStudyGroupRelationsInput, Prisma.StudyGroupUncheckedCreateWithoutStudyGroupRelationsInput>
  connectOrCreate?: Prisma.StudyGroupCreateOrConnectWithoutStudyGroupRelationsInput
  connect?: Prisma.StudyGroupWhereUniqueInput
}

export type StudyGroupUpdateOneRequiredWithoutStudyGroupRelationsNestedInput = {
  create?: Prisma.XOR<Prisma.StudyGroupCreateWithoutStudyGroupRelationsInput, Prisma.StudyGroupUncheckedCreateWithoutStudyGroupRelationsInput>
  connectOrCreate?: Prisma.StudyGroupCreateOrConnectWithoutStudyGroupRelationsInput
  upsert?: Prisma.StudyGroupUpsertWithoutStudyGroupRelationsInput
  connect?: Prisma.StudyGroupWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.StudyGroupUpdateToOneWithWhereWithoutStudyGroupRelationsInput, Prisma.StudyGroupUpdateWithoutStudyGroupRelationsInput>, Prisma.StudyGroupUncheckedUpdateWithoutStudyGroupRelationsInput>
}

export type StudyGroupCreateWithoutUserInput = {
  id?: number
  grade?: number | null
  letter?: string | null
  title: string
  homework?: Prisma.HomeworkCreateNestedManyWithoutStudyGroupInput
  studyGroupRelations?: Prisma.StudyGroupRelationCreateNestedManyWithoutGroupInput
}

export type StudyGroupUncheckedCreateWithoutUserInput = {
  id?: number
  grade?: number | null
  letter?: string | null
  title: string
  homework?: Prisma.HomeworkUncheckedCreateNestedManyWithoutStudyGroupInput
  studyGroupRelations?: Prisma.StudyGroupRelationUncheckedCreateNestedManyWithoutGroupInput
}

export type StudyGroupCreateOrConnectWithoutUserInput = {
  where: Prisma.StudyGroupWhereUniqueInput
  create: Prisma.XOR<Prisma.StudyGroupCreateWithoutUserInput, Prisma.StudyGroupUncheckedCreateWithoutUserInput>
}

export type StudyGroupUpsertWithoutUserInput = {
  update: Prisma.XOR<Prisma.StudyGroupUpdateWithoutUserInput, Prisma.StudyGroupUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.StudyGroupCreateWithoutUserInput, Prisma.StudyGroupUncheckedCreateWithoutUserInput>
  where?: Prisma.StudyGroupWhereInput
}

export type StudyGroupUpdateToOneWithWhereWithoutUserInput = {
  where?: Prisma.StudyGroupWhereInput
  data: Prisma.XOR<Prisma.StudyGroupUpdateWithoutUserInput, Prisma.StudyGroupUncheckedUpdateWithoutUserInput>
}

export type StudyGroupUpdateWithoutUserInput = {
  grade?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  letter?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  title?: Prisma.StringFieldUpdateOperationsInput | string
  homework?: Prisma.HomeworkUpdateManyWithoutStudyGroupNestedInput
  studyGroupRelations?: Prisma.StudyGroupRelationUpdateManyWithoutGroupNestedInput
}

export type StudyGroupUncheckedUpdateWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  grade?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  letter?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  title?: Prisma.StringFieldUpdateOperationsInput | string
  homework?: Prisma.HomeworkUncheckedUpdateManyWithoutStudyGroupNestedInput
  studyGroupRelations?: Prisma.StudyGroupRelationUncheckedUpdateManyWithoutGroupNestedInput
}

export type StudyGroupCreateWithoutHomeworkInput = {
  id?: number
  grade?: number | null
  letter?: string | null
  title: string
  User?: Prisma.UserCreateNestedManyWithoutStudyGroupInput
  studyGroupRelations?: Prisma.StudyGroupRelationCreateNestedManyWithoutGroupInput
}

export type StudyGroupUncheckedCreateWithoutHomeworkInput = {
  id?: number
  grade?: number | null
  letter?: string | null
  title: string
  User?: Prisma.UserUncheckedCreateNestedManyWithoutStudyGroupInput
  studyGroupRelations?: Prisma.StudyGroupRelationUncheckedCreateNestedManyWithoutGroupInput
}

export type StudyGroupCreateOrConnectWithoutHomeworkInput = {
  where: Prisma.StudyGroupWhereUniqueInput
  create: Prisma.XOR<Prisma.StudyGroupCreateWithoutHomeworkInput, Prisma.StudyGroupUncheckedCreateWithoutHomeworkInput>
}

export type StudyGroupUpsertWithoutHomeworkInput = {
  update: Prisma.XOR<Prisma.StudyGroupUpdateWithoutHomeworkInput, Prisma.StudyGroupUncheckedUpdateWithoutHomeworkInput>
  create: Prisma.XOR<Prisma.StudyGroupCreateWithoutHomeworkInput, Prisma.StudyGroupUncheckedCreateWithoutHomeworkInput>
  where?: Prisma.StudyGroupWhereInput
}

export type StudyGroupUpdateToOneWithWhereWithoutHomeworkInput = {
  where?: Prisma.StudyGroupWhereInput
  data: Prisma.XOR<Prisma.StudyGroupUpdateWithoutHomeworkInput, Prisma.StudyGroupUncheckedUpdateWithoutHomeworkInput>
}

export type StudyGroupUpdateWithoutHomeworkInput = {
  grade?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  letter?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  title?: Prisma.StringFieldUpdateOperationsInput | string
  User?: Prisma.UserUpdateManyWithoutStudyGroupNestedInput
  studyGroupRelations?: Prisma.StudyGroupRelationUpdateManyWithoutGroupNestedInput
}

export type StudyGroupUncheckedUpdateWithoutHomeworkInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  grade?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  letter?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  title?: Prisma.StringFieldUpdateOperationsInput | string
  User?: Prisma.UserUncheckedUpdateManyWithoutStudyGroupNestedInput
  studyGroupRelations?: Prisma.StudyGroupRelationUncheckedUpdateManyWithoutGroupNestedInput
}

export type StudyGroupCreateWithoutStudyGroupRelationsInput = {
  id?: number
  grade?: number | null
  letter?: string | null
  title: string
  homework?: Prisma.HomeworkCreateNestedManyWithoutStudyGroupInput
  User?: Prisma.UserCreateNestedManyWithoutStudyGroupInput
}

export type StudyGroupUncheckedCreateWithoutStudyGroupRelationsInput = {
  id?: number
  grade?: number | null
  letter?: string | null
  title: string
  homework?: Prisma.HomeworkUncheckedCreateNestedManyWithoutStudyGroupInput
  User?: Prisma.UserUncheckedCreateNestedManyWithoutStudyGroupInput
}

export type StudyGroupCreateOrConnectWithoutStudyGroupRelationsInput = {
  where: Prisma.StudyGroupWhereUniqueInput
  create: Prisma.XOR<Prisma.StudyGroupCreateWithoutStudyGroupRelationsInput, Prisma.StudyGroupUncheckedCreateWithoutStudyGroupRelationsInput>
}

export type StudyGroupUpsertWithoutStudyGroupRelationsInput = {
  update: Prisma.XOR<Prisma.StudyGroupUpdateWithoutStudyGroupRelationsInput, Prisma.StudyGroupUncheckedUpdateWithoutStudyGroupRelationsInput>
  create: Prisma.XOR<Prisma.StudyGroupCreateWithoutStudyGroupRelationsInput, Prisma.StudyGroupUncheckedCreateWithoutStudyGroupRelationsInput>
  where?: Prisma.StudyGroupWhereInput
}

export type StudyGroupUpdateToOneWithWhereWithoutStudyGroupRelationsInput = {
  where?: Prisma.StudyGroupWhereInput
  data: Prisma.XOR<Prisma.StudyGroupUpdateWithoutStudyGroupRelationsInput, Prisma.StudyGroupUncheckedUpdateWithoutStudyGroupRelationsInput>
}

export type StudyGroupUpdateWithoutStudyGroupRelationsInput = {
  grade?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  letter?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  title?: Prisma.StringFieldUpdateOperationsInput | string
  homework?: Prisma.HomeworkUpdateManyWithoutStudyGroupNestedInput
  User?: Prisma.UserUpdateManyWithoutStudyGroupNestedInput
}

export type StudyGroupUncheckedUpdateWithoutStudyGroupRelationsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  grade?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  letter?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  title?: Prisma.StringFieldUpdateOperationsInput | string
  homework?: Prisma.HomeworkUncheckedUpdateManyWithoutStudyGroupNestedInput
  User?: Prisma.UserUncheckedUpdateManyWithoutStudyGroupNestedInput
}


/**
 * Count Type StudyGroupCountOutputType
 */

export type StudyGroupCountOutputType = {
  homework: number
  User: number
  studyGroupRelations: number
}

export type StudyGroupCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  homework?: boolean | StudyGroupCountOutputTypeCountHomeworkArgs
  User?: boolean | StudyGroupCountOutputTypeCountUserArgs
  studyGroupRelations?: boolean | StudyGroupCountOutputTypeCountStudyGroupRelationsArgs
}

/**
 * StudyGroupCountOutputType without action
 */
export type StudyGroupCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudyGroupCountOutputType
   */
  select?: Prisma.StudyGroupCountOutputTypeSelect<ExtArgs> | null
}

/**
 * StudyGroupCountOutputType without action
 */
export type StudyGroupCountOutputTypeCountHomeworkArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.HomeworkWhereInput
}

/**
 * StudyGroupCountOutputType without action
 */
export type StudyGroupCountOutputTypeCountUserArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserWhereInput
}

/**
 * StudyGroupCountOutputType without action
 */
export type StudyGroupCountOutputTypeCountStudyGroupRelationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.StudyGroupRelationWhereInput
}


export type StudyGroupSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  grade?: boolean
  letter?: boolean
  title?: boolean
  homework?: boolean | Prisma.StudyGroup$homeworkArgs<ExtArgs>
  User?: boolean | Prisma.StudyGroup$UserArgs<ExtArgs>
  studyGroupRelations?: boolean | Prisma.StudyGroup$studyGroupRelationsArgs<ExtArgs>
  _count?: boolean | Prisma.StudyGroupCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["studyGroup"]>

export type StudyGroupSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  grade?: boolean
  letter?: boolean
  title?: boolean
}, ExtArgs["result"]["studyGroup"]>

export type StudyGroupSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  grade?: boolean
  letter?: boolean
  title?: boolean
}, ExtArgs["result"]["studyGroup"]>

export type StudyGroupSelectScalar = {
  id?: boolean
  grade?: boolean
  letter?: boolean
  title?: boolean
}

export type StudyGroupOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "grade" | "letter" | "title", ExtArgs["result"]["studyGroup"]>
export type StudyGroupInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  homework?: boolean | Prisma.StudyGroup$homeworkArgs<ExtArgs>
  User?: boolean | Prisma.StudyGroup$UserArgs<ExtArgs>
  studyGroupRelations?: boolean | Prisma.StudyGroup$studyGroupRelationsArgs<ExtArgs>
  _count?: boolean | Prisma.StudyGroupCountOutputTypeDefaultArgs<ExtArgs>
}
export type StudyGroupIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type StudyGroupIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $StudyGroupPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "StudyGroup"
  objects: {
    homework: Prisma.$HomeworkPayload<ExtArgs>[]
    User: Prisma.$UserPayload<ExtArgs>[]
    studyGroupRelations: Prisma.$StudyGroupRelationPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    grade: number | null
    letter: string | null
    title: string
  }, ExtArgs["result"]["studyGroup"]>
  composites: {}
}

export type StudyGroupGetPayload<S extends boolean | null | undefined | StudyGroupDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$StudyGroupPayload, S>

export type StudyGroupCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<StudyGroupFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: StudyGroupCountAggregateInputType | true
  }

export interface StudyGroupDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['StudyGroup'], meta: { name: 'StudyGroup' } }
  /**
   * Find zero or one StudyGroup that matches the filter.
   * @param {StudyGroupFindUniqueArgs} args - Arguments to find a StudyGroup
   * @example
   * // Get one StudyGroup
   * const studyGroup = await prisma.studyGroup.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends StudyGroupFindUniqueArgs>(args: Prisma.SelectSubset<T, StudyGroupFindUniqueArgs<ExtArgs>>): Prisma.Prisma__StudyGroupClient<runtime.Types.Result.GetResult<Prisma.$StudyGroupPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one StudyGroup that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {StudyGroupFindUniqueOrThrowArgs} args - Arguments to find a StudyGroup
   * @example
   * // Get one StudyGroup
   * const studyGroup = await prisma.studyGroup.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends StudyGroupFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, StudyGroupFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__StudyGroupClient<runtime.Types.Result.GetResult<Prisma.$StudyGroupPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first StudyGroup that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StudyGroupFindFirstArgs} args - Arguments to find a StudyGroup
   * @example
   * // Get one StudyGroup
   * const studyGroup = await prisma.studyGroup.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends StudyGroupFindFirstArgs>(args?: Prisma.SelectSubset<T, StudyGroupFindFirstArgs<ExtArgs>>): Prisma.Prisma__StudyGroupClient<runtime.Types.Result.GetResult<Prisma.$StudyGroupPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first StudyGroup that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StudyGroupFindFirstOrThrowArgs} args - Arguments to find a StudyGroup
   * @example
   * // Get one StudyGroup
   * const studyGroup = await prisma.studyGroup.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends StudyGroupFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, StudyGroupFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__StudyGroupClient<runtime.Types.Result.GetResult<Prisma.$StudyGroupPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more StudyGroups that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StudyGroupFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all StudyGroups
   * const studyGroups = await prisma.studyGroup.findMany()
   * 
   * // Get first 10 StudyGroups
   * const studyGroups = await prisma.studyGroup.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const studyGroupWithIdOnly = await prisma.studyGroup.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends StudyGroupFindManyArgs>(args?: Prisma.SelectSubset<T, StudyGroupFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StudyGroupPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a StudyGroup.
   * @param {StudyGroupCreateArgs} args - Arguments to create a StudyGroup.
   * @example
   * // Create one StudyGroup
   * const StudyGroup = await prisma.studyGroup.create({
   *   data: {
   *     // ... data to create a StudyGroup
   *   }
   * })
   * 
   */
  create<T extends StudyGroupCreateArgs>(args: Prisma.SelectSubset<T, StudyGroupCreateArgs<ExtArgs>>): Prisma.Prisma__StudyGroupClient<runtime.Types.Result.GetResult<Prisma.$StudyGroupPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many StudyGroups.
   * @param {StudyGroupCreateManyArgs} args - Arguments to create many StudyGroups.
   * @example
   * // Create many StudyGroups
   * const studyGroup = await prisma.studyGroup.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends StudyGroupCreateManyArgs>(args?: Prisma.SelectSubset<T, StudyGroupCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many StudyGroups and returns the data saved in the database.
   * @param {StudyGroupCreateManyAndReturnArgs} args - Arguments to create many StudyGroups.
   * @example
   * // Create many StudyGroups
   * const studyGroup = await prisma.studyGroup.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many StudyGroups and only return the `id`
   * const studyGroupWithIdOnly = await prisma.studyGroup.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends StudyGroupCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, StudyGroupCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StudyGroupPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a StudyGroup.
   * @param {StudyGroupDeleteArgs} args - Arguments to delete one StudyGroup.
   * @example
   * // Delete one StudyGroup
   * const StudyGroup = await prisma.studyGroup.delete({
   *   where: {
   *     // ... filter to delete one StudyGroup
   *   }
   * })
   * 
   */
  delete<T extends StudyGroupDeleteArgs>(args: Prisma.SelectSubset<T, StudyGroupDeleteArgs<ExtArgs>>): Prisma.Prisma__StudyGroupClient<runtime.Types.Result.GetResult<Prisma.$StudyGroupPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one StudyGroup.
   * @param {StudyGroupUpdateArgs} args - Arguments to update one StudyGroup.
   * @example
   * // Update one StudyGroup
   * const studyGroup = await prisma.studyGroup.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends StudyGroupUpdateArgs>(args: Prisma.SelectSubset<T, StudyGroupUpdateArgs<ExtArgs>>): Prisma.Prisma__StudyGroupClient<runtime.Types.Result.GetResult<Prisma.$StudyGroupPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more StudyGroups.
   * @param {StudyGroupDeleteManyArgs} args - Arguments to filter StudyGroups to delete.
   * @example
   * // Delete a few StudyGroups
   * const { count } = await prisma.studyGroup.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends StudyGroupDeleteManyArgs>(args?: Prisma.SelectSubset<T, StudyGroupDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more StudyGroups.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StudyGroupUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many StudyGroups
   * const studyGroup = await prisma.studyGroup.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends StudyGroupUpdateManyArgs>(args: Prisma.SelectSubset<T, StudyGroupUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more StudyGroups and returns the data updated in the database.
   * @param {StudyGroupUpdateManyAndReturnArgs} args - Arguments to update many StudyGroups.
   * @example
   * // Update many StudyGroups
   * const studyGroup = await prisma.studyGroup.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more StudyGroups and only return the `id`
   * const studyGroupWithIdOnly = await prisma.studyGroup.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends StudyGroupUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, StudyGroupUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StudyGroupPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one StudyGroup.
   * @param {StudyGroupUpsertArgs} args - Arguments to update or create a StudyGroup.
   * @example
   * // Update or create a StudyGroup
   * const studyGroup = await prisma.studyGroup.upsert({
   *   create: {
   *     // ... data to create a StudyGroup
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the StudyGroup we want to update
   *   }
   * })
   */
  upsert<T extends StudyGroupUpsertArgs>(args: Prisma.SelectSubset<T, StudyGroupUpsertArgs<ExtArgs>>): Prisma.Prisma__StudyGroupClient<runtime.Types.Result.GetResult<Prisma.$StudyGroupPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of StudyGroups.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StudyGroupCountArgs} args - Arguments to filter StudyGroups to count.
   * @example
   * // Count the number of StudyGroups
   * const count = await prisma.studyGroup.count({
   *   where: {
   *     // ... the filter for the StudyGroups we want to count
   *   }
   * })
  **/
  count<T extends StudyGroupCountArgs>(
    args?: Prisma.Subset<T, StudyGroupCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], StudyGroupCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a StudyGroup.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StudyGroupAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends StudyGroupAggregateArgs>(args: Prisma.Subset<T, StudyGroupAggregateArgs>): Prisma.PrismaPromise<GetStudyGroupAggregateType<T>>

  /**
   * Group by StudyGroup.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StudyGroupGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends StudyGroupGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: StudyGroupGroupByArgs['orderBy'] }
      : { orderBy?: StudyGroupGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, StudyGroupGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetStudyGroupGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the StudyGroup model
 */
readonly fields: StudyGroupFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for StudyGroup.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__StudyGroupClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  homework<T extends Prisma.StudyGroup$homeworkArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.StudyGroup$homeworkArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HomeworkPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  User<T extends Prisma.StudyGroup$UserArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.StudyGroup$UserArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  studyGroupRelations<T extends Prisma.StudyGroup$studyGroupRelationsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.StudyGroup$studyGroupRelationsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StudyGroupRelationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the StudyGroup model
 */
export interface StudyGroupFieldRefs {
  readonly id: Prisma.FieldRef<"StudyGroup", 'Int'>
  readonly grade: Prisma.FieldRef<"StudyGroup", 'Int'>
  readonly letter: Prisma.FieldRef<"StudyGroup", 'String'>
  readonly title: Prisma.FieldRef<"StudyGroup", 'String'>
}
    

// Custom InputTypes
/**
 * StudyGroup findUnique
 */
export type StudyGroupFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudyGroup
   */
  select?: Prisma.StudyGroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudyGroup
   */
  omit?: Prisma.StudyGroupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudyGroupInclude<ExtArgs> | null
  /**
   * Filter, which StudyGroup to fetch.
   */
  where: Prisma.StudyGroupWhereUniqueInput
}

/**
 * StudyGroup findUniqueOrThrow
 */
export type StudyGroupFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudyGroup
   */
  select?: Prisma.StudyGroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudyGroup
   */
  omit?: Prisma.StudyGroupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudyGroupInclude<ExtArgs> | null
  /**
   * Filter, which StudyGroup to fetch.
   */
  where: Prisma.StudyGroupWhereUniqueInput
}

/**
 * StudyGroup findFirst
 */
export type StudyGroupFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudyGroup
   */
  select?: Prisma.StudyGroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudyGroup
   */
  omit?: Prisma.StudyGroupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudyGroupInclude<ExtArgs> | null
  /**
   * Filter, which StudyGroup to fetch.
   */
  where?: Prisma.StudyGroupWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StudyGroups to fetch.
   */
  orderBy?: Prisma.StudyGroupOrderByWithRelationInput | Prisma.StudyGroupOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for StudyGroups.
   */
  cursor?: Prisma.StudyGroupWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StudyGroups from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StudyGroups.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of StudyGroups.
   */
  distinct?: Prisma.StudyGroupScalarFieldEnum | Prisma.StudyGroupScalarFieldEnum[]
}

/**
 * StudyGroup findFirstOrThrow
 */
export type StudyGroupFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudyGroup
   */
  select?: Prisma.StudyGroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudyGroup
   */
  omit?: Prisma.StudyGroupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudyGroupInclude<ExtArgs> | null
  /**
   * Filter, which StudyGroup to fetch.
   */
  where?: Prisma.StudyGroupWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StudyGroups to fetch.
   */
  orderBy?: Prisma.StudyGroupOrderByWithRelationInput | Prisma.StudyGroupOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for StudyGroups.
   */
  cursor?: Prisma.StudyGroupWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StudyGroups from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StudyGroups.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of StudyGroups.
   */
  distinct?: Prisma.StudyGroupScalarFieldEnum | Prisma.StudyGroupScalarFieldEnum[]
}

/**
 * StudyGroup findMany
 */
export type StudyGroupFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudyGroup
   */
  select?: Prisma.StudyGroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudyGroup
   */
  omit?: Prisma.StudyGroupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudyGroupInclude<ExtArgs> | null
  /**
   * Filter, which StudyGroups to fetch.
   */
  where?: Prisma.StudyGroupWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StudyGroups to fetch.
   */
  orderBy?: Prisma.StudyGroupOrderByWithRelationInput | Prisma.StudyGroupOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing StudyGroups.
   */
  cursor?: Prisma.StudyGroupWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StudyGroups from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StudyGroups.
   */
  skip?: number
  distinct?: Prisma.StudyGroupScalarFieldEnum | Prisma.StudyGroupScalarFieldEnum[]
}

/**
 * StudyGroup create
 */
export type StudyGroupCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudyGroup
   */
  select?: Prisma.StudyGroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudyGroup
   */
  omit?: Prisma.StudyGroupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudyGroupInclude<ExtArgs> | null
  /**
   * The data needed to create a StudyGroup.
   */
  data: Prisma.XOR<Prisma.StudyGroupCreateInput, Prisma.StudyGroupUncheckedCreateInput>
}

/**
 * StudyGroup createMany
 */
export type StudyGroupCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many StudyGroups.
   */
  data: Prisma.StudyGroupCreateManyInput | Prisma.StudyGroupCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * StudyGroup createManyAndReturn
 */
export type StudyGroupCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudyGroup
   */
  select?: Prisma.StudyGroupSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the StudyGroup
   */
  omit?: Prisma.StudyGroupOmit<ExtArgs> | null
  /**
   * The data used to create many StudyGroups.
   */
  data: Prisma.StudyGroupCreateManyInput | Prisma.StudyGroupCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * StudyGroup update
 */
export type StudyGroupUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudyGroup
   */
  select?: Prisma.StudyGroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudyGroup
   */
  omit?: Prisma.StudyGroupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudyGroupInclude<ExtArgs> | null
  /**
   * The data needed to update a StudyGroup.
   */
  data: Prisma.XOR<Prisma.StudyGroupUpdateInput, Prisma.StudyGroupUncheckedUpdateInput>
  /**
   * Choose, which StudyGroup to update.
   */
  where: Prisma.StudyGroupWhereUniqueInput
}

/**
 * StudyGroup updateMany
 */
export type StudyGroupUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update StudyGroups.
   */
  data: Prisma.XOR<Prisma.StudyGroupUpdateManyMutationInput, Prisma.StudyGroupUncheckedUpdateManyInput>
  /**
   * Filter which StudyGroups to update
   */
  where?: Prisma.StudyGroupWhereInput
  /**
   * Limit how many StudyGroups to update.
   */
  limit?: number
}

/**
 * StudyGroup updateManyAndReturn
 */
export type StudyGroupUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudyGroup
   */
  select?: Prisma.StudyGroupSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the StudyGroup
   */
  omit?: Prisma.StudyGroupOmit<ExtArgs> | null
  /**
   * The data used to update StudyGroups.
   */
  data: Prisma.XOR<Prisma.StudyGroupUpdateManyMutationInput, Prisma.StudyGroupUncheckedUpdateManyInput>
  /**
   * Filter which StudyGroups to update
   */
  where?: Prisma.StudyGroupWhereInput
  /**
   * Limit how many StudyGroups to update.
   */
  limit?: number
}

/**
 * StudyGroup upsert
 */
export type StudyGroupUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudyGroup
   */
  select?: Prisma.StudyGroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudyGroup
   */
  omit?: Prisma.StudyGroupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudyGroupInclude<ExtArgs> | null
  /**
   * The filter to search for the StudyGroup to update in case it exists.
   */
  where: Prisma.StudyGroupWhereUniqueInput
  /**
   * In case the StudyGroup found by the `where` argument doesn't exist, create a new StudyGroup with this data.
   */
  create: Prisma.XOR<Prisma.StudyGroupCreateInput, Prisma.StudyGroupUncheckedCreateInput>
  /**
   * In case the StudyGroup was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.StudyGroupUpdateInput, Prisma.StudyGroupUncheckedUpdateInput>
}

/**
 * StudyGroup delete
 */
export type StudyGroupDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudyGroup
   */
  select?: Prisma.StudyGroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudyGroup
   */
  omit?: Prisma.StudyGroupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudyGroupInclude<ExtArgs> | null
  /**
   * Filter which StudyGroup to delete.
   */
  where: Prisma.StudyGroupWhereUniqueInput
}

/**
 * StudyGroup deleteMany
 */
export type StudyGroupDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which StudyGroups to delete
   */
  where?: Prisma.StudyGroupWhereInput
  /**
   * Limit how many StudyGroups to delete.
   */
  limit?: number
}

/**
 * StudyGroup.homework
 */
export type StudyGroup$homeworkArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Homework
   */
  select?: Prisma.HomeworkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Homework
   */
  omit?: Prisma.HomeworkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HomeworkInclude<ExtArgs> | null
  where?: Prisma.HomeworkWhereInput
  orderBy?: Prisma.HomeworkOrderByWithRelationInput | Prisma.HomeworkOrderByWithRelationInput[]
  cursor?: Prisma.HomeworkWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.HomeworkScalarFieldEnum | Prisma.HomeworkScalarFieldEnum[]
}

/**
 * StudyGroup.User
 */
export type StudyGroup$UserArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  cursor?: Prisma.UserWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.UserScalarFieldEnum | Prisma.UserScalarFieldEnum[]
}

/**
 * StudyGroup.studyGroupRelations
 */
export type StudyGroup$studyGroupRelationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudyGroupRelation
   */
  select?: Prisma.StudyGroupRelationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudyGroupRelation
   */
  omit?: Prisma.StudyGroupRelationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudyGroupRelationInclude<ExtArgs> | null
  where?: Prisma.StudyGroupRelationWhereInput
  orderBy?: Prisma.StudyGroupRelationOrderByWithRelationInput | Prisma.StudyGroupRelationOrderByWithRelationInput[]
  cursor?: Prisma.StudyGroupRelationWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.StudyGroupRelationScalarFieldEnum | Prisma.StudyGroupRelationScalarFieldEnum[]
}

/**
 * StudyGroup without action
 */
export type StudyGroupDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudyGroup
   */
  select?: Prisma.StudyGroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudyGroup
   */
  omit?: Prisma.StudyGroupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudyGroupInclude<ExtArgs> | null
}
