
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `UserHomework` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model UserHomework
 * 
 */
export type UserHomeworkModel = runtime.Types.Result.DefaultSelection<Prisma.$UserHomeworkPayload>

export type AggregateUserHomework = {
  _count: UserHomeworkCountAggregateOutputType | null
  _avg: UserHomeworkAvgAggregateOutputType | null
  _sum: UserHomeworkSumAggregateOutputType | null
  _min: UserHomeworkMinAggregateOutputType | null
  _max: UserHomeworkMaxAggregateOutputType | null
}

export type UserHomeworkAvgAggregateOutputType = {
  id: number | null
  user_id: number | null
  homework_id: number | null
  score: number | null
}

export type UserHomeworkSumAggregateOutputType = {
  id: number | null
  user_id: bigint | null
  homework_id: number | null
  score: number | null
}

export type UserHomeworkMinAggregateOutputType = {
  id: number | null
  user_id: bigint | null
  homework_id: number | null
  deleted: boolean | null
  checked: boolean | null
  score: number | null
  completedAt: Date | null
}

export type UserHomeworkMaxAggregateOutputType = {
  id: number | null
  user_id: bigint | null
  homework_id: number | null
  deleted: boolean | null
  checked: boolean | null
  score: number | null
  completedAt: Date | null
}

export type UserHomeworkCountAggregateOutputType = {
  id: number
  user_id: number
  homework_id: number
  deleted: number
  checked: number
  score: number
  completedAt: number
  _all: number
}


export type UserHomeworkAvgAggregateInputType = {
  id?: true
  user_id?: true
  homework_id?: true
  score?: true
}

export type UserHomeworkSumAggregateInputType = {
  id?: true
  user_id?: true
  homework_id?: true
  score?: true
}

export type UserHomeworkMinAggregateInputType = {
  id?: true
  user_id?: true
  homework_id?: true
  deleted?: true
  checked?: true
  score?: true
  completedAt?: true
}

export type UserHomeworkMaxAggregateInputType = {
  id?: true
  user_id?: true
  homework_id?: true
  deleted?: true
  checked?: true
  score?: true
  completedAt?: true
}

export type UserHomeworkCountAggregateInputType = {
  id?: true
  user_id?: true
  homework_id?: true
  deleted?: true
  checked?: true
  score?: true
  completedAt?: true
  _all?: true
}

export type UserHomeworkAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserHomework to aggregate.
   */
  where?: Prisma.UserHomeworkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserHomeworks to fetch.
   */
  orderBy?: Prisma.UserHomeworkOrderByWithRelationInput | Prisma.UserHomeworkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UserHomeworkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserHomeworks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserHomeworks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned UserHomeworks
  **/
  _count?: true | UserHomeworkCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: UserHomeworkAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: UserHomeworkSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UserHomeworkMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UserHomeworkMaxAggregateInputType
}

export type GetUserHomeworkAggregateType<T extends UserHomeworkAggregateArgs> = {
      [P in keyof T & keyof AggregateUserHomework]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUserHomework[P]>
    : Prisma.GetScalarType<T[P], AggregateUserHomework[P]>
}




export type UserHomeworkGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserHomeworkWhereInput
  orderBy?: Prisma.UserHomeworkOrderByWithAggregationInput | Prisma.UserHomeworkOrderByWithAggregationInput[]
  by: Prisma.UserHomeworkScalarFieldEnum[] | Prisma.UserHomeworkScalarFieldEnum
  having?: Prisma.UserHomeworkScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UserHomeworkCountAggregateInputType | true
  _avg?: UserHomeworkAvgAggregateInputType
  _sum?: UserHomeworkSumAggregateInputType
  _min?: UserHomeworkMinAggregateInputType
  _max?: UserHomeworkMaxAggregateInputType
}

export type UserHomeworkGroupByOutputType = {
  id: number
  user_id: bigint
  homework_id: number
  deleted: boolean
  checked: boolean
  score: number | null
  completedAt: Date
  _count: UserHomeworkCountAggregateOutputType | null
  _avg: UserHomeworkAvgAggregateOutputType | null
  _sum: UserHomeworkSumAggregateOutputType | null
  _min: UserHomeworkMinAggregateOutputType | null
  _max: UserHomeworkMaxAggregateOutputType | null
}

type GetUserHomeworkGroupByPayload<T extends UserHomeworkGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UserHomeworkGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UserHomeworkGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UserHomeworkGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UserHomeworkGroupByOutputType[P]>
      }
    >
  >



export type UserHomeworkWhereInput = {
  AND?: Prisma.UserHomeworkWhereInput | Prisma.UserHomeworkWhereInput[]
  OR?: Prisma.UserHomeworkWhereInput[]
  NOT?: Prisma.UserHomeworkWhereInput | Prisma.UserHomeworkWhereInput[]
  id?: Prisma.IntFilter<"UserHomework"> | number
  user_id?: Prisma.BigIntFilter<"UserHomework"> | bigint | number
  homework_id?: Prisma.IntFilter<"UserHomework"> | number
  deleted?: Prisma.BoolFilter<"UserHomework"> | boolean
  checked?: Prisma.BoolFilter<"UserHomework"> | boolean
  score?: Prisma.IntNullableFilter<"UserHomework"> | number | null
  completedAt?: Prisma.DateTimeFilter<"UserHomework"> | Date | string
  homework?: Prisma.XOR<Prisma.HomeworkScalarRelationFilter, Prisma.HomeworkWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type UserHomeworkOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  homework_id?: Prisma.SortOrder
  deleted?: Prisma.SortOrder
  checked?: Prisma.SortOrder
  score?: Prisma.SortOrderInput | Prisma.SortOrder
  completedAt?: Prisma.SortOrder
  homework?: Prisma.HomeworkOrderByWithRelationInput
  user?: Prisma.UserOrderByWithRelationInput
}

export type UserHomeworkWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  user_id_homework_id?: Prisma.UserHomeworkUser_idHomework_idCompoundUniqueInput
  AND?: Prisma.UserHomeworkWhereInput | Prisma.UserHomeworkWhereInput[]
  OR?: Prisma.UserHomeworkWhereInput[]
  NOT?: Prisma.UserHomeworkWhereInput | Prisma.UserHomeworkWhereInput[]
  user_id?: Prisma.BigIntFilter<"UserHomework"> | bigint | number
  homework_id?: Prisma.IntFilter<"UserHomework"> | number
  deleted?: Prisma.BoolFilter<"UserHomework"> | boolean
  checked?: Prisma.BoolFilter<"UserHomework"> | boolean
  score?: Prisma.IntNullableFilter<"UserHomework"> | number | null
  completedAt?: Prisma.DateTimeFilter<"UserHomework"> | Date | string
  homework?: Prisma.XOR<Prisma.HomeworkScalarRelationFilter, Prisma.HomeworkWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id" | "user_id_homework_id">

export type UserHomeworkOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  homework_id?: Prisma.SortOrder
  deleted?: Prisma.SortOrder
  checked?: Prisma.SortOrder
  score?: Prisma.SortOrderInput | Prisma.SortOrder
  completedAt?: Prisma.SortOrder
  _count?: Prisma.UserHomeworkCountOrderByAggregateInput
  _avg?: Prisma.UserHomeworkAvgOrderByAggregateInput
  _max?: Prisma.UserHomeworkMaxOrderByAggregateInput
  _min?: Prisma.UserHomeworkMinOrderByAggregateInput
  _sum?: Prisma.UserHomeworkSumOrderByAggregateInput
}

export type UserHomeworkScalarWhereWithAggregatesInput = {
  AND?: Prisma.UserHomeworkScalarWhereWithAggregatesInput | Prisma.UserHomeworkScalarWhereWithAggregatesInput[]
  OR?: Prisma.UserHomeworkScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UserHomeworkScalarWhereWithAggregatesInput | Prisma.UserHomeworkScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"UserHomework"> | number
  user_id?: Prisma.BigIntWithAggregatesFilter<"UserHomework"> | bigint | number
  homework_id?: Prisma.IntWithAggregatesFilter<"UserHomework"> | number
  deleted?: Prisma.BoolWithAggregatesFilter<"UserHomework"> | boolean
  checked?: Prisma.BoolWithAggregatesFilter<"UserHomework"> | boolean
  score?: Prisma.IntNullableWithAggregatesFilter<"UserHomework"> | number | null
  completedAt?: Prisma.DateTimeWithAggregatesFilter<"UserHomework"> | Date | string
}

export type UserHomeworkCreateInput = {
  deleted?: boolean
  checked?: boolean
  score?: number | null
  completedAt?: Date | string
  homework: Prisma.HomeworkCreateNestedOneWithoutUserHomeworksInput
  user: Prisma.UserCreateNestedOneWithoutUserHomeworksInput
}

export type UserHomeworkUncheckedCreateInput = {
  id?: number
  user_id: bigint | number
  homework_id: number
  deleted?: boolean
  checked?: boolean
  score?: number | null
  completedAt?: Date | string
}

export type UserHomeworkUpdateInput = {
  deleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  checked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  score?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  completedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  homework?: Prisma.HomeworkUpdateOneRequiredWithoutUserHomeworksNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutUserHomeworksNestedInput
}

export type UserHomeworkUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  user_id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  homework_id?: Prisma.IntFieldUpdateOperationsInput | number
  deleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  checked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  score?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  completedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserHomeworkCreateManyInput = {
  id?: number
  user_id: bigint | number
  homework_id: number
  deleted?: boolean
  checked?: boolean
  score?: number | null
  completedAt?: Date | string
}

export type UserHomeworkUpdateManyMutationInput = {
  deleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  checked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  score?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  completedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserHomeworkUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  user_id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  homework_id?: Prisma.IntFieldUpdateOperationsInput | number
  deleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  checked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  score?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  completedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserHomeworkListRelationFilter = {
  every?: Prisma.UserHomeworkWhereInput
  some?: Prisma.UserHomeworkWhereInput
  none?: Prisma.UserHomeworkWhereInput
}

export type UserHomeworkOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type UserHomeworkUser_idHomework_idCompoundUniqueInput = {
  user_id: bigint | number
  homework_id: number
}

export type UserHomeworkCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  homework_id?: Prisma.SortOrder
  deleted?: Prisma.SortOrder
  checked?: Prisma.SortOrder
  score?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
}

export type UserHomeworkAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  homework_id?: Prisma.SortOrder
  score?: Prisma.SortOrder
}

export type UserHomeworkMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  homework_id?: Prisma.SortOrder
  deleted?: Prisma.SortOrder
  checked?: Prisma.SortOrder
  score?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
}

export type UserHomeworkMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  homework_id?: Prisma.SortOrder
  deleted?: Prisma.SortOrder
  checked?: Prisma.SortOrder
  score?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
}

export type UserHomeworkSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  homework_id?: Prisma.SortOrder
  score?: Prisma.SortOrder
}

export type UserHomeworkCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UserHomeworkCreateWithoutUserInput, Prisma.UserHomeworkUncheckedCreateWithoutUserInput> | Prisma.UserHomeworkCreateWithoutUserInput[] | Prisma.UserHomeworkUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserHomeworkCreateOrConnectWithoutUserInput | Prisma.UserHomeworkCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UserHomeworkCreateManyUserInputEnvelope
  connect?: Prisma.UserHomeworkWhereUniqueInput | Prisma.UserHomeworkWhereUniqueInput[]
}

export type UserHomeworkUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UserHomeworkCreateWithoutUserInput, Prisma.UserHomeworkUncheckedCreateWithoutUserInput> | Prisma.UserHomeworkCreateWithoutUserInput[] | Prisma.UserHomeworkUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserHomeworkCreateOrConnectWithoutUserInput | Prisma.UserHomeworkCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UserHomeworkCreateManyUserInputEnvelope
  connect?: Prisma.UserHomeworkWhereUniqueInput | Prisma.UserHomeworkWhereUniqueInput[]
}

export type UserHomeworkUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UserHomeworkCreateWithoutUserInput, Prisma.UserHomeworkUncheckedCreateWithoutUserInput> | Prisma.UserHomeworkCreateWithoutUserInput[] | Prisma.UserHomeworkUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserHomeworkCreateOrConnectWithoutUserInput | Prisma.UserHomeworkCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.UserHomeworkUpsertWithWhereUniqueWithoutUserInput | Prisma.UserHomeworkUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UserHomeworkCreateManyUserInputEnvelope
  set?: Prisma.UserHomeworkWhereUniqueInput | Prisma.UserHomeworkWhereUniqueInput[]
  disconnect?: Prisma.UserHomeworkWhereUniqueInput | Prisma.UserHomeworkWhereUniqueInput[]
  delete?: Prisma.UserHomeworkWhereUniqueInput | Prisma.UserHomeworkWhereUniqueInput[]
  connect?: Prisma.UserHomeworkWhereUniqueInput | Prisma.UserHomeworkWhereUniqueInput[]
  update?: Prisma.UserHomeworkUpdateWithWhereUniqueWithoutUserInput | Prisma.UserHomeworkUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.UserHomeworkUpdateManyWithWhereWithoutUserInput | Prisma.UserHomeworkUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.UserHomeworkScalarWhereInput | Prisma.UserHomeworkScalarWhereInput[]
}

export type UserHomeworkUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UserHomeworkCreateWithoutUserInput, Prisma.UserHomeworkUncheckedCreateWithoutUserInput> | Prisma.UserHomeworkCreateWithoutUserInput[] | Prisma.UserHomeworkUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserHomeworkCreateOrConnectWithoutUserInput | Prisma.UserHomeworkCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.UserHomeworkUpsertWithWhereUniqueWithoutUserInput | Prisma.UserHomeworkUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UserHomeworkCreateManyUserInputEnvelope
  set?: Prisma.UserHomeworkWhereUniqueInput | Prisma.UserHomeworkWhereUniqueInput[]
  disconnect?: Prisma.UserHomeworkWhereUniqueInput | Prisma.UserHomeworkWhereUniqueInput[]
  delete?: Prisma.UserHomeworkWhereUniqueInput | Prisma.UserHomeworkWhereUniqueInput[]
  connect?: Prisma.UserHomeworkWhereUniqueInput | Prisma.UserHomeworkWhereUniqueInput[]
  update?: Prisma.UserHomeworkUpdateWithWhereUniqueWithoutUserInput | Prisma.UserHomeworkUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.UserHomeworkUpdateManyWithWhereWithoutUserInput | Prisma.UserHomeworkUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.UserHomeworkScalarWhereInput | Prisma.UserHomeworkScalarWhereInput[]
}

export type UserHomeworkCreateNestedManyWithoutHomeworkInput = {
  create?: Prisma.XOR<Prisma.UserHomeworkCreateWithoutHomeworkInput, Prisma.UserHomeworkUncheckedCreateWithoutHomeworkInput> | Prisma.UserHomeworkCreateWithoutHomeworkInput[] | Prisma.UserHomeworkUncheckedCreateWithoutHomeworkInput[]
  connectOrCreate?: Prisma.UserHomeworkCreateOrConnectWithoutHomeworkInput | Prisma.UserHomeworkCreateOrConnectWithoutHomeworkInput[]
  createMany?: Prisma.UserHomeworkCreateManyHomeworkInputEnvelope
  connect?: Prisma.UserHomeworkWhereUniqueInput | Prisma.UserHomeworkWhereUniqueInput[]
}

export type UserHomeworkUncheckedCreateNestedManyWithoutHomeworkInput = {
  create?: Prisma.XOR<Prisma.UserHomeworkCreateWithoutHomeworkInput, Prisma.UserHomeworkUncheckedCreateWithoutHomeworkInput> | Prisma.UserHomeworkCreateWithoutHomeworkInput[] | Prisma.UserHomeworkUncheckedCreateWithoutHomeworkInput[]
  connectOrCreate?: Prisma.UserHomeworkCreateOrConnectWithoutHomeworkInput | Prisma.UserHomeworkCreateOrConnectWithoutHomeworkInput[]
  createMany?: Prisma.UserHomeworkCreateManyHomeworkInputEnvelope
  connect?: Prisma.UserHomeworkWhereUniqueInput | Prisma.UserHomeworkWhereUniqueInput[]
}

export type UserHomeworkUpdateManyWithoutHomeworkNestedInput = {
  create?: Prisma.XOR<Prisma.UserHomeworkCreateWithoutHomeworkInput, Prisma.UserHomeworkUncheckedCreateWithoutHomeworkInput> | Prisma.UserHomeworkCreateWithoutHomeworkInput[] | Prisma.UserHomeworkUncheckedCreateWithoutHomeworkInput[]
  connectOrCreate?: Prisma.UserHomeworkCreateOrConnectWithoutHomeworkInput | Prisma.UserHomeworkCreateOrConnectWithoutHomeworkInput[]
  upsert?: Prisma.UserHomeworkUpsertWithWhereUniqueWithoutHomeworkInput | Prisma.UserHomeworkUpsertWithWhereUniqueWithoutHomeworkInput[]
  createMany?: Prisma.UserHomeworkCreateManyHomeworkInputEnvelope
  set?: Prisma.UserHomeworkWhereUniqueInput | Prisma.UserHomeworkWhereUniqueInput[]
  disconnect?: Prisma.UserHomeworkWhereUniqueInput | Prisma.UserHomeworkWhereUniqueInput[]
  delete?: Prisma.UserHomeworkWhereUniqueInput | Prisma.UserHomeworkWhereUniqueInput[]
  connect?: Prisma.UserHomeworkWhereUniqueInput | Prisma.UserHomeworkWhereUniqueInput[]
  update?: Prisma.UserHomeworkUpdateWithWhereUniqueWithoutHomeworkInput | Prisma.UserHomeworkUpdateWithWhereUniqueWithoutHomeworkInput[]
  updateMany?: Prisma.UserHomeworkUpdateManyWithWhereWithoutHomeworkInput | Prisma.UserHomeworkUpdateManyWithWhereWithoutHomeworkInput[]
  deleteMany?: Prisma.UserHomeworkScalarWhereInput | Prisma.UserHomeworkScalarWhereInput[]
}

export type UserHomeworkUncheckedUpdateManyWithoutHomeworkNestedInput = {
  create?: Prisma.XOR<Prisma.UserHomeworkCreateWithoutHomeworkInput, Prisma.UserHomeworkUncheckedCreateWithoutHomeworkInput> | Prisma.UserHomeworkCreateWithoutHomeworkInput[] | Prisma.UserHomeworkUncheckedCreateWithoutHomeworkInput[]
  connectOrCreate?: Prisma.UserHomeworkCreateOrConnectWithoutHomeworkInput | Prisma.UserHomeworkCreateOrConnectWithoutHomeworkInput[]
  upsert?: Prisma.UserHomeworkUpsertWithWhereUniqueWithoutHomeworkInput | Prisma.UserHomeworkUpsertWithWhereUniqueWithoutHomeworkInput[]
  createMany?: Prisma.UserHomeworkCreateManyHomeworkInputEnvelope
  set?: Prisma.UserHomeworkWhereUniqueInput | Prisma.UserHomeworkWhereUniqueInput[]
  disconnect?: Prisma.UserHomeworkWhereUniqueInput | Prisma.UserHomeworkWhereUniqueInput[]
  delete?: Prisma.UserHomeworkWhereUniqueInput | Prisma.UserHomeworkWhereUniqueInput[]
  connect?: Prisma.UserHomeworkWhereUniqueInput | Prisma.UserHomeworkWhereUniqueInput[]
  update?: Prisma.UserHomeworkUpdateWithWhereUniqueWithoutHomeworkInput | Prisma.UserHomeworkUpdateWithWhereUniqueWithoutHomeworkInput[]
  updateMany?: Prisma.UserHomeworkUpdateManyWithWhereWithoutHomeworkInput | Prisma.UserHomeworkUpdateManyWithWhereWithoutHomeworkInput[]
  deleteMany?: Prisma.UserHomeworkScalarWhereInput | Prisma.UserHomeworkScalarWhereInput[]
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type UserHomeworkCreateWithoutUserInput = {
  deleted?: boolean
  checked?: boolean
  score?: number | null
  completedAt?: Date | string
  homework: Prisma.HomeworkCreateNestedOneWithoutUserHomeworksInput
}

export type UserHomeworkUncheckedCreateWithoutUserInput = {
  id?: number
  homework_id: number
  deleted?: boolean
  checked?: boolean
  score?: number | null
  completedAt?: Date | string
}

export type UserHomeworkCreateOrConnectWithoutUserInput = {
  where: Prisma.UserHomeworkWhereUniqueInput
  create: Prisma.XOR<Prisma.UserHomeworkCreateWithoutUserInput, Prisma.UserHomeworkUncheckedCreateWithoutUserInput>
}

export type UserHomeworkCreateManyUserInputEnvelope = {
  data: Prisma.UserHomeworkCreateManyUserInput | Prisma.UserHomeworkCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type UserHomeworkUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.UserHomeworkWhereUniqueInput
  update: Prisma.XOR<Prisma.UserHomeworkUpdateWithoutUserInput, Prisma.UserHomeworkUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.UserHomeworkCreateWithoutUserInput, Prisma.UserHomeworkUncheckedCreateWithoutUserInput>
}

export type UserHomeworkUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.UserHomeworkWhereUniqueInput
  data: Prisma.XOR<Prisma.UserHomeworkUpdateWithoutUserInput, Prisma.UserHomeworkUncheckedUpdateWithoutUserInput>
}

export type UserHomeworkUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.UserHomeworkScalarWhereInput
  data: Prisma.XOR<Prisma.UserHomeworkUpdateManyMutationInput, Prisma.UserHomeworkUncheckedUpdateManyWithoutUserInput>
}

export type UserHomeworkScalarWhereInput = {
  AND?: Prisma.UserHomeworkScalarWhereInput | Prisma.UserHomeworkScalarWhereInput[]
  OR?: Prisma.UserHomeworkScalarWhereInput[]
  NOT?: Prisma.UserHomeworkScalarWhereInput | Prisma.UserHomeworkScalarWhereInput[]
  id?: Prisma.IntFilter<"UserHomework"> | number
  user_id?: Prisma.BigIntFilter<"UserHomework"> | bigint | number
  homework_id?: Prisma.IntFilter<"UserHomework"> | number
  deleted?: Prisma.BoolFilter<"UserHomework"> | boolean
  checked?: Prisma.BoolFilter<"UserHomework"> | boolean
  score?: Prisma.IntNullableFilter<"UserHomework"> | number | null
  completedAt?: Prisma.DateTimeFilter<"UserHomework"> | Date | string
}

export type UserHomeworkCreateWithoutHomeworkInput = {
  deleted?: boolean
  checked?: boolean
  score?: number | null
  completedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutUserHomeworksInput
}

export type UserHomeworkUncheckedCreateWithoutHomeworkInput = {
  id?: number
  user_id: bigint | number
  deleted?: boolean
  checked?: boolean
  score?: number | null
  completedAt?: Date | string
}

export type UserHomeworkCreateOrConnectWithoutHomeworkInput = {
  where: Prisma.UserHomeworkWhereUniqueInput
  create: Prisma.XOR<Prisma.UserHomeworkCreateWithoutHomeworkInput, Prisma.UserHomeworkUncheckedCreateWithoutHomeworkInput>
}

export type UserHomeworkCreateManyHomeworkInputEnvelope = {
  data: Prisma.UserHomeworkCreateManyHomeworkInput | Prisma.UserHomeworkCreateManyHomeworkInput[]
  skipDuplicates?: boolean
}

export type UserHomeworkUpsertWithWhereUniqueWithoutHomeworkInput = {
  where: Prisma.UserHomeworkWhereUniqueInput
  update: Prisma.XOR<Prisma.UserHomeworkUpdateWithoutHomeworkInput, Prisma.UserHomeworkUncheckedUpdateWithoutHomeworkInput>
  create: Prisma.XOR<Prisma.UserHomeworkCreateWithoutHomeworkInput, Prisma.UserHomeworkUncheckedCreateWithoutHomeworkInput>
}

export type UserHomeworkUpdateWithWhereUniqueWithoutHomeworkInput = {
  where: Prisma.UserHomeworkWhereUniqueInput
  data: Prisma.XOR<Prisma.UserHomeworkUpdateWithoutHomeworkInput, Prisma.UserHomeworkUncheckedUpdateWithoutHomeworkInput>
}

export type UserHomeworkUpdateManyWithWhereWithoutHomeworkInput = {
  where: Prisma.UserHomeworkScalarWhereInput
  data: Prisma.XOR<Prisma.UserHomeworkUpdateManyMutationInput, Prisma.UserHomeworkUncheckedUpdateManyWithoutHomeworkInput>
}

export type UserHomeworkCreateManyUserInput = {
  id?: number
  homework_id: number
  deleted?: boolean
  checked?: boolean
  score?: number | null
  completedAt?: Date | string
}

export type UserHomeworkUpdateWithoutUserInput = {
  deleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  checked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  score?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  completedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  homework?: Prisma.HomeworkUpdateOneRequiredWithoutUserHomeworksNestedInput
}

export type UserHomeworkUncheckedUpdateWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  homework_id?: Prisma.IntFieldUpdateOperationsInput | number
  deleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  checked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  score?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  completedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserHomeworkUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  homework_id?: Prisma.IntFieldUpdateOperationsInput | number
  deleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  checked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  score?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  completedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserHomeworkCreateManyHomeworkInput = {
  id?: number
  user_id: bigint | number
  deleted?: boolean
  checked?: boolean
  score?: number | null
  completedAt?: Date | string
}

export type UserHomeworkUpdateWithoutHomeworkInput = {
  deleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  checked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  score?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  completedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutUserHomeworksNestedInput
}

export type UserHomeworkUncheckedUpdateWithoutHomeworkInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  user_id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  deleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  checked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  score?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  completedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserHomeworkUncheckedUpdateManyWithoutHomeworkInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  user_id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  deleted?: Prisma.BoolFieldUpdateOperationsInput | boolean
  checked?: Prisma.BoolFieldUpdateOperationsInput | boolean
  score?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  completedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type UserHomeworkSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_id?: boolean
  homework_id?: boolean
  deleted?: boolean
  checked?: boolean
  score?: boolean
  completedAt?: boolean
  homework?: boolean | Prisma.HomeworkDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userHomework"]>

export type UserHomeworkSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_id?: boolean
  homework_id?: boolean
  deleted?: boolean
  checked?: boolean
  score?: boolean
  completedAt?: boolean
  homework?: boolean | Prisma.HomeworkDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userHomework"]>

export type UserHomeworkSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_id?: boolean
  homework_id?: boolean
  deleted?: boolean
  checked?: boolean
  score?: boolean
  completedAt?: boolean
  homework?: boolean | Prisma.HomeworkDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userHomework"]>

export type UserHomeworkSelectScalar = {
  id?: boolean
  user_id?: boolean
  homework_id?: boolean
  deleted?: boolean
  checked?: boolean
  score?: boolean
  completedAt?: boolean
}

export type UserHomeworkOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "user_id" | "homework_id" | "deleted" | "checked" | "score" | "completedAt", ExtArgs["result"]["userHomework"]>
export type UserHomeworkInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  homework?: boolean | Prisma.HomeworkDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type UserHomeworkIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  homework?: boolean | Prisma.HomeworkDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type UserHomeworkIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  homework?: boolean | Prisma.HomeworkDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $UserHomeworkPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "UserHomework"
  objects: {
    homework: Prisma.$HomeworkPayload<ExtArgs>
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    user_id: bigint
    homework_id: number
    deleted: boolean
    checked: boolean
    score: number | null
    completedAt: Date
  }, ExtArgs["result"]["userHomework"]>
  composites: {}
}

export type UserHomeworkGetPayload<S extends boolean | null | undefined | UserHomeworkDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UserHomeworkPayload, S>

export type UserHomeworkCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UserHomeworkFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UserHomeworkCountAggregateInputType | true
  }

export interface UserHomeworkDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['UserHomework'], meta: { name: 'UserHomework' } }
  /**
   * Find zero or one UserHomework that matches the filter.
   * @param {UserHomeworkFindUniqueArgs} args - Arguments to find a UserHomework
   * @example
   * // Get one UserHomework
   * const userHomework = await prisma.userHomework.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UserHomeworkFindUniqueArgs>(args: Prisma.SelectSubset<T, UserHomeworkFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UserHomeworkClient<runtime.Types.Result.GetResult<Prisma.$UserHomeworkPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one UserHomework that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UserHomeworkFindUniqueOrThrowArgs} args - Arguments to find a UserHomework
   * @example
   * // Get one UserHomework
   * const userHomework = await prisma.userHomework.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UserHomeworkFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UserHomeworkFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserHomeworkClient<runtime.Types.Result.GetResult<Prisma.$UserHomeworkPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserHomework that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserHomeworkFindFirstArgs} args - Arguments to find a UserHomework
   * @example
   * // Get one UserHomework
   * const userHomework = await prisma.userHomework.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UserHomeworkFindFirstArgs>(args?: Prisma.SelectSubset<T, UserHomeworkFindFirstArgs<ExtArgs>>): Prisma.Prisma__UserHomeworkClient<runtime.Types.Result.GetResult<Prisma.$UserHomeworkPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserHomework that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserHomeworkFindFirstOrThrowArgs} args - Arguments to find a UserHomework
   * @example
   * // Get one UserHomework
   * const userHomework = await prisma.userHomework.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UserHomeworkFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UserHomeworkFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserHomeworkClient<runtime.Types.Result.GetResult<Prisma.$UserHomeworkPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more UserHomeworks that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserHomeworkFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all UserHomeworks
   * const userHomeworks = await prisma.userHomework.findMany()
   * 
   * // Get first 10 UserHomeworks
   * const userHomeworks = await prisma.userHomework.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const userHomeworkWithIdOnly = await prisma.userHomework.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends UserHomeworkFindManyArgs>(args?: Prisma.SelectSubset<T, UserHomeworkFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserHomeworkPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a UserHomework.
   * @param {UserHomeworkCreateArgs} args - Arguments to create a UserHomework.
   * @example
   * // Create one UserHomework
   * const UserHomework = await prisma.userHomework.create({
   *   data: {
   *     // ... data to create a UserHomework
   *   }
   * })
   * 
   */
  create<T extends UserHomeworkCreateArgs>(args: Prisma.SelectSubset<T, UserHomeworkCreateArgs<ExtArgs>>): Prisma.Prisma__UserHomeworkClient<runtime.Types.Result.GetResult<Prisma.$UserHomeworkPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many UserHomeworks.
   * @param {UserHomeworkCreateManyArgs} args - Arguments to create many UserHomeworks.
   * @example
   * // Create many UserHomeworks
   * const userHomework = await prisma.userHomework.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UserHomeworkCreateManyArgs>(args?: Prisma.SelectSubset<T, UserHomeworkCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many UserHomeworks and returns the data saved in the database.
   * @param {UserHomeworkCreateManyAndReturnArgs} args - Arguments to create many UserHomeworks.
   * @example
   * // Create many UserHomeworks
   * const userHomework = await prisma.userHomework.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many UserHomeworks and only return the `id`
   * const userHomeworkWithIdOnly = await prisma.userHomework.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UserHomeworkCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UserHomeworkCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserHomeworkPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a UserHomework.
   * @param {UserHomeworkDeleteArgs} args - Arguments to delete one UserHomework.
   * @example
   * // Delete one UserHomework
   * const UserHomework = await prisma.userHomework.delete({
   *   where: {
   *     // ... filter to delete one UserHomework
   *   }
   * })
   * 
   */
  delete<T extends UserHomeworkDeleteArgs>(args: Prisma.SelectSubset<T, UserHomeworkDeleteArgs<ExtArgs>>): Prisma.Prisma__UserHomeworkClient<runtime.Types.Result.GetResult<Prisma.$UserHomeworkPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one UserHomework.
   * @param {UserHomeworkUpdateArgs} args - Arguments to update one UserHomework.
   * @example
   * // Update one UserHomework
   * const userHomework = await prisma.userHomework.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UserHomeworkUpdateArgs>(args: Prisma.SelectSubset<T, UserHomeworkUpdateArgs<ExtArgs>>): Prisma.Prisma__UserHomeworkClient<runtime.Types.Result.GetResult<Prisma.$UserHomeworkPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more UserHomeworks.
   * @param {UserHomeworkDeleteManyArgs} args - Arguments to filter UserHomeworks to delete.
   * @example
   * // Delete a few UserHomeworks
   * const { count } = await prisma.userHomework.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UserHomeworkDeleteManyArgs>(args?: Prisma.SelectSubset<T, UserHomeworkDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserHomeworks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserHomeworkUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many UserHomeworks
   * const userHomework = await prisma.userHomework.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UserHomeworkUpdateManyArgs>(args: Prisma.SelectSubset<T, UserHomeworkUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserHomeworks and returns the data updated in the database.
   * @param {UserHomeworkUpdateManyAndReturnArgs} args - Arguments to update many UserHomeworks.
   * @example
   * // Update many UserHomeworks
   * const userHomework = await prisma.userHomework.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more UserHomeworks and only return the `id`
   * const userHomeworkWithIdOnly = await prisma.userHomework.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UserHomeworkUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UserHomeworkUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserHomeworkPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one UserHomework.
   * @param {UserHomeworkUpsertArgs} args - Arguments to update or create a UserHomework.
   * @example
   * // Update or create a UserHomework
   * const userHomework = await prisma.userHomework.upsert({
   *   create: {
   *     // ... data to create a UserHomework
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the UserHomework we want to update
   *   }
   * })
   */
  upsert<T extends UserHomeworkUpsertArgs>(args: Prisma.SelectSubset<T, UserHomeworkUpsertArgs<ExtArgs>>): Prisma.Prisma__UserHomeworkClient<runtime.Types.Result.GetResult<Prisma.$UserHomeworkPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of UserHomeworks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserHomeworkCountArgs} args - Arguments to filter UserHomeworks to count.
   * @example
   * // Count the number of UserHomeworks
   * const count = await prisma.userHomework.count({
   *   where: {
   *     // ... the filter for the UserHomeworks we want to count
   *   }
   * })
  **/
  count<T extends UserHomeworkCountArgs>(
    args?: Prisma.Subset<T, UserHomeworkCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UserHomeworkCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a UserHomework.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserHomeworkAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UserHomeworkAggregateArgs>(args: Prisma.Subset<T, UserHomeworkAggregateArgs>): Prisma.PrismaPromise<GetUserHomeworkAggregateType<T>>

  /**
   * Group by UserHomework.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserHomeworkGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UserHomeworkGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UserHomeworkGroupByArgs['orderBy'] }
      : { orderBy?: UserHomeworkGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UserHomeworkGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserHomeworkGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the UserHomework model
 */
readonly fields: UserHomeworkFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for UserHomework.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UserHomeworkClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  homework<T extends Prisma.HomeworkDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.HomeworkDefaultArgs<ExtArgs>>): Prisma.Prisma__HomeworkClient<runtime.Types.Result.GetResult<Prisma.$HomeworkPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the UserHomework model
 */
export interface UserHomeworkFieldRefs {
  readonly id: Prisma.FieldRef<"UserHomework", 'Int'>
  readonly user_id: Prisma.FieldRef<"UserHomework", 'BigInt'>
  readonly homework_id: Prisma.FieldRef<"UserHomework", 'Int'>
  readonly deleted: Prisma.FieldRef<"UserHomework", 'Boolean'>
  readonly checked: Prisma.FieldRef<"UserHomework", 'Boolean'>
  readonly score: Prisma.FieldRef<"UserHomework", 'Int'>
  readonly completedAt: Prisma.FieldRef<"UserHomework", 'DateTime'>
}
    

// Custom InputTypes
/**
 * UserHomework findUnique
 */
export type UserHomeworkFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserHomework
   */
  select?: Prisma.UserHomeworkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserHomework
   */
  omit?: Prisma.UserHomeworkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserHomeworkInclude<ExtArgs> | null
  /**
   * Filter, which UserHomework to fetch.
   */
  where: Prisma.UserHomeworkWhereUniqueInput
}

/**
 * UserHomework findUniqueOrThrow
 */
export type UserHomeworkFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserHomework
   */
  select?: Prisma.UserHomeworkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserHomework
   */
  omit?: Prisma.UserHomeworkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserHomeworkInclude<ExtArgs> | null
  /**
   * Filter, which UserHomework to fetch.
   */
  where: Prisma.UserHomeworkWhereUniqueInput
}

/**
 * UserHomework findFirst
 */
export type UserHomeworkFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserHomework
   */
  select?: Prisma.UserHomeworkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserHomework
   */
  omit?: Prisma.UserHomeworkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserHomeworkInclude<ExtArgs> | null
  /**
   * Filter, which UserHomework to fetch.
   */
  where?: Prisma.UserHomeworkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserHomeworks to fetch.
   */
  orderBy?: Prisma.UserHomeworkOrderByWithRelationInput | Prisma.UserHomeworkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserHomeworks.
   */
  cursor?: Prisma.UserHomeworkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserHomeworks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserHomeworks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserHomeworks.
   */
  distinct?: Prisma.UserHomeworkScalarFieldEnum | Prisma.UserHomeworkScalarFieldEnum[]
}

/**
 * UserHomework findFirstOrThrow
 */
export type UserHomeworkFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserHomework
   */
  select?: Prisma.UserHomeworkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserHomework
   */
  omit?: Prisma.UserHomeworkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserHomeworkInclude<ExtArgs> | null
  /**
   * Filter, which UserHomework to fetch.
   */
  where?: Prisma.UserHomeworkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserHomeworks to fetch.
   */
  orderBy?: Prisma.UserHomeworkOrderByWithRelationInput | Prisma.UserHomeworkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserHomeworks.
   */
  cursor?: Prisma.UserHomeworkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserHomeworks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserHomeworks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserHomeworks.
   */
  distinct?: Prisma.UserHomeworkScalarFieldEnum | Prisma.UserHomeworkScalarFieldEnum[]
}

/**
 * UserHomework findMany
 */
export type UserHomeworkFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserHomework
   */
  select?: Prisma.UserHomeworkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserHomework
   */
  omit?: Prisma.UserHomeworkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserHomeworkInclude<ExtArgs> | null
  /**
   * Filter, which UserHomeworks to fetch.
   */
  where?: Prisma.UserHomeworkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserHomeworks to fetch.
   */
  orderBy?: Prisma.UserHomeworkOrderByWithRelationInput | Prisma.UserHomeworkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing UserHomeworks.
   */
  cursor?: Prisma.UserHomeworkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserHomeworks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserHomeworks.
   */
  skip?: number
  distinct?: Prisma.UserHomeworkScalarFieldEnum | Prisma.UserHomeworkScalarFieldEnum[]
}

/**
 * UserHomework create
 */
export type UserHomeworkCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserHomework
   */
  select?: Prisma.UserHomeworkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserHomework
   */
  omit?: Prisma.UserHomeworkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserHomeworkInclude<ExtArgs> | null
  /**
   * The data needed to create a UserHomework.
   */
  data: Prisma.XOR<Prisma.UserHomeworkCreateInput, Prisma.UserHomeworkUncheckedCreateInput>
}

/**
 * UserHomework createMany
 */
export type UserHomeworkCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many UserHomeworks.
   */
  data: Prisma.UserHomeworkCreateManyInput | Prisma.UserHomeworkCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * UserHomework createManyAndReturn
 */
export type UserHomeworkCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserHomework
   */
  select?: Prisma.UserHomeworkSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserHomework
   */
  omit?: Prisma.UserHomeworkOmit<ExtArgs> | null
  /**
   * The data used to create many UserHomeworks.
   */
  data: Prisma.UserHomeworkCreateManyInput | Prisma.UserHomeworkCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserHomeworkIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * UserHomework update
 */
export type UserHomeworkUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserHomework
   */
  select?: Prisma.UserHomeworkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserHomework
   */
  omit?: Prisma.UserHomeworkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserHomeworkInclude<ExtArgs> | null
  /**
   * The data needed to update a UserHomework.
   */
  data: Prisma.XOR<Prisma.UserHomeworkUpdateInput, Prisma.UserHomeworkUncheckedUpdateInput>
  /**
   * Choose, which UserHomework to update.
   */
  where: Prisma.UserHomeworkWhereUniqueInput
}

/**
 * UserHomework updateMany
 */
export type UserHomeworkUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update UserHomeworks.
   */
  data: Prisma.XOR<Prisma.UserHomeworkUpdateManyMutationInput, Prisma.UserHomeworkUncheckedUpdateManyInput>
  /**
   * Filter which UserHomeworks to update
   */
  where?: Prisma.UserHomeworkWhereInput
  /**
   * Limit how many UserHomeworks to update.
   */
  limit?: number
}

/**
 * UserHomework updateManyAndReturn
 */
export type UserHomeworkUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserHomework
   */
  select?: Prisma.UserHomeworkSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserHomework
   */
  omit?: Prisma.UserHomeworkOmit<ExtArgs> | null
  /**
   * The data used to update UserHomeworks.
   */
  data: Prisma.XOR<Prisma.UserHomeworkUpdateManyMutationInput, Prisma.UserHomeworkUncheckedUpdateManyInput>
  /**
   * Filter which UserHomeworks to update
   */
  where?: Prisma.UserHomeworkWhereInput
  /**
   * Limit how many UserHomeworks to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserHomeworkIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * UserHomework upsert
 */
export type UserHomeworkUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserHomework
   */
  select?: Prisma.UserHomeworkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserHomework
   */
  omit?: Prisma.UserHomeworkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserHomeworkInclude<ExtArgs> | null
  /**
   * The filter to search for the UserHomework to update in case it exists.
   */
  where: Prisma.UserHomeworkWhereUniqueInput
  /**
   * In case the UserHomework found by the `where` argument doesn't exist, create a new UserHomework with this data.
   */
  create: Prisma.XOR<Prisma.UserHomeworkCreateInput, Prisma.UserHomeworkUncheckedCreateInput>
  /**
   * In case the UserHomework was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UserHomeworkUpdateInput, Prisma.UserHomeworkUncheckedUpdateInput>
}

/**
 * UserHomework delete
 */
export type UserHomeworkDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserHomework
   */
  select?: Prisma.UserHomeworkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserHomework
   */
  omit?: Prisma.UserHomeworkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserHomeworkInclude<ExtArgs> | null
  /**
   * Filter which UserHomework to delete.
   */
  where: Prisma.UserHomeworkWhereUniqueInput
}

/**
 * UserHomework deleteMany
 */
export type UserHomeworkDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserHomeworks to delete
   */
  where?: Prisma.UserHomeworkWhereInput
  /**
   * Limit how many UserHomeworks to delete.
   */
  limit?: number
}

/**
 * UserHomework without action
 */
export type UserHomeworkDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserHomework
   */
  select?: Prisma.UserHomeworkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserHomework
   */
  omit?: Prisma.UserHomeworkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserHomeworkInclude<ExtArgs> | null
}
