
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `User` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model User
 * 
 */
export type UserModel = runtime.Types.Result.DefaultSelection<Prisma.$UserPayload>

export type AggregateUser = {
  _count: UserCountAggregateOutputType | null
  _avg: UserAvgAggregateOutputType | null
  _sum: UserSumAggregateOutputType | null
  _min: UserMinAggregateOutputType | null
  _max: UserMaxAggregateOutputType | null
}

export type UserAvgAggregateOutputType = {
  id: number | null
  overdue_tasks: number | null
  score: number | null
  studyGroupId: number | null
}

export type UserSumAggregateOutputType = {
  id: bigint | null
  overdue_tasks: number | null
  score: number | null
  studyGroupId: number | null
}

export type UserMinAggregateOutputType = {
  id: bigint | null
  username: string | null
  yandex_email: string | null
  verified: boolean | null
  name: string | null
  last_name: string | null
  patronymic: string | null
  overdue_tasks: number | null
  createdAt: Date | null
  role: $Enums.Role | null
  score: number | null
  studyGroupId: number | null
}

export type UserMaxAggregateOutputType = {
  id: bigint | null
  username: string | null
  yandex_email: string | null
  verified: boolean | null
  name: string | null
  last_name: string | null
  patronymic: string | null
  overdue_tasks: number | null
  createdAt: Date | null
  role: $Enums.Role | null
  score: number | null
  studyGroupId: number | null
}

export type UserCountAggregateOutputType = {
  id: number
  username: number
  yandex_email: number
  verified: number
  name: number
  last_name: number
  patronymic: number
  overdue_tasks: number
  createdAt: number
  role: number
  score: number
  studyGroupId: number
  _all: number
}


export type UserAvgAggregateInputType = {
  id?: true
  overdue_tasks?: true
  score?: true
  studyGroupId?: true
}

export type UserSumAggregateInputType = {
  id?: true
  overdue_tasks?: true
  score?: true
  studyGroupId?: true
}

export type UserMinAggregateInputType = {
  id?: true
  username?: true
  yandex_email?: true
  verified?: true
  name?: true
  last_name?: true
  patronymic?: true
  overdue_tasks?: true
  createdAt?: true
  role?: true
  score?: true
  studyGroupId?: true
}

export type UserMaxAggregateInputType = {
  id?: true
  username?: true
  yandex_email?: true
  verified?: true
  name?: true
  last_name?: true
  patronymic?: true
  overdue_tasks?: true
  createdAt?: true
  role?: true
  score?: true
  studyGroupId?: true
}

export type UserCountAggregateInputType = {
  id?: true
  username?: true
  yandex_email?: true
  verified?: true
  name?: true
  last_name?: true
  patronymic?: true
  overdue_tasks?: true
  createdAt?: true
  role?: true
  score?: true
  studyGroupId?: true
  _all?: true
}

export type UserAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which User to aggregate.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Users
  **/
  _count?: true | UserCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: UserAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: UserSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UserMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UserMaxAggregateInputType
}

export type GetUserAggregateType<T extends UserAggregateArgs> = {
      [P in keyof T & keyof AggregateUser]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUser[P]>
    : Prisma.GetScalarType<T[P], AggregateUser[P]>
}




export type UserGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserWhereInput
  orderBy?: Prisma.UserOrderByWithAggregationInput | Prisma.UserOrderByWithAggregationInput[]
  by: Prisma.UserScalarFieldEnum[] | Prisma.UserScalarFieldEnum
  having?: Prisma.UserScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UserCountAggregateInputType | true
  _avg?: UserAvgAggregateInputType
  _sum?: UserSumAggregateInputType
  _min?: UserMinAggregateInputType
  _max?: UserMaxAggregateInputType
}

export type UserGroupByOutputType = {
  id: bigint
  username: string | null
  yandex_email: string
  verified: boolean
  name: string
  last_name: string
  patronymic: string
  overdue_tasks: number
  createdAt: Date
  role: $Enums.Role
  score: number
  studyGroupId: number
  _count: UserCountAggregateOutputType | null
  _avg: UserAvgAggregateOutputType | null
  _sum: UserSumAggregateOutputType | null
  _min: UserMinAggregateOutputType | null
  _max: UserMaxAggregateOutputType | null
}

type GetUserGroupByPayload<T extends UserGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UserGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UserGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UserGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UserGroupByOutputType[P]>
      }
    >
  >



export type UserWhereInput = {
  AND?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  OR?: Prisma.UserWhereInput[]
  NOT?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  id?: Prisma.BigIntFilter<"User"> | bigint | number
  username?: Prisma.StringNullableFilter<"User"> | string | null
  yandex_email?: Prisma.StringFilter<"User"> | string
  verified?: Prisma.BoolFilter<"User"> | boolean
  name?: Prisma.StringFilter<"User"> | string
  last_name?: Prisma.StringFilter<"User"> | string
  patronymic?: Prisma.StringFilter<"User"> | string
  overdue_tasks?: Prisma.IntFilter<"User"> | number
  createdAt?: Prisma.DateTimeFilter<"User"> | Date | string
  role?: Prisma.EnumRoleFilter<"User"> | $Enums.Role
  score?: Prisma.IntFilter<"User"> | number
  studyGroupId?: Prisma.IntFilter<"User"> | number
  request?: Prisma.XOR<Prisma.RequestNullableScalarRelationFilter, Prisma.RequestWhereInput> | null
  StudyGroup?: Prisma.XOR<Prisma.StudyGroupScalarRelationFilter, Prisma.StudyGroupWhereInput>
  userHomeworks?: Prisma.UserHomeworkListRelationFilter
  studyGroupRelations?: Prisma.StudyGroupRelationListRelationFilter
}

export type UserOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  username?: Prisma.SortOrderInput | Prisma.SortOrder
  yandex_email?: Prisma.SortOrder
  verified?: Prisma.SortOrder
  name?: Prisma.SortOrder
  last_name?: Prisma.SortOrder
  patronymic?: Prisma.SortOrder
  overdue_tasks?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  role?: Prisma.SortOrder
  score?: Prisma.SortOrder
  studyGroupId?: Prisma.SortOrder
  request?: Prisma.RequestOrderByWithRelationInput
  StudyGroup?: Prisma.StudyGroupOrderByWithRelationInput
  userHomeworks?: Prisma.UserHomeworkOrderByRelationAggregateInput
  studyGroupRelations?: Prisma.StudyGroupRelationOrderByRelationAggregateInput
}

export type UserWhereUniqueInput = Prisma.AtLeast<{
  id?: bigint | number
  username?: string
  AND?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  OR?: Prisma.UserWhereInput[]
  NOT?: Prisma.UserWhereInput | Prisma.UserWhereInput[]
  yandex_email?: Prisma.StringFilter<"User"> | string
  verified?: Prisma.BoolFilter<"User"> | boolean
  name?: Prisma.StringFilter<"User"> | string
  last_name?: Prisma.StringFilter<"User"> | string
  patronymic?: Prisma.StringFilter<"User"> | string
  overdue_tasks?: Prisma.IntFilter<"User"> | number
  createdAt?: Prisma.DateTimeFilter<"User"> | Date | string
  role?: Prisma.EnumRoleFilter<"User"> | $Enums.Role
  score?: Prisma.IntFilter<"User"> | number
  studyGroupId?: Prisma.IntFilter<"User"> | number
  request?: Prisma.XOR<Prisma.RequestNullableScalarRelationFilter, Prisma.RequestWhereInput> | null
  StudyGroup?: Prisma.XOR<Prisma.StudyGroupScalarRelationFilter, Prisma.StudyGroupWhereInput>
  userHomeworks?: Prisma.UserHomeworkListRelationFilter
  studyGroupRelations?: Prisma.StudyGroupRelationListRelationFilter
}, "id" | "username">

export type UserOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  username?: Prisma.SortOrderInput | Prisma.SortOrder
  yandex_email?: Prisma.SortOrder
  verified?: Prisma.SortOrder
  name?: Prisma.SortOrder
  last_name?: Prisma.SortOrder
  patronymic?: Prisma.SortOrder
  overdue_tasks?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  role?: Prisma.SortOrder
  score?: Prisma.SortOrder
  studyGroupId?: Prisma.SortOrder
  _count?: Prisma.UserCountOrderByAggregateInput
  _avg?: Prisma.UserAvgOrderByAggregateInput
  _max?: Prisma.UserMaxOrderByAggregateInput
  _min?: Prisma.UserMinOrderByAggregateInput
  _sum?: Prisma.UserSumOrderByAggregateInput
}

export type UserScalarWhereWithAggregatesInput = {
  AND?: Prisma.UserScalarWhereWithAggregatesInput | Prisma.UserScalarWhereWithAggregatesInput[]
  OR?: Prisma.UserScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UserScalarWhereWithAggregatesInput | Prisma.UserScalarWhereWithAggregatesInput[]
  id?: Prisma.BigIntWithAggregatesFilter<"User"> | bigint | number
  username?: Prisma.StringNullableWithAggregatesFilter<"User"> | string | null
  yandex_email?: Prisma.StringWithAggregatesFilter<"User"> | string
  verified?: Prisma.BoolWithAggregatesFilter<"User"> | boolean
  name?: Prisma.StringWithAggregatesFilter<"User"> | string
  last_name?: Prisma.StringWithAggregatesFilter<"User"> | string
  patronymic?: Prisma.StringWithAggregatesFilter<"User"> | string
  overdue_tasks?: Prisma.IntWithAggregatesFilter<"User"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"User"> | Date | string
  role?: Prisma.EnumRoleWithAggregatesFilter<"User"> | $Enums.Role
  score?: Prisma.IntWithAggregatesFilter<"User"> | number
  studyGroupId?: Prisma.IntWithAggregatesFilter<"User"> | number
}

export type UserCreateInput = {
  id: bigint | number
  username?: string | null
  yandex_email: string
  verified?: boolean
  name: string
  last_name: string
  patronymic: string
  overdue_tasks?: number
  createdAt?: Date | string
  role?: $Enums.Role
  score?: number
  request?: Prisma.RequestCreateNestedOneWithoutUserInput
  StudyGroup: Prisma.StudyGroupCreateNestedOneWithoutUserInput
  userHomeworks?: Prisma.UserHomeworkCreateNestedManyWithoutUserInput
  studyGroupRelations?: Prisma.StudyGroupRelationCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateInput = {
  id: bigint | number
  username?: string | null
  yandex_email: string
  verified?: boolean
  name: string
  last_name: string
  patronymic: string
  overdue_tasks?: number
  createdAt?: Date | string
  role?: $Enums.Role
  score?: number
  studyGroupId: number
  request?: Prisma.RequestUncheckedCreateNestedOneWithoutUserInput
  userHomeworks?: Prisma.UserHomeworkUncheckedCreateNestedManyWithoutUserInput
  studyGroupRelations?: Prisma.StudyGroupRelationUncheckedCreateNestedManyWithoutUserInput
}

export type UserUpdateInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  yandex_email?: Prisma.StringFieldUpdateOperationsInput | string
  verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  name?: Prisma.StringFieldUpdateOperationsInput | string
  last_name?: Prisma.StringFieldUpdateOperationsInput | string
  patronymic?: Prisma.StringFieldUpdateOperationsInput | string
  overdue_tasks?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  score?: Prisma.IntFieldUpdateOperationsInput | number
  request?: Prisma.RequestUpdateOneWithoutUserNestedInput
  StudyGroup?: Prisma.StudyGroupUpdateOneRequiredWithoutUserNestedInput
  userHomeworks?: Prisma.UserHomeworkUpdateManyWithoutUserNestedInput
  studyGroupRelations?: Prisma.StudyGroupRelationUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  yandex_email?: Prisma.StringFieldUpdateOperationsInput | string
  verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  name?: Prisma.StringFieldUpdateOperationsInput | string
  last_name?: Prisma.StringFieldUpdateOperationsInput | string
  patronymic?: Prisma.StringFieldUpdateOperationsInput | string
  overdue_tasks?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  score?: Prisma.IntFieldUpdateOperationsInput | number
  studyGroupId?: Prisma.IntFieldUpdateOperationsInput | number
  request?: Prisma.RequestUncheckedUpdateOneWithoutUserNestedInput
  userHomeworks?: Prisma.UserHomeworkUncheckedUpdateManyWithoutUserNestedInput
  studyGroupRelations?: Prisma.StudyGroupRelationUncheckedUpdateManyWithoutUserNestedInput
}

export type UserCreateManyInput = {
  id: bigint | number
  username?: string | null
  yandex_email: string
  verified?: boolean
  name: string
  last_name: string
  patronymic: string
  overdue_tasks?: number
  createdAt?: Date | string
  role?: $Enums.Role
  score?: number
  studyGroupId: number
}

export type UserUpdateManyMutationInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  yandex_email?: Prisma.StringFieldUpdateOperationsInput | string
  verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  name?: Prisma.StringFieldUpdateOperationsInput | string
  last_name?: Prisma.StringFieldUpdateOperationsInput | string
  patronymic?: Prisma.StringFieldUpdateOperationsInput | string
  overdue_tasks?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  score?: Prisma.IntFieldUpdateOperationsInput | number
}

export type UserUncheckedUpdateManyInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  yandex_email?: Prisma.StringFieldUpdateOperationsInput | string
  verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  name?: Prisma.StringFieldUpdateOperationsInput | string
  last_name?: Prisma.StringFieldUpdateOperationsInput | string
  patronymic?: Prisma.StringFieldUpdateOperationsInput | string
  overdue_tasks?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  score?: Prisma.IntFieldUpdateOperationsInput | number
  studyGroupId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type UserCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  username?: Prisma.SortOrder
  yandex_email?: Prisma.SortOrder
  verified?: Prisma.SortOrder
  name?: Prisma.SortOrder
  last_name?: Prisma.SortOrder
  patronymic?: Prisma.SortOrder
  overdue_tasks?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  role?: Prisma.SortOrder
  score?: Prisma.SortOrder
  studyGroupId?: Prisma.SortOrder
}

export type UserAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  overdue_tasks?: Prisma.SortOrder
  score?: Prisma.SortOrder
  studyGroupId?: Prisma.SortOrder
}

export type UserMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  username?: Prisma.SortOrder
  yandex_email?: Prisma.SortOrder
  verified?: Prisma.SortOrder
  name?: Prisma.SortOrder
  last_name?: Prisma.SortOrder
  patronymic?: Prisma.SortOrder
  overdue_tasks?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  role?: Prisma.SortOrder
  score?: Prisma.SortOrder
  studyGroupId?: Prisma.SortOrder
}

export type UserMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  username?: Prisma.SortOrder
  yandex_email?: Prisma.SortOrder
  verified?: Prisma.SortOrder
  name?: Prisma.SortOrder
  last_name?: Prisma.SortOrder
  patronymic?: Prisma.SortOrder
  overdue_tasks?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  role?: Prisma.SortOrder
  score?: Prisma.SortOrder
  studyGroupId?: Prisma.SortOrder
}

export type UserSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  overdue_tasks?: Prisma.SortOrder
  score?: Prisma.SortOrder
  studyGroupId?: Prisma.SortOrder
}

export type UserScalarRelationFilter = {
  is?: Prisma.UserWhereInput
  isNot?: Prisma.UserWhereInput
}

export type UserListRelationFilter = {
  every?: Prisma.UserWhereInput
  some?: Prisma.UserWhereInput
  none?: Prisma.UserWhereInput
}

export type UserOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type BigIntFieldUpdateOperationsInput = {
  set?: bigint | number
  increment?: bigint | number
  decrement?: bigint | number
  multiply?: bigint | number
  divide?: bigint | number
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type EnumRoleFieldUpdateOperationsInput = {
  set?: $Enums.Role
}

export type UserCreateNestedOneWithoutRequestInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutRequestInput, Prisma.UserUncheckedCreateWithoutRequestInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutRequestInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutRequestNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutRequestInput, Prisma.UserUncheckedCreateWithoutRequestInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutRequestInput
  upsert?: Prisma.UserUpsertWithoutRequestInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutRequestInput, Prisma.UserUpdateWithoutRequestInput>, Prisma.UserUncheckedUpdateWithoutRequestInput>
}

export type UserCreateNestedOneWithoutUserHomeworksInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutUserHomeworksInput, Prisma.UserUncheckedCreateWithoutUserHomeworksInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutUserHomeworksInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutUserHomeworksNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutUserHomeworksInput, Prisma.UserUncheckedCreateWithoutUserHomeworksInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutUserHomeworksInput
  upsert?: Prisma.UserUpsertWithoutUserHomeworksInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutUserHomeworksInput, Prisma.UserUpdateWithoutUserHomeworksInput>, Prisma.UserUncheckedUpdateWithoutUserHomeworksInput>
}

export type UserCreateNestedOneWithoutStudyGroupRelationsInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutStudyGroupRelationsInput, Prisma.UserUncheckedCreateWithoutStudyGroupRelationsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutStudyGroupRelationsInput
  connect?: Prisma.UserWhereUniqueInput
}

export type UserUpdateOneRequiredWithoutStudyGroupRelationsNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutStudyGroupRelationsInput, Prisma.UserUncheckedCreateWithoutStudyGroupRelationsInput>
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutStudyGroupRelationsInput
  upsert?: Prisma.UserUpsertWithoutStudyGroupRelationsInput
  connect?: Prisma.UserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UserUpdateToOneWithWhereWithoutStudyGroupRelationsInput, Prisma.UserUpdateWithoutStudyGroupRelationsInput>, Prisma.UserUncheckedUpdateWithoutStudyGroupRelationsInput>
}

export type UserCreateNestedManyWithoutStudyGroupInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutStudyGroupInput, Prisma.UserUncheckedCreateWithoutStudyGroupInput> | Prisma.UserCreateWithoutStudyGroupInput[] | Prisma.UserUncheckedCreateWithoutStudyGroupInput[]
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutStudyGroupInput | Prisma.UserCreateOrConnectWithoutStudyGroupInput[]
  createMany?: Prisma.UserCreateManyStudyGroupInputEnvelope
  connect?: Prisma.UserWhereUniqueInput | Prisma.UserWhereUniqueInput[]
}

export type UserUncheckedCreateNestedManyWithoutStudyGroupInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutStudyGroupInput, Prisma.UserUncheckedCreateWithoutStudyGroupInput> | Prisma.UserCreateWithoutStudyGroupInput[] | Prisma.UserUncheckedCreateWithoutStudyGroupInput[]
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutStudyGroupInput | Prisma.UserCreateOrConnectWithoutStudyGroupInput[]
  createMany?: Prisma.UserCreateManyStudyGroupInputEnvelope
  connect?: Prisma.UserWhereUniqueInput | Prisma.UserWhereUniqueInput[]
}

export type UserUpdateManyWithoutStudyGroupNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutStudyGroupInput, Prisma.UserUncheckedCreateWithoutStudyGroupInput> | Prisma.UserCreateWithoutStudyGroupInput[] | Prisma.UserUncheckedCreateWithoutStudyGroupInput[]
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutStudyGroupInput | Prisma.UserCreateOrConnectWithoutStudyGroupInput[]
  upsert?: Prisma.UserUpsertWithWhereUniqueWithoutStudyGroupInput | Prisma.UserUpsertWithWhereUniqueWithoutStudyGroupInput[]
  createMany?: Prisma.UserCreateManyStudyGroupInputEnvelope
  set?: Prisma.UserWhereUniqueInput | Prisma.UserWhereUniqueInput[]
  disconnect?: Prisma.UserWhereUniqueInput | Prisma.UserWhereUniqueInput[]
  delete?: Prisma.UserWhereUniqueInput | Prisma.UserWhereUniqueInput[]
  connect?: Prisma.UserWhereUniqueInput | Prisma.UserWhereUniqueInput[]
  update?: Prisma.UserUpdateWithWhereUniqueWithoutStudyGroupInput | Prisma.UserUpdateWithWhereUniqueWithoutStudyGroupInput[]
  updateMany?: Prisma.UserUpdateManyWithWhereWithoutStudyGroupInput | Prisma.UserUpdateManyWithWhereWithoutStudyGroupInput[]
  deleteMany?: Prisma.UserScalarWhereInput | Prisma.UserScalarWhereInput[]
}

export type UserUncheckedUpdateManyWithoutStudyGroupNestedInput = {
  create?: Prisma.XOR<Prisma.UserCreateWithoutStudyGroupInput, Prisma.UserUncheckedCreateWithoutStudyGroupInput> | Prisma.UserCreateWithoutStudyGroupInput[] | Prisma.UserUncheckedCreateWithoutStudyGroupInput[]
  connectOrCreate?: Prisma.UserCreateOrConnectWithoutStudyGroupInput | Prisma.UserCreateOrConnectWithoutStudyGroupInput[]
  upsert?: Prisma.UserUpsertWithWhereUniqueWithoutStudyGroupInput | Prisma.UserUpsertWithWhereUniqueWithoutStudyGroupInput[]
  createMany?: Prisma.UserCreateManyStudyGroupInputEnvelope
  set?: Prisma.UserWhereUniqueInput | Prisma.UserWhereUniqueInput[]
  disconnect?: Prisma.UserWhereUniqueInput | Prisma.UserWhereUniqueInput[]
  delete?: Prisma.UserWhereUniqueInput | Prisma.UserWhereUniqueInput[]
  connect?: Prisma.UserWhereUniqueInput | Prisma.UserWhereUniqueInput[]
  update?: Prisma.UserUpdateWithWhereUniqueWithoutStudyGroupInput | Prisma.UserUpdateWithWhereUniqueWithoutStudyGroupInput[]
  updateMany?: Prisma.UserUpdateManyWithWhereWithoutStudyGroupInput | Prisma.UserUpdateManyWithWhereWithoutStudyGroupInput[]
  deleteMany?: Prisma.UserScalarWhereInput | Prisma.UserScalarWhereInput[]
}

export type UserCreateWithoutRequestInput = {
  id: bigint | number
  username?: string | null
  yandex_email: string
  verified?: boolean
  name: string
  last_name: string
  patronymic: string
  overdue_tasks?: number
  createdAt?: Date | string
  role?: $Enums.Role
  score?: number
  StudyGroup: Prisma.StudyGroupCreateNestedOneWithoutUserInput
  userHomeworks?: Prisma.UserHomeworkCreateNestedManyWithoutUserInput
  studyGroupRelations?: Prisma.StudyGroupRelationCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateWithoutRequestInput = {
  id: bigint | number
  username?: string | null
  yandex_email: string
  verified?: boolean
  name: string
  last_name: string
  patronymic: string
  overdue_tasks?: number
  createdAt?: Date | string
  role?: $Enums.Role
  score?: number
  studyGroupId: number
  userHomeworks?: Prisma.UserHomeworkUncheckedCreateNestedManyWithoutUserInput
  studyGroupRelations?: Prisma.StudyGroupRelationUncheckedCreateNestedManyWithoutUserInput
}

export type UserCreateOrConnectWithoutRequestInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutRequestInput, Prisma.UserUncheckedCreateWithoutRequestInput>
}

export type UserUpsertWithoutRequestInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutRequestInput, Prisma.UserUncheckedUpdateWithoutRequestInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutRequestInput, Prisma.UserUncheckedCreateWithoutRequestInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutRequestInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutRequestInput, Prisma.UserUncheckedUpdateWithoutRequestInput>
}

export type UserUpdateWithoutRequestInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  yandex_email?: Prisma.StringFieldUpdateOperationsInput | string
  verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  name?: Prisma.StringFieldUpdateOperationsInput | string
  last_name?: Prisma.StringFieldUpdateOperationsInput | string
  patronymic?: Prisma.StringFieldUpdateOperationsInput | string
  overdue_tasks?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  score?: Prisma.IntFieldUpdateOperationsInput | number
  StudyGroup?: Prisma.StudyGroupUpdateOneRequiredWithoutUserNestedInput
  userHomeworks?: Prisma.UserHomeworkUpdateManyWithoutUserNestedInput
  studyGroupRelations?: Prisma.StudyGroupRelationUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateWithoutRequestInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  yandex_email?: Prisma.StringFieldUpdateOperationsInput | string
  verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  name?: Prisma.StringFieldUpdateOperationsInput | string
  last_name?: Prisma.StringFieldUpdateOperationsInput | string
  patronymic?: Prisma.StringFieldUpdateOperationsInput | string
  overdue_tasks?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  score?: Prisma.IntFieldUpdateOperationsInput | number
  studyGroupId?: Prisma.IntFieldUpdateOperationsInput | number
  userHomeworks?: Prisma.UserHomeworkUncheckedUpdateManyWithoutUserNestedInput
  studyGroupRelations?: Prisma.StudyGroupRelationUncheckedUpdateManyWithoutUserNestedInput
}

export type UserCreateWithoutUserHomeworksInput = {
  id: bigint | number
  username?: string | null
  yandex_email: string
  verified?: boolean
  name: string
  last_name: string
  patronymic: string
  overdue_tasks?: number
  createdAt?: Date | string
  role?: $Enums.Role
  score?: number
  request?: Prisma.RequestCreateNestedOneWithoutUserInput
  StudyGroup: Prisma.StudyGroupCreateNestedOneWithoutUserInput
  studyGroupRelations?: Prisma.StudyGroupRelationCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateWithoutUserHomeworksInput = {
  id: bigint | number
  username?: string | null
  yandex_email: string
  verified?: boolean
  name: string
  last_name: string
  patronymic: string
  overdue_tasks?: number
  createdAt?: Date | string
  role?: $Enums.Role
  score?: number
  studyGroupId: number
  request?: Prisma.RequestUncheckedCreateNestedOneWithoutUserInput
  studyGroupRelations?: Prisma.StudyGroupRelationUncheckedCreateNestedManyWithoutUserInput
}

export type UserCreateOrConnectWithoutUserHomeworksInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutUserHomeworksInput, Prisma.UserUncheckedCreateWithoutUserHomeworksInput>
}

export type UserUpsertWithoutUserHomeworksInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutUserHomeworksInput, Prisma.UserUncheckedUpdateWithoutUserHomeworksInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutUserHomeworksInput, Prisma.UserUncheckedCreateWithoutUserHomeworksInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutUserHomeworksInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutUserHomeworksInput, Prisma.UserUncheckedUpdateWithoutUserHomeworksInput>
}

export type UserUpdateWithoutUserHomeworksInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  yandex_email?: Prisma.StringFieldUpdateOperationsInput | string
  verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  name?: Prisma.StringFieldUpdateOperationsInput | string
  last_name?: Prisma.StringFieldUpdateOperationsInput | string
  patronymic?: Prisma.StringFieldUpdateOperationsInput | string
  overdue_tasks?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  score?: Prisma.IntFieldUpdateOperationsInput | number
  request?: Prisma.RequestUpdateOneWithoutUserNestedInput
  StudyGroup?: Prisma.StudyGroupUpdateOneRequiredWithoutUserNestedInput
  studyGroupRelations?: Prisma.StudyGroupRelationUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateWithoutUserHomeworksInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  yandex_email?: Prisma.StringFieldUpdateOperationsInput | string
  verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  name?: Prisma.StringFieldUpdateOperationsInput | string
  last_name?: Prisma.StringFieldUpdateOperationsInput | string
  patronymic?: Prisma.StringFieldUpdateOperationsInput | string
  overdue_tasks?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  score?: Prisma.IntFieldUpdateOperationsInput | number
  studyGroupId?: Prisma.IntFieldUpdateOperationsInput | number
  request?: Prisma.RequestUncheckedUpdateOneWithoutUserNestedInput
  studyGroupRelations?: Prisma.StudyGroupRelationUncheckedUpdateManyWithoutUserNestedInput
}

export type UserCreateWithoutStudyGroupRelationsInput = {
  id: bigint | number
  username?: string | null
  yandex_email: string
  verified?: boolean
  name: string
  last_name: string
  patronymic: string
  overdue_tasks?: number
  createdAt?: Date | string
  role?: $Enums.Role
  score?: number
  request?: Prisma.RequestCreateNestedOneWithoutUserInput
  StudyGroup: Prisma.StudyGroupCreateNestedOneWithoutUserInput
  userHomeworks?: Prisma.UserHomeworkCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateWithoutStudyGroupRelationsInput = {
  id: bigint | number
  username?: string | null
  yandex_email: string
  verified?: boolean
  name: string
  last_name: string
  patronymic: string
  overdue_tasks?: number
  createdAt?: Date | string
  role?: $Enums.Role
  score?: number
  studyGroupId: number
  request?: Prisma.RequestUncheckedCreateNestedOneWithoutUserInput
  userHomeworks?: Prisma.UserHomeworkUncheckedCreateNestedManyWithoutUserInput
}

export type UserCreateOrConnectWithoutStudyGroupRelationsInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutStudyGroupRelationsInput, Prisma.UserUncheckedCreateWithoutStudyGroupRelationsInput>
}

export type UserUpsertWithoutStudyGroupRelationsInput = {
  update: Prisma.XOR<Prisma.UserUpdateWithoutStudyGroupRelationsInput, Prisma.UserUncheckedUpdateWithoutStudyGroupRelationsInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutStudyGroupRelationsInput, Prisma.UserUncheckedCreateWithoutStudyGroupRelationsInput>
  where?: Prisma.UserWhereInput
}

export type UserUpdateToOneWithWhereWithoutStudyGroupRelationsInput = {
  where?: Prisma.UserWhereInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutStudyGroupRelationsInput, Prisma.UserUncheckedUpdateWithoutStudyGroupRelationsInput>
}

export type UserUpdateWithoutStudyGroupRelationsInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  yandex_email?: Prisma.StringFieldUpdateOperationsInput | string
  verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  name?: Prisma.StringFieldUpdateOperationsInput | string
  last_name?: Prisma.StringFieldUpdateOperationsInput | string
  patronymic?: Prisma.StringFieldUpdateOperationsInput | string
  overdue_tasks?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  score?: Prisma.IntFieldUpdateOperationsInput | number
  request?: Prisma.RequestUpdateOneWithoutUserNestedInput
  StudyGroup?: Prisma.StudyGroupUpdateOneRequiredWithoutUserNestedInput
  userHomeworks?: Prisma.UserHomeworkUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateWithoutStudyGroupRelationsInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  yandex_email?: Prisma.StringFieldUpdateOperationsInput | string
  verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  name?: Prisma.StringFieldUpdateOperationsInput | string
  last_name?: Prisma.StringFieldUpdateOperationsInput | string
  patronymic?: Prisma.StringFieldUpdateOperationsInput | string
  overdue_tasks?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  score?: Prisma.IntFieldUpdateOperationsInput | number
  studyGroupId?: Prisma.IntFieldUpdateOperationsInput | number
  request?: Prisma.RequestUncheckedUpdateOneWithoutUserNestedInput
  userHomeworks?: Prisma.UserHomeworkUncheckedUpdateManyWithoutUserNestedInput
}

export type UserCreateWithoutStudyGroupInput = {
  id: bigint | number
  username?: string | null
  yandex_email: string
  verified?: boolean
  name: string
  last_name: string
  patronymic: string
  overdue_tasks?: number
  createdAt?: Date | string
  role?: $Enums.Role
  score?: number
  request?: Prisma.RequestCreateNestedOneWithoutUserInput
  userHomeworks?: Prisma.UserHomeworkCreateNestedManyWithoutUserInput
  studyGroupRelations?: Prisma.StudyGroupRelationCreateNestedManyWithoutUserInput
}

export type UserUncheckedCreateWithoutStudyGroupInput = {
  id: bigint | number
  username?: string | null
  yandex_email: string
  verified?: boolean
  name: string
  last_name: string
  patronymic: string
  overdue_tasks?: number
  createdAt?: Date | string
  role?: $Enums.Role
  score?: number
  request?: Prisma.RequestUncheckedCreateNestedOneWithoutUserInput
  userHomeworks?: Prisma.UserHomeworkUncheckedCreateNestedManyWithoutUserInput
  studyGroupRelations?: Prisma.StudyGroupRelationUncheckedCreateNestedManyWithoutUserInput
}

export type UserCreateOrConnectWithoutStudyGroupInput = {
  where: Prisma.UserWhereUniqueInput
  create: Prisma.XOR<Prisma.UserCreateWithoutStudyGroupInput, Prisma.UserUncheckedCreateWithoutStudyGroupInput>
}

export type UserCreateManyStudyGroupInputEnvelope = {
  data: Prisma.UserCreateManyStudyGroupInput | Prisma.UserCreateManyStudyGroupInput[]
  skipDuplicates?: boolean
}

export type UserUpsertWithWhereUniqueWithoutStudyGroupInput = {
  where: Prisma.UserWhereUniqueInput
  update: Prisma.XOR<Prisma.UserUpdateWithoutStudyGroupInput, Prisma.UserUncheckedUpdateWithoutStudyGroupInput>
  create: Prisma.XOR<Prisma.UserCreateWithoutStudyGroupInput, Prisma.UserUncheckedCreateWithoutStudyGroupInput>
}

export type UserUpdateWithWhereUniqueWithoutStudyGroupInput = {
  where: Prisma.UserWhereUniqueInput
  data: Prisma.XOR<Prisma.UserUpdateWithoutStudyGroupInput, Prisma.UserUncheckedUpdateWithoutStudyGroupInput>
}

export type UserUpdateManyWithWhereWithoutStudyGroupInput = {
  where: Prisma.UserScalarWhereInput
  data: Prisma.XOR<Prisma.UserUpdateManyMutationInput, Prisma.UserUncheckedUpdateManyWithoutStudyGroupInput>
}

export type UserScalarWhereInput = {
  AND?: Prisma.UserScalarWhereInput | Prisma.UserScalarWhereInput[]
  OR?: Prisma.UserScalarWhereInput[]
  NOT?: Prisma.UserScalarWhereInput | Prisma.UserScalarWhereInput[]
  id?: Prisma.BigIntFilter<"User"> | bigint | number
  username?: Prisma.StringNullableFilter<"User"> | string | null
  yandex_email?: Prisma.StringFilter<"User"> | string
  verified?: Prisma.BoolFilter<"User"> | boolean
  name?: Prisma.StringFilter<"User"> | string
  last_name?: Prisma.StringFilter<"User"> | string
  patronymic?: Prisma.StringFilter<"User"> | string
  overdue_tasks?: Prisma.IntFilter<"User"> | number
  createdAt?: Prisma.DateTimeFilter<"User"> | Date | string
  role?: Prisma.EnumRoleFilter<"User"> | $Enums.Role
  score?: Prisma.IntFilter<"User"> | number
  studyGroupId?: Prisma.IntFilter<"User"> | number
}

export type UserCreateManyStudyGroupInput = {
  id: bigint | number
  username?: string | null
  yandex_email: string
  verified?: boolean
  name: string
  last_name: string
  patronymic: string
  overdue_tasks?: number
  createdAt?: Date | string
  role?: $Enums.Role
  score?: number
}

export type UserUpdateWithoutStudyGroupInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  yandex_email?: Prisma.StringFieldUpdateOperationsInput | string
  verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  name?: Prisma.StringFieldUpdateOperationsInput | string
  last_name?: Prisma.StringFieldUpdateOperationsInput | string
  patronymic?: Prisma.StringFieldUpdateOperationsInput | string
  overdue_tasks?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  score?: Prisma.IntFieldUpdateOperationsInput | number
  request?: Prisma.RequestUpdateOneWithoutUserNestedInput
  userHomeworks?: Prisma.UserHomeworkUpdateManyWithoutUserNestedInput
  studyGroupRelations?: Prisma.StudyGroupRelationUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateWithoutStudyGroupInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  yandex_email?: Prisma.StringFieldUpdateOperationsInput | string
  verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  name?: Prisma.StringFieldUpdateOperationsInput | string
  last_name?: Prisma.StringFieldUpdateOperationsInput | string
  patronymic?: Prisma.StringFieldUpdateOperationsInput | string
  overdue_tasks?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  score?: Prisma.IntFieldUpdateOperationsInput | number
  request?: Prisma.RequestUncheckedUpdateOneWithoutUserNestedInput
  userHomeworks?: Prisma.UserHomeworkUncheckedUpdateManyWithoutUserNestedInput
  studyGroupRelations?: Prisma.StudyGroupRelationUncheckedUpdateManyWithoutUserNestedInput
}

export type UserUncheckedUpdateManyWithoutStudyGroupInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  username?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  yandex_email?: Prisma.StringFieldUpdateOperationsInput | string
  verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  name?: Prisma.StringFieldUpdateOperationsInput | string
  last_name?: Prisma.StringFieldUpdateOperationsInput | string
  patronymic?: Prisma.StringFieldUpdateOperationsInput | string
  overdue_tasks?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  role?: Prisma.EnumRoleFieldUpdateOperationsInput | $Enums.Role
  score?: Prisma.IntFieldUpdateOperationsInput | number
}


/**
 * Count Type UserCountOutputType
 */

export type UserCountOutputType = {
  userHomeworks: number
  studyGroupRelations: number
}

export type UserCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  userHomeworks?: boolean | UserCountOutputTypeCountUserHomeworksArgs
  studyGroupRelations?: boolean | UserCountOutputTypeCountStudyGroupRelationsArgs
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserCountOutputType
   */
  select?: Prisma.UserCountOutputTypeSelect<ExtArgs> | null
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountUserHomeworksArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserHomeworkWhereInput
}

/**
 * UserCountOutputType without action
 */
export type UserCountOutputTypeCountStudyGroupRelationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.StudyGroupRelationWhereInput
}


export type UserSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  username?: boolean
  yandex_email?: boolean
  verified?: boolean
  name?: boolean
  last_name?: boolean
  patronymic?: boolean
  overdue_tasks?: boolean
  createdAt?: boolean
  role?: boolean
  score?: boolean
  studyGroupId?: boolean
  request?: boolean | Prisma.User$requestArgs<ExtArgs>
  StudyGroup?: boolean | Prisma.StudyGroupDefaultArgs<ExtArgs>
  userHomeworks?: boolean | Prisma.User$userHomeworksArgs<ExtArgs>
  studyGroupRelations?: boolean | Prisma.User$studyGroupRelationsArgs<ExtArgs>
  _count?: boolean | Prisma.UserCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["user"]>

export type UserSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  username?: boolean
  yandex_email?: boolean
  verified?: boolean
  name?: boolean
  last_name?: boolean
  patronymic?: boolean
  overdue_tasks?: boolean
  createdAt?: boolean
  role?: boolean
  score?: boolean
  studyGroupId?: boolean
  StudyGroup?: boolean | Prisma.StudyGroupDefaultArgs<ExtArgs>
}, ExtArgs["result"]["user"]>

export type UserSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  username?: boolean
  yandex_email?: boolean
  verified?: boolean
  name?: boolean
  last_name?: boolean
  patronymic?: boolean
  overdue_tasks?: boolean
  createdAt?: boolean
  role?: boolean
  score?: boolean
  studyGroupId?: boolean
  StudyGroup?: boolean | Prisma.StudyGroupDefaultArgs<ExtArgs>
}, ExtArgs["result"]["user"]>

export type UserSelectScalar = {
  id?: boolean
  username?: boolean
  yandex_email?: boolean
  verified?: boolean
  name?: boolean
  last_name?: boolean
  patronymic?: boolean
  overdue_tasks?: boolean
  createdAt?: boolean
  role?: boolean
  score?: boolean
  studyGroupId?: boolean
}

export type UserOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "username" | "yandex_email" | "verified" | "name" | "last_name" | "patronymic" | "overdue_tasks" | "createdAt" | "role" | "score" | "studyGroupId", ExtArgs["result"]["user"]>
export type UserInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  request?: boolean | Prisma.User$requestArgs<ExtArgs>
  StudyGroup?: boolean | Prisma.StudyGroupDefaultArgs<ExtArgs>
  userHomeworks?: boolean | Prisma.User$userHomeworksArgs<ExtArgs>
  studyGroupRelations?: boolean | Prisma.User$studyGroupRelationsArgs<ExtArgs>
  _count?: boolean | Prisma.UserCountOutputTypeDefaultArgs<ExtArgs>
}
export type UserIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  StudyGroup?: boolean | Prisma.StudyGroupDefaultArgs<ExtArgs>
}
export type UserIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  StudyGroup?: boolean | Prisma.StudyGroupDefaultArgs<ExtArgs>
}

export type $UserPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "User"
  objects: {
    request: Prisma.$RequestPayload<ExtArgs> | null
    StudyGroup: Prisma.$StudyGroupPayload<ExtArgs>
    userHomeworks: Prisma.$UserHomeworkPayload<ExtArgs>[]
    studyGroupRelations: Prisma.$StudyGroupRelationPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: bigint
    username: string | null
    yandex_email: string
    verified: boolean
    name: string
    last_name: string
    patronymic: string
    overdue_tasks: number
    createdAt: Date
    role: $Enums.Role
    score: number
    studyGroupId: number
  }, ExtArgs["result"]["user"]>
  composites: {}
}

export type UserGetPayload<S extends boolean | null | undefined | UserDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UserPayload, S>

export type UserCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UserFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UserCountAggregateInputType | true
  }

export interface UserDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['User'], meta: { name: 'User' } }
  /**
   * Find zero or one User that matches the filter.
   * @param {UserFindUniqueArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UserFindUniqueArgs>(args: Prisma.SelectSubset<T, UserFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one User that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UserFindUniqueOrThrowArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UserFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UserFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first User that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFindFirstArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UserFindFirstArgs>(args?: Prisma.SelectSubset<T, UserFindFirstArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first User that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFindFirstOrThrowArgs} args - Arguments to find a User
   * @example
   * // Get one User
   * const user = await prisma.user.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UserFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UserFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Users that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Users
   * const users = await prisma.user.findMany()
   * 
   * // Get first 10 Users
   * const users = await prisma.user.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const userWithIdOnly = await prisma.user.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends UserFindManyArgs>(args?: Prisma.SelectSubset<T, UserFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a User.
   * @param {UserCreateArgs} args - Arguments to create a User.
   * @example
   * // Create one User
   * const User = await prisma.user.create({
   *   data: {
   *     // ... data to create a User
   *   }
   * })
   * 
   */
  create<T extends UserCreateArgs>(args: Prisma.SelectSubset<T, UserCreateArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Users.
   * @param {UserCreateManyArgs} args - Arguments to create many Users.
   * @example
   * // Create many Users
   * const user = await prisma.user.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UserCreateManyArgs>(args?: Prisma.SelectSubset<T, UserCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Users and returns the data saved in the database.
   * @param {UserCreateManyAndReturnArgs} args - Arguments to create many Users.
   * @example
   * // Create many Users
   * const user = await prisma.user.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Users and only return the `id`
   * const userWithIdOnly = await prisma.user.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UserCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UserCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a User.
   * @param {UserDeleteArgs} args - Arguments to delete one User.
   * @example
   * // Delete one User
   * const User = await prisma.user.delete({
   *   where: {
   *     // ... filter to delete one User
   *   }
   * })
   * 
   */
  delete<T extends UserDeleteArgs>(args: Prisma.SelectSubset<T, UserDeleteArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one User.
   * @param {UserUpdateArgs} args - Arguments to update one User.
   * @example
   * // Update one User
   * const user = await prisma.user.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UserUpdateArgs>(args: Prisma.SelectSubset<T, UserUpdateArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Users.
   * @param {UserDeleteManyArgs} args - Arguments to filter Users to delete.
   * @example
   * // Delete a few Users
   * const { count } = await prisma.user.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UserDeleteManyArgs>(args?: Prisma.SelectSubset<T, UserDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Users.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Users
   * const user = await prisma.user.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UserUpdateManyArgs>(args: Prisma.SelectSubset<T, UserUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Users and returns the data updated in the database.
   * @param {UserUpdateManyAndReturnArgs} args - Arguments to update many Users.
   * @example
   * // Update many Users
   * const user = await prisma.user.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Users and only return the `id`
   * const userWithIdOnly = await prisma.user.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UserUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UserUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one User.
   * @param {UserUpsertArgs} args - Arguments to update or create a User.
   * @example
   * // Update or create a User
   * const user = await prisma.user.upsert({
   *   create: {
   *     // ... data to create a User
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the User we want to update
   *   }
   * })
   */
  upsert<T extends UserUpsertArgs>(args: Prisma.SelectSubset<T, UserUpsertArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Users.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserCountArgs} args - Arguments to filter Users to count.
   * @example
   * // Count the number of Users
   * const count = await prisma.user.count({
   *   where: {
   *     // ... the filter for the Users we want to count
   *   }
   * })
  **/
  count<T extends UserCountArgs>(
    args?: Prisma.Subset<T, UserCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UserCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a User.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UserAggregateArgs>(args: Prisma.Subset<T, UserAggregateArgs>): Prisma.PrismaPromise<GetUserAggregateType<T>>

  /**
   * Group by User.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UserGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UserGroupByArgs['orderBy'] }
      : { orderBy?: UserGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UserGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the User model
 */
readonly fields: UserFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for User.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UserClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  request<T extends Prisma.User$requestArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$requestArgs<ExtArgs>>): Prisma.Prisma__RequestClient<runtime.Types.Result.GetResult<Prisma.$RequestPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  StudyGroup<T extends Prisma.StudyGroupDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.StudyGroupDefaultArgs<ExtArgs>>): Prisma.Prisma__StudyGroupClient<runtime.Types.Result.GetResult<Prisma.$StudyGroupPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  userHomeworks<T extends Prisma.User$userHomeworksArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$userHomeworksArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserHomeworkPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  studyGroupRelations<T extends Prisma.User$studyGroupRelationsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.User$studyGroupRelationsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StudyGroupRelationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the User model
 */
export interface UserFieldRefs {
  readonly id: Prisma.FieldRef<"User", 'BigInt'>
  readonly username: Prisma.FieldRef<"User", 'String'>
  readonly yandex_email: Prisma.FieldRef<"User", 'String'>
  readonly verified: Prisma.FieldRef<"User", 'Boolean'>
  readonly name: Prisma.FieldRef<"User", 'String'>
  readonly last_name: Prisma.FieldRef<"User", 'String'>
  readonly patronymic: Prisma.FieldRef<"User", 'String'>
  readonly overdue_tasks: Prisma.FieldRef<"User", 'Int'>
  readonly createdAt: Prisma.FieldRef<"User", 'DateTime'>
  readonly role: Prisma.FieldRef<"User", 'Role'>
  readonly score: Prisma.FieldRef<"User", 'Int'>
  readonly studyGroupId: Prisma.FieldRef<"User", 'Int'>
}
    

// Custom InputTypes
/**
 * User findUnique
 */
export type UserFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User findUniqueOrThrow
 */
export type UserFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User findFirst
 */
export type UserFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Users.
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Users.
   */
  distinct?: Prisma.UserScalarFieldEnum | Prisma.UserScalarFieldEnum[]
}

/**
 * User findFirstOrThrow
 */
export type UserFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which User to fetch.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Users.
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Users.
   */
  distinct?: Prisma.UserScalarFieldEnum | Prisma.UserScalarFieldEnum[]
}

/**
 * User findMany
 */
export type UserFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter, which Users to fetch.
   */
  where?: Prisma.UserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Users to fetch.
   */
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Users.
   */
  cursor?: Prisma.UserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Users.
   */
  skip?: number
  distinct?: Prisma.UserScalarFieldEnum | Prisma.UserScalarFieldEnum[]
}

/**
 * User create
 */
export type UserCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * The data needed to create a User.
   */
  data: Prisma.XOR<Prisma.UserCreateInput, Prisma.UserUncheckedCreateInput>
}

/**
 * User createMany
 */
export type UserCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Users.
   */
  data: Prisma.UserCreateManyInput | Prisma.UserCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * User createManyAndReturn
 */
export type UserCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * The data used to create many Users.
   */
  data: Prisma.UserCreateManyInput | Prisma.UserCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * User update
 */
export type UserUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * The data needed to update a User.
   */
  data: Prisma.XOR<Prisma.UserUpdateInput, Prisma.UserUncheckedUpdateInput>
  /**
   * Choose, which User to update.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User updateMany
 */
export type UserUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Users.
   */
  data: Prisma.XOR<Prisma.UserUpdateManyMutationInput, Prisma.UserUncheckedUpdateManyInput>
  /**
   * Filter which Users to update
   */
  where?: Prisma.UserWhereInput
  /**
   * Limit how many Users to update.
   */
  limit?: number
}

/**
 * User updateManyAndReturn
 */
export type UserUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * The data used to update Users.
   */
  data: Prisma.XOR<Prisma.UserUpdateManyMutationInput, Prisma.UserUncheckedUpdateManyInput>
  /**
   * Filter which Users to update
   */
  where?: Prisma.UserWhereInput
  /**
   * Limit how many Users to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * User upsert
 */
export type UserUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * The filter to search for the User to update in case it exists.
   */
  where: Prisma.UserWhereUniqueInput
  /**
   * In case the User found by the `where` argument doesn't exist, create a new User with this data.
   */
  create: Prisma.XOR<Prisma.UserCreateInput, Prisma.UserUncheckedCreateInput>
  /**
   * In case the User was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UserUpdateInput, Prisma.UserUncheckedUpdateInput>
}

/**
 * User delete
 */
export type UserDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  /**
   * Filter which User to delete.
   */
  where: Prisma.UserWhereUniqueInput
}

/**
 * User deleteMany
 */
export type UserDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Users to delete
   */
  where?: Prisma.UserWhereInput
  /**
   * Limit how many Users to delete.
   */
  limit?: number
}

/**
 * User.request
 */
export type User$requestArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Request
   */
  select?: Prisma.RequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Request
   */
  omit?: Prisma.RequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RequestInclude<ExtArgs> | null
  where?: Prisma.RequestWhereInput
}

/**
 * User.userHomeworks
 */
export type User$userHomeworksArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserHomework
   */
  select?: Prisma.UserHomeworkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserHomework
   */
  omit?: Prisma.UserHomeworkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserHomeworkInclude<ExtArgs> | null
  where?: Prisma.UserHomeworkWhereInput
  orderBy?: Prisma.UserHomeworkOrderByWithRelationInput | Prisma.UserHomeworkOrderByWithRelationInput[]
  cursor?: Prisma.UserHomeworkWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.UserHomeworkScalarFieldEnum | Prisma.UserHomeworkScalarFieldEnum[]
}

/**
 * User.studyGroupRelations
 */
export type User$studyGroupRelationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudyGroupRelation
   */
  select?: Prisma.StudyGroupRelationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudyGroupRelation
   */
  omit?: Prisma.StudyGroupRelationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudyGroupRelationInclude<ExtArgs> | null
  where?: Prisma.StudyGroupRelationWhereInput
  orderBy?: Prisma.StudyGroupRelationOrderByWithRelationInput | Prisma.StudyGroupRelationOrderByWithRelationInput[]
  cursor?: Prisma.StudyGroupRelationWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.StudyGroupRelationScalarFieldEnum | Prisma.StudyGroupRelationScalarFieldEnum[]
}

/**
 * User without action
 */
export type UserDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
}
